### PR TITLE
Improve support for french language

### PR DESCRIPTION
**Pull request by Lipucciu**
French translation : 100%

### CODE REVIEW

**Comment by tomasbrod** [comment]
rebase on development

**Comment by Lipucciu** [comment]
Blocked here with Git for today : 
```
fatal: Needed a single revision
invalid upstream HEAD~1
```
I'll try to do it tomorrow.

**Comment by iFoggz** [comment]
ravon can just move the destination over should be alright

thank you for your contribution

**Comment by Lipucciu** [comment]
Nice if it could be alright because I don't find the git problem (first PR here). Keep it up !

**Pull request merged**
