### PR TITLE
Fix SSL RPC issues

### PR DESCRIPTION
**Pull request by denravonska**
Changes to make the RPC handlers multithreaded, and to fix an old issue where connecting using SSL to a non-SSL wallet freezes the RPC handler. We believe this is what's causing Bittrex to have issues with their RPC calls.

This conflicts with the changes done in dev/ but I will move the code to the appropriate locations when merged.

### CODE REVIEW

**Comment by tomasbrod** [comment]
Now I see why the RPCs are getting blocked. The protocol parser(?w) is written as sequential process, instead of event-driven state-machine, even thought ASIO is being used.
Instead of spawning x (4) threads in worker pool, what about spawning a one thread for each connection?

**Comment by denravonska** [comment]
We used to do that but the thread spawning had such a high overhead. If my measurements were correct in a85de02ccf6c6a8ff4908813a2ef6767b7585d98 (its comment regarding ASIO is somewhat incorrect) then traversing the entire chain using RPC takes 21-22h longer when spawning a thread for each request.

**Comment by tomasbrod** [comment]
Ouch, that is a significant overhead. Then maybe a new worker thread could be spawned when the thread pool is getting thin?
Or do it in the way I find the most elegant (as in beauty), but not easy: Write the parser in some regular language language, such as Ragel, and have it compiled to C state machine. This way also asio could be eliminated.

**Comment by denravonska** [comment]
This PR is more of a workaround or modernisation until we have ported the changes from Bitcoin or rebased. Their solution was to drop asio in favour of libevent2. It's implementation is way more straight forward, see https://github.com/bitcoin/bitcoin/pull/5677

**Comment by tomasbrod** [comment]
Hopefully they are using the same libevent for the peer-to-peer connections, instead of the homebrew one in net.cpp.

**Pull request merged**
