### PR TITLE
Do not replace underscores by spaces in Qt Poll URLs

### LINKED ISSUE #1325: Poll URLs can't contain underscores
(I posted a message to discord/IRC \#gridcoin channel earlier today.)

When polls are created, any spaces in the discussion URL (among other attributes) are converted to underscores (`_`), and then when displayed, these are converted to spaces. However, if the URL originally contains underscores these are incorrectly displayed as spaces, which can cause URLs to break.

Having looked at some of the [past polls](https://gridcoinstats.eu/poll), I have not yet found any URLs that look as if spaces have been intentionally included, whereas I have found several that had underscores in the first place. Though the only truly "broken" one I've found so far is the URL for [missing-logic:\_project\_equality\_poll\_(abstain,_etc)](https://gridcoinstats.eu/poll/missing-logic:_project_equality_poll_(abstain,_etc)); others were Reddit URLs which happen to work if underscores are substituted with spaces.

I think the behavior of the wallet can be changed without breaking existing polls (and actually fixing the affected one):
1. when creating polls, don't convert spaces in URLs to underscores (use some other approach to deal with them if they aren't allowed, e.g. converting them to `%20`, or not allowing a poll to be created with them); and
1. when displaying poll URLs, don't convert underscores to spaces.

A workaround to preserve underscores when creating polls would be to manually escape them as `%5f` in the URL.

### PR DESCRIPTION
**Pull request by tomasbrod**
Fix #1325 .
Todo: check how are urls handled when creating a poll.

### CODE REVIEW

**Comment by denravonska** [comment]
This conflicts with #1179. Why are spaces an issue to begin with?

**Comment by tomasbrod** [comment]
Because it cahnges underscores into spaces in the URL. Spaces in URL.
Like it would add spaces to originally legit url.

**Comment by denravonska** [comment]
I mean why do we convert spaces to underscore?

**Comment by tomasbrod** [comment]
It does not convert spaces to underscores. It converts underscores to spaces. In URL, that does not make any sense.

**Comment by denravonska** [comment]
But why does any conversion take place at all? Is there a technical reason for not using spaces when the data is entered?

**Comment by tomasbrod** [comment]
The conversion happens, because someone put it there in error. This PR removes the conversion.

**Comment by denravonska** [comment]
I think no conversion should be done at all, neither on the poll entrance nor on the display. But we'll leave that for a separate PR.

**Comment by tomasbrod** [comment]
There is no conversion of spaces in URLs to underscores on the entrance. There should be no spaces in url to begin with.

**Pull request merged**
