### PR TITLE
gui: Implement Alt-7 for unlock and lock of wallet

### LINKED ISSUE #2257: User interface: keyboard shortcuts in v5.3.2.0
# Bug Report

**Current behavior**

In the v5.3.2.0 update, the user interface now includes one drop down menu for everything. It does not appear to respect the "alt" button to key into the menu items for navigation via the keyboard.

**Expected behavior**

When I first open the application, I can immediately begin staking using keyboard shortcuts only (this is really the only keyboard shortcut I care about, honestly).

**Steps to reproduce:**

N/A

**Screenshots**

image

image

**Gridcoin version**

v.5.3.2.0, Linux, Cinnamon

### PR DESCRIPTION
**Pull request by jamescowens**
Self explanatory. Closes #2257.

### CODE REVIEW

**Comment by barton2526** [comment]
Is there any reasoning why Alt-7 specifically was chosen?

**Comment by div72** [comment]
@barton2526 Alt keys from 1 to 6 are shortcuts for tabs on left. Since the unlock wallet button is below the tabs, I suppose it is regarded as the seventh tab.

**Comment by jamescowens** [comment]
@barton2526 I assume your upcheck means you are ok. I am going ahead and merging.

**Comment by barton2526** [comment]
Sorry for the delay.  TACK

**Comment by jamescowens** [comment]
Thanks! :)

**Pull request merged**
