### PR TITLE
log: Adjust logging

### LINKED ISSUE #2055: Can we change [AcceptToMemoryPool : Unable to connect to inputs ‘n’] from an ‘Error’  to ‘Info’
Can we maybe change [AcceptToMemoryPool : Unable to connect to inputs ‘n’] from an ‘Error’  to ‘Info’

This happened to BTC back in 2015 . Source: https://github.com/bitcoin/bitcoin/issues/6518

and they changed it from ‘Error’ to something else. The GridcoinResearch debug log will, of course, show less errors then. Not a biggy ; only 6 of these entries in the last 3 days.

### PR DESCRIPTION
**Pull request by jamescowens**
This PR straightens out some of the worst non-conformity in logging. I did not do a completely exhaustive review, but fixed the most obvious issues through the codebase. This also closes #2055.

### CODE REVIEW

**Comment by cyrossignol** [comment]
This is going to create a lot of conflicts with #2006.

**Comment by jamescowens** [comment]
Probably so. I don't know why #2006 hasn't been finished by now. We are going to have to make a choice.

**Comment by jamescowens** [comment]
I have downscoped this to reduce conflicts for #2006 with the expectation that @div72 will get that PR done and merged, than I will  rebase the left out commits on top of development and will create another PR to track the further logging cleanup after #2006 is merged.

**Review by cyrossignol — APPROVED** [review]

**Comment by div72** [comment]
@jamescowens Apologies, bit short on time lately. Will do.

**Comment by jamescowens** [comment]
No problem! Let's just don't leave it hanging out there for too long, ok?

**Pull request merged**
