### PR TITLE
diag: fix researcher mode check

### PR DESCRIPTION
**Pull request by div72**
Fixes a non-deterministic crash that can happen due to a std::optional being dereferenced when it has no value:
https://github.com/gridcoin-community/Gridcoin-Research/blob/8477d94403f168d7fdb189654b98a2fa4da5615f/src/wallet/diagnose.h#L536

Sadly it's non-deterministic, as dereferencing a non-valued std::optional is UB; compilers/stdlib is allowed to not have any checks. It results in a randomized garbage CPID being read on the machine I'm currently on.

### CODE REVIEW

**Comment by jamescowens** [comment]
Your commit does not address the comment above?

**Comment by jamescowens** [comment]
A fix for your comment could be

```
        const GRC::BeaconRegistry& beacons = GRC::GetBeaconRegistry();
        if (const GRC::CpidOption cpid = GRC::Researcher::Get()->Id().TryCpid()) {
            if (const GRC::BeaconOption beacon = beacons.Try(*cpid)) {
                if (!beacon->Expired(GetAdjustedTime())) {
                    return true;
                }
                for (const auto& beacon_ptr : beacons.FindPending(*cpid)) {
                    if (!beacon_ptr->Expired(GetAdjustedTime())) {
                        return true;
                    }
                }
            }
        }
        return false;
```

**Comment by div72** [comment]
I can add a `cpid &&` to the if condition if that's what you are asking. The commit fixes the issue by preventing the function from getting called in cases where cpid optional may not have a value.

I think it'd be the best if we had a linter which enforces optionals to be either proven to have a value or be checked, so that every optional in the entire codebase is checked.

**Comment by div72** [comment]
> Your commit does not address the comment above?

The function is not called in the first case if the CPID is null with the commit. I can add another check with a warning if you want.

It'd the best if we had a linter which enforced this.

**Comment by jamescowens** [comment]
I understand that, but it is more correct to fix the behavior at the source. *cpid should be guarded.

Your actual commit is of course correct.

We should do something with the linter for this if possible.

**Review by jamescowens — APPROVED** [review]
utACK

**Pull request merged**
