### PR TITLE
Reduce RAM usage

### PR DESCRIPTION
**Pull request by denravonska**
Remove unused variables from CBlockIndex and remove redundant std::string assignments in constructor.

sizeof(CBlockIndex) drops from 408 to 360 bytes and the overall memory consumption
drops from peak 453MiB to 417MiB, or by 8%.

This should help #153 slightly.

### CODE REVIEW

**Comment by grctest** [comment]
These changes would require a mandatory upgrade, no? And the block explorers would have to adapt their code. It would require several weeks of notice for the exchanges.

We'd need to rebuild the blockchain with these new rules, no?

**Comment by denravonska** [comment]
There should be no need for changes unless the CBlockIndex struct is written straight to disk without being serialized on a per member basis, and I couldn't find any of that for that particular struct. I guess Rob could give the final word on that.

**Comment by denravonska** [comment]
I just pushed another update which uses boost::flyweight for the CPID- and address strings in the block index. Since many of these are repeating strings and since `std::string` has quite the overhead, this reduces the memory usage by 10% compared to baseline. With all these fixes the peak memory requirement has gone down from 473MiB to 389.1MiB, or 17.7%.

I realize that this is just us trying to keep our head above the water and eventually when the number of blocks increase we will still drown. In the long run we could perhaps try to find a way to only keep the most recent blocks in RAM and only deserialize stored blocks from disk when necessary.

**Comment by denravonska** [comment]
#171 makes the flyweight commits redundant, I think.

**Comment by denravonska** [comment]
Closing this since it makes the code inconsistent and there are better ways of solving the RAM issue. See #176. The unused variables should still be removed though but that's easily done manually.

**Comment by tomasbrod** [comment]
- sCPID -> pointer to some global cpid table
- sLastPORBlockHash, sLastPORBlock, prevoutStake -> replace with pointer the relevant block in index
- nIsSuperBlock, nIsContract -> move to nFlags
- sGRCAddress -> binary fixed length char[]

I haven't read the code so take this with reserve.

**Comment by denravonska** [comment]
@tomasbrod That's pretty much exactly what I did:

- sCPID and sGRCAddress were switched to a flyweight string pool. No repeated strings, but lots of `.get()` calls in the code.
- Tried moving nIsSuperBlock and nIsContract to the flags with no change. I suppose the compiler is smart enough to do it.

I think the only way forward is to move the data to the blocks. It will slow things down, but that should be solvable.

**Pull request closed without merging**
