### PR TITLE
depends: add cross arm64-darwin support

### PR DESCRIPTION
**Pull request by div72**
This PR adds arm64-darwin support for depends. Also removes the LLVM toolchain from the depends, a recent version of clang is now required for MacOS cross builds.

Updates libzip to 1.10.1. CMake is now required for depends. bzip2 is removed from depends.

CD output tested on a M1 Mac, starts without an issue.

### CODE REVIEW

**Comment by div72** [comment]
@jamescowens What are we building bzip2 in depends for?

**Comment by jamescowens** [comment]
Probably nothing. I think it came along for the ride with the original depends port.Sent from my iPhoneOn Sep 15, 2024, at 8:05 PM, div72 ***@***.***> wrote:﻿
@jamescowens What are we building bzip2 in depends for?

**Review by jamescowens — COMMENTED** [review]
Looks ok to me. Can we get all of the CI jobs working before I merge this?

**Comment by div72** [comment]
Just rebased, all green now.

**Review by jamescowens — APPROVED** [review]
ACK

**Pull request merged**
