### PR TITLE
Gridcoin Chinese Translation

### PR DESCRIPTION
**Pull request by mrip0001**
Hey guys！ Gridcoin to da moon！恭喜发财！

### CODE REVIEW

**Comment by denravonska** [comment]
Sweet! Was this made on master or dev?

**Comment by mrip0001** [comment]
Sorry I‘m new to here and don't know there are different branches. I believe I choosed the master branch.

**Review by tomasbrod — APPROVED** [review]
Yeah, this one is based the master branch. It is written just under the title (sorry if stating the obvious).
I suggest --squash when merging this in.

**Comment by denravonska** [comment]
@mrip001 No worries, I'll merge this to dev. There will be a handfull of new translations there.

**Comment by denravonska** [comment]
I have merged the translations to dev but there were a couple of errors. Can you please finalize the translations from dev in Qt Linguist instead of a manual editor? Check translations and tools here:

https://github.com/gridcoin/Gridcoin-Research/blob/development/src/qt/locale/bitcoin_zh_CN.ts
https://github.com/lelegard/qtlinguist-installers/releases

**Comment by mrip0001** [comment]
Ok， I‘ll try to fix it

**Pull request merged**
