### PR TITLE
beacon: Specialized beacon storage in leveldb

### PR DESCRIPTION
**Pull request by jamescowens**
This is currently a "tracking" PR to track my and now @div72's work on implementing a specialized beacon storage area in leveldb to solve the beacon lookback problem. When this is successful, we can return the lookback to MAX_AGE (180 days) from 2 * MAX_AGE for the lookback for contracts.

This builds on #2008. I intend on #2008 to go into Hilda. I am not sure yet about this.

The concept of this PR is to effectively record the beacon actions in a historical log in leveldb. To accomplish this and support wallets that are already in sync or at various stages of sync, a variable lookback scheme is employed in the contract replay. The contract lookback is now the interval that starts at the provided high height and stretches back to

std::min(std::max(beacon_db_height, V11_height), lookback_window_low_height);

The beacon_db_height is populated by querying the beacon db, which contains the height to where beacons were recorded in leveldb. (This is also stored in leveldb.) On an initial sync, or a wallet startup with the wallet in sync from the prior shutdown, but using prior code without the beacon_db, the beacon_db_height will be zero.

Given that the beacon_db could have been partially populated during a sync from zero, the std::max ensures that the replay will start at the greater of the beacon_db height or V11_height, and the lesser of THAT and the standard lookback window (180 day) low height. This ensures that the beacon_db population at all times includes V11 or above beacons, but also from the contract replay perspective, the contracts get at least a 180 day lookback (unless one is syncing from zero and the 180 day lookback is reduced when the genesis block is hit).

Once the beacon_db is populated to a height that intersects the heights in the range of the contract replay, the beacon contract and superblock beacon activation replays are SKIPPED for heights less than the beacon db height, because that information is already filled in by the beacon db initialization, which "replays" the results of those contracts from the beacon db instead. The contract replay of the beacon contracts resumes at the beacon db height up to the head of the chain (and in so doing also populates the beacon db to the new height, and a new beacon db height is recorded as each beacon contract is memorized).

During block reorganizations, the BeaconRegistry::Revert is now used (the contract handler reset is now disabled for beacons) and the beacon db height reset to the common block at the root of the reorg during block disconnects. The contract replay will proceed as usual with a 180 day lookback for non-beacon contracts. The beacon contracts during the replay are SKIPPED until the height representing the reorg root is reached in the replay, at which point the beacon contracts will again be recorded (along the new branch) to the new chain head. All of this ensures that a complete history of beacons is maintained at least to the V11_height point. This ENSURES that the beacon "chainlets" formed by the pattern of Advertisement.... Pending.... Activation... Renewal.... Renewal... etc. for EACH CPID. are recorded correctly at all times.

The beacons now include a previous beacon hash, which allows reverse linkage from the last (active) beacon all the way to the original advertisement for each CPID. (This part was already implemented in #2008 as part of the fix for the newbie bug, but 2008 still had the lookback problem, which was temporarily compensated by doubling the lookback window.) I elected to retain the hash based one-way linked list here, which is slower than a pointer based approach, rather than convert to pointers on load and convert to hashes on save (which is what is done with the CBlockIndex*), as it is much simpler to store. Unlike CBlockIndex*, the beacon list traversals are not as common. In fact, the only time they are used at all is one step for the beacon renewal, the accrual correction function (for the newbie fix), and the auditsnapshotaccrual(s), which are all relatively uncommon executions, compared to things like CBlockIndex* which are used constantly.

Being mindful of the moderate increase in memory requirements due to the now more heavyweight memory requirements for the beacon objects, I converted the m_beacons (active beacon) map and the m_pending (pending beacon) maps to have elements of smart shared pointers pointing back to the elements in m_historical, which is where the actual beacon objects are stored now. This saves memory by not replicating beacon objects between historical and the active map or the pending map. This is especially important, since the same underlying object is pointed to by both maps, and the maps (on purpose) have different keys, the keys also have to be in the object.

Note that I have implemented a specialized find function on the beacon_db which wraps the find function of the underlying historical map, and looks in leveldb for the provided hash and then populates the historical map if found before returning the iterator. The intent of this is to be able to eliminate all but the active and pending cpids from the in-memory historical map. This is not fully thought through yet but the idea is that the only time elements before the current active list need to be accessed is for beacon renewals and reorganizations. For right now, the m_historical will include the complete set of beacons recorded from at least V11.

Part of the purpose of this PR was to minimally disturb the rest of the machinery using the beacon and associated classes, and I think I am accomplishing that goal.

Some comments about testing:

The initial testing and debug of this was done against testnet. There is an extensive amount of logging right now to gain visibility into the save and load machinery and how it interacts with contract replay. I had to repeatedly (maybe 50 times?) run this against mainnet using the following pattern, making adjustments and fixing subtle bugs to get everything to work:

As a prerequisite, save a copy of the blockchain database that is several days old. This allows a good contract replay, but also allows thousands of blocks to be synced (connected) post startup and several superblocks, to exercise the machinery.

1. Wipe the blockchain database.
2. Run the wallet with the test compile and allow the wallet to do the contract replay and several hundred blocks and a superblock to sync to verify the wallet is running correctly. This primes the leveldb beacon area.
3. Shut the wallet down
4. Restart the wallet. It will now load the beacon_db, which populates the beacons from leveldb rather than the contract replay.
5. Sync the wallet to the head and verify proper operation
6. Run an auditsnapshotaccruals report and compare to a production mainnet node (running 5.1.0.8 testnet code).

The runs against mainnet are very good at detecting all manner of whacky beacon situations... repeated advertisements, verifying an earlier advertisement rather than the latest, which leaves a "dangling" pending beacon, and believe it or not, verifying MORE than one pending beacon in the same superblock. Yes we have had that happen. (The original code effectively memorizes the last one in the vector of pending IDs provided that were verified by the scrapers.)

What the mainnet runs do not show is the interaction with the original problem of the lookback window's interaction with beacon renewals. For this the testnet chain was very useful. The testnet Fern hard fork was much earlier than mainnet, and so almost all the beacons on testnet have gone through a renewal cycle, with the original advertisements more than 180 days back in time from the head of the testnet chain. This immediately triggers the lookback beacon problem on testnet when the lookback is reset to 180 days, UNLESS the code in this PR is working properly, in which case operation will be normal both on a leveldb priming run and the restart.

I haven't yet fixed the testing harness to deal with all of this, which is why the Travis builds are failing. It would be nice to get some help in that area. I really think it would be a good idea to flash record the entire beacon contract replay from mainnet as it exists today, which includes some v 1 beacons the Fern hard fork, all of the forced expirations, and then the v 2 advertisements, as the input data block for the BOOST beacon unit test area, as it is a good exercise. UPDATE: @div72 is graciously working on this for me! :) [Update - @div72 did a good first pass and I did the comprehensive coding for a really thorough unit test that uses contract dumps from both testnet AND mainnet and replays them through the beacon registry to store in leveldb, then re initializes the registry to load the beacon state from leveldb and then does comprehensive comparisons.]

We should also record the testnet version to test for the beacon lookback bug as renewals have been processed there.

**Some additional comments:** 

This PR is part of a more general concept of the concept of chained contract state management, and contract reversion.

1. The simple contracts that are built into Gridcoin are not "smart" in the sense that they are independent in the individual sense,  but in the case of beacons, they have a "chained" state that is manifested on "CPID". This "chained" state is maintained by wallet in memory structures and is not built into the contracts themselves.
2. A general contract cache that supports reversion rather than replay would have to deal with these "chained states" related to the entity addressed by the contract. Some are relatively simple... such as the removal of vote weight... But others are more complex, like the beacons area I have dealt with in this PR. For example in the scraper area, we would have to implement a resurrection of an authorized scraper record from history if a scraper deauthorization were reverted. (Note that an extension of the appcache structure was implemented specific to the scraper precisely to deal with deleted scraper authorizations, similar to this...)
3. The necessary linkage has not been built into the existing contract system, and so at current the contract system depends on a reset and forward replay to arrive at the correct contract state.
4. Each different area of contracts will require different specializations for caching and state management that support reversion rather than replay.
5. I DID implement better generic serializable object storage, both at the individual object level and the store/load of entire maps using template programming in txdb-leveldb.h. I didn't like the existing generic functions, because they use string arguments, which injects an extra serialization/deserialization into the process. I think the templates I put in there are better, and will suppport leveldb storage of contract type historical "logs" by leveldb in other contract handlers.

One final note... you could ask why bother with all of this. Why not simply replay the contracts from the CBlockIndex from leveldb? In a nutshell, specialized storage of the contract state change results in leveldb, when appropriately implemented, should achieve higher performance than a general replay from the blockchain, because only a small portion of the blocks/transactions are actually involved compared to the general blockchain, and the results which were recorded in leveldb are stored from a full contract validation, so they do not need to be revalidated when played back from the specialized area (which is local node storage manifested from the local nodes' view of consensus). This should scale better as the number of participants increases and the chain continues to lengthen. Otherwise as the chain gets longer and longer, the lookback start would eventually have to be pinned at the Fern hard fork point, and the performance would degrade over time proportional to chain height. If we can implement other cache specializations in the other contract handlers which support the ::Revert function, we may be able to get to the point where there is no replay required at all.

An intermediate approach would be to store the raw contracts into a specialized area in leveldb to achieve higher performance than walking the whole CBlockIndex structure, but since the contracts do not include the necessary intrinsic linkage or state managment to support native reversion, they would be opaque to a revert, and you would be stuck with having to do forward replays like we do now. So that is not really a good way to go.

Some additional technical commentary now that this thing is about to be merged:

There is an inherent compromise in the choice of the key for the records stored in leveldb for the beacons. This same issue will be relevant for other contract handlers when we do the specializations, so it is worth discussing here.

The intention is to be able to have the historical map have only the latest (working set) of map entries actually present in memory. This is a head facing backwards question... If leveldb is going to contain historical elements that need to be recalled lazily (if removed from memory or never loaded)  by x_db.find(key), this would imply that the key needs to be the hash, as contracts invariably form chainlets with the prev_hash concept. So the natural key is the hash. This is what is implemented in the storage layer of the beacon database in this PR.

This generates a compromise however. When an iterator on leveldb walks through the records, it does it in the natural order of the key. If the hash is used as the key, then the order the iterator returns the records IS NOT COHERENT with the order in which the records were inserted. As we have found out from the nasty bug documented below, the actual order in which the contracts were recorded is important, and it is insufficient to use time as a proxy for that order. As a result, for the beacon database, the records are stored in leveldb in the form:

--------------- "beacon" -- hash -----------------record num --- Beacon
key: std::pair<std::string, uint256> value: std::pair<uint64_t, Beacon>

This method of storage preserves fast lookup of values by hash, which is the natural way to look up the records since beacons are identified by the hashes of their relevant transactions, etc. It has one nasty downside. The bulk load of state from leveldb in ::Initialize must use an intermediate (temporary) map which uses record number as the key to put the records in the right order for replay. This takes memory. IF I had chosen to store the records in leveldb using the continuously increasing record num, then the bulk load during Initialize would be fast, because the leveldb iterator would be in the correct order, but the leveldb lookup by hash would be very slow, especially on a regular hard disk.

I think I have made the right choice. The initialization is still very, very fast, only occurs once during wallet startup, and the additional memory used is released quickly because the temporary map is destroyed after initialization. And then since the key is by hash, the future storage and lookups by hash will be fast.

Note that we could write a very specialized map load function that would iterate through leveldb in the natural order, and then fill the storage map directly without an intermediate map, but this would require a specific beacon db implemention IN TXLEVELDB. I wrote template functions specifically to avoid more specialization at that low level, precisely because of the ugliness of the block index loader there, and not wanting to go down that road. Conversely with the template low level functions for storage and recall in txleveldb, we should be able to easily implement for other contract type caches.

### CODE REVIEW

**Comment by jamescowens** [comment]
Oh my what a difficult PR this has been to get right. I finally got it to run on reload with replaying the leveldb stored beacons and not fork off on testnet and a test node on mainnet. It is still a bit messy. Lots of clean-up to do. I will squash the commits as part of the cleanup.

**Comment by jamescowens** [comment]
I am currently working on changing the BeaconRegistry::Revert and Deactivate, because I don't think they properly cover all corner cases.

**Comment by jamescowens** [comment]
Ok. Thanks to a good start by @div72, making some serious progress on the unit tests for this. I am using cout temporarily on the test harness. Looks like it may have identified a subtle bug I had not found before in the renewal case. I will be chasing this down later today.

**Comment by jamescowens** [comment]
Dammit. Ugly, ugly, ugly.

Contract application in both block connects and contract replays (same thing effectively) is by the order of the transactions in the transaction vector in the block:

void GRC::ApplyContracts(
    const CBlock& block,
    const CBlockIndex* const pindex, const int& beacon_db_height,
    bool& out_found_contract)
{
    out_found_contract = false;

    // Skip coinbase and coinstake transactions:
    for (auto iter = std::next(block.vtx.begin(), 2), end = block.vtx.end();
        iter != end;
        ++iter)
    {
        ApplyContracts(*iter, pindex, beacon_db_height, out_found_contract);
    }
}

I have found an instance on testnet whether there were two beacon advertisement transactions (that were renewals essentially) on the same block for the same cpid. The renewal transaction that is at a higher index in the transaction vector in the block has AN EARLIER TIME. This breaks the ordering scheme on the state load using the key pair(cpid, time):

The log of an initial load (with the beacon storage cleared):

2021-02-20T23:35:28Z INFO update - store beacon: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1608421791, hash 37129befd588c96eae7c0cf64df63c42015bcd9ebcb9ec112274804d951eef63, prev_beacon_hash e56d09e3e65a87c578387bcd3aa9319ad97b2d48e27d27b9e9a0dfd5dc3d28ed, status = 3.
2021-02-20T23:35:28Z INFO update - store beacon: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1608421778, hash 3bbf05b36cc01851a0f53ab7d2c14c079bbc1e24133d2ece6f2c296e62a9a286, prev_beacon_hash 37129befd588c96eae7c0cf64df63c42015bcd9ebcb9ec112274804d951eef63, status = 3.

The output of beaconreport:

{
"cpid": "d9a2f25eb0722243bf2aecc16a018cfd",
"address": "my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR",
"timestamp": 1608421778,
"hash": "3bbf05b36cc01851a0f53ab7d2c14c079bbc1e24133d2ece6f2c296e62a9a286",
"prev_beacon_hash": "37129befd588c96eae7c0cf64df63c42015bcd9ebcb9ec112274804d951eef63",
"status": 3
},

The replay log on restart of wallet after the beacon storage is initialized:

2021-02-20T23:18:17Z INFO: Initialize: m_historical insert: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1594765707, hash 5b0a4482404c7cb52ae6acdbd0141bb622c7c5cbae98e8fbbb84a6a46c60b105, prev_beacon_hash 0000000000000000000000000000000000000000000000000000000000000000, beacon status = 1.
2021-02-20T23:18:17Z INFO: Initialize: m_pending insert: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1594765707, hash 5b0a4482404c7cb52ae6acdbd0141bb622c7c5cbae98e8fbbb84a6a46c60b105, prev_beacon_hash 0000000000000000000000000000000000000000000000000000000000000000, beacon status = 1 - (1) PENDING.
2021-02-20T23:18:17Z INFO: Initialize: m_historical insert: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1594765707, hash e56d09e3e65a87c578387bcd3aa9319ad97b2d48e27d27b9e9a0dfd5dc3d28ed, prev_beacon_hash 5b0a4482404c7cb52ae6acdbd0141bb622c7c5cbae98e8fbbb84a6a46c60b105, beacon status = 2.
2021-02-20T23:18:17Z INFO: Initialize: m_beacons insert: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1594765707, hash e56d09e3e65a87c578387bcd3aa9319ad97b2d48e27d27b9e9a0dfd5dc3d28ed, prev_beacon_hash 5b0a4482404c7cb52ae6acdbd0141bb622c7c5cbae98e8fbbb84a6a46c60b105, beacon status = 2 - (2) ACTIVE or (3) RENEWAL.
2021-02-20T23:18:17Z INFO: Initialize: m_pending delete after active insert: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1594765707, hash 5b0a4482404c7cb52ae6acdbd0141bb622c7c5cbae98e8fbbb84a6a46c60b105, prev_beacon_hash 0000000000000000000000000000000000000000000000000000000000000000, beacon status = 1 - (2).
2021-02-20T23:18:17Z INFO: Initialize: m_historical insert: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1608421778, hash 3bbf05b36cc01851a0f53ab7d2c14c079bbc1e24133d2ece6f2c296e62a9a286, prev_beacon_hash 37129befd588c96eae7c0cf64df63c42015bcd9ebcb9ec112274804d951eef63, beacon status = 3.
2021-02-20T23:18:17Z INFO: Initialize: m_beacons insert: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1608421778, hash 3bbf05b36cc01851a0f53ab7d2c14c079bbc1e24133d2ece6f2c296e62a9a286, prev_beacon_hash 37129befd588c96eae7c0cf64df63c42015bcd9ebcb9ec112274804d951eef63, beacon status = 3 - (2) ACTIVE or (3) RENEWAL.
2021-02-20T23:18:17Z INFO: Initialize: m_historical insert: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1608421791, hash 37129befd588c96eae7c0cf64df63c42015bcd9ebcb9ec112274804d951eef63, prev_beacon_hash e56d09e3e65a87c578387bcd3aa9319ad97b2d48e27d27b9e9a0dfd5dc3d28ed, beacon status = 3.
2021-02-20T23:18:17Z INFO: Initialize: m_beacons insert: cpid d9a2f25eb0722243bf2aecc16a018cfd, address my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR, timestamp 1608421791, hash 37129befd588c96eae7c0cf64df63c42015bcd9ebcb9ec112274804d951eef63, prev_beacon_hash e56d09e3e65a87c578387bcd3aa9319ad97b2d48e27d27b9e9a0dfd5dc3d28ed, beacon status = 3 - (2) ACTIVE or (3) RENEWAL.


The output of beaconreport:

{
"cpid": "d9a2f25eb0722243bf2aecc16a018cfd",
"address": "my9RrySJiDCuRiMkvHTpppf7Pav19fuLGR",
"timestamp": 1608421791,
"hash": "37129befd588c96eae7c0cf64df63c42015bcd9ebcb9ec112274804d951eef63",
"prev_beacon_hash": "e56d09e3e65a87c578387bcd3aa9319ad97b2d48e27d27b9e9a0dfd5dc3d28ed",
"status": 3
},

Notice the earlier time record is chosen on the initial load, and the later time record is chosen on the reload from beacon storage.

It is a serious question quite frankly as to what is correct here.

**Comment by jamescowens** [comment]
I solved it and fixed a number of other subtle bugs identified during the straightening out of the unit tests. I now use a record number that is recorded in leveldb that encodes the correct underlying order.

**Comment by jamescowens** [comment]
I marked this ready for review. We just need to sort out the path to the binary data files for the beacon contract replay unit tests for the CI builds. I was thinking about squashing the commits a bit more, but I think it is instructive to see them the way they are for now.

**Comment by jamescowens** [comment]
Note that the unit tests do not cover deep reorgs, but I have tested that by reorgs over 1000 blocks and then reorg back and things work nicely.

**Review by div72 — APPROVED** [review]
utACK

**Comment by jamescowens** [comment]
Ok. I put two additional template functions in txdb-leveldb.h which support maps with a key foreign to the key used to store items in leveldb. This eliminates one of the temporary maps used in the BeaconRegistry::BeaconDB::Initialize function.

I am going to do sync from zeroes on both testnet and mainnet with this PR and then some other tests and then merge.

**Comment by jamescowens** [comment]
Both syncs from zero were successful. Merging

**Pull request merged**
