### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by Tahvok**
You would need to enable travis to run on this repo first for this to work.

A working example at my fork:
https://github.com/Tahvok/Gridcoin-Research/pull/3

And the successfull build:
https://travis-ci.org/Tahvok/Gridcoin-Research/builds/155970019

It's possible to add some more checks to this.

### CODE REVIEW

**Comment by denravonska** [comment]
We need to cherry pick this to the staging branch too, right?

**Comment by Tahvok** [comment]
Yes, but dev branch should be always above the master branch. Isn't it the case?

**Pull request merged**
