### PR TITLE
Remove resize constraints and more

### PR DESCRIPTION
**Pull request by skcin**
You should be able to resize the gui to a smaler size and the unused progress bar is removed.
Please test if the icons on the green bar are centered now.

### CODE REVIEW

**Comment by denravonska** [comment]
Green bar has its icons centered now but they're cut off. 
screenshot_2017-06-17_07-27-46

**Comment by denravonska** [comment]
I merged this one as-is. The icon cut off feels like a small fix.

**Comment by denravonska** [comment]
There's a small issue with the window automatically resizing to fit the status text:
gridcoin wallet testnet _004
gridcoin wallet testnet _005

**Comment by tomasbrod** [comment]
I can remove the "Added Reward ...;" from the status text. Would it help?

**Comment by denravonska** [comment]
@tomasbrod Partly but the window shouldn't resize to fit. I think it's better to just cut off then.

**Pull request merged**
