### PR TITLE
ssl in help channel, on freenode

### PR DESCRIPTION
**Pull request by Erkan-Yilmaz**

### CODE REVIEW

**Comment by Peppernrino** [comment]
hehe. i actually removed SSL from help channel due to some complaints.

SSL remains in the main channel, and others. any unregistered/non-SSL users will be forwarded to #gridcoin-help through +F mode. :)

**Comment by Quezacoatl1** [comment]
Is the SSL requerement really necessary? My IRC client does not support SSL so I cannt enter. Thats another barrier for newbies becoming a member of the community

**Comment by denravonska** [comment]
It's also interfering with the slack<->irc bot :(

**Comment by grctest** [comment]
How come the slack bot cannot work with SSL? @Quezacoatl1 perhaps that's an indicator that you should switch IRC client?

**Comment by denravonska** [comment]
@grctest I think it does but not out of the box. See last comment: https://github.com/ekmartin/slack-irc/issues/38#issuecomment-257107876
I'm still not sure why we require SSL in an open channel. For closed discussions, fine, but this one is for anyone to read anyway.

**Comment by Peppernrino** [comment]
in the interest of preparedness for the future (god knows if people will be able to change your text in transit soon), and also to show people that we hold ourselves to the same standard of security that we are asking of people. while SSL isn't required by projects, we have been going around telling people to SSL their sites. it's not that hard to do... pretty frivolous complaints for the most part. and in my opinion, as well as some other ops, it's a good primer to show people that this isn't something you can try in a couple of seconds... it takes a bit of work. ;)

**Comment by grctest** [comment]
I've removed the forced SSL on the main chat due to the bots being negatively affected. Users can use SSL if they want, we're just not enforcing it. It's up to end users if they want to be secure or not. IRC should be considered entirely public, so interception of SSL traffic is pointless when you can just join and monitor the plain text chat.

**Comment by Peppernrino** [comment]
also, it should be noted that #elitebnc on Freenode gives out free bnc's that automatically connect through SSL no matter what client you are on. :)

**Pull request merged**
