### PR TITLE
net: Add and document network messages in protocol.h (backport)

### PR DESCRIPTION
**Pull request by Pythonix**
This is a backport of https://github.com/bitcoin/bitcoin/pull/7181. I have only included the messages I found in the source code and also added the Gridcoin specific messages.

### CODE REVIEW

**Comment by div72** [comment]
"aries" is not Gridcoin-specific, it's just version renamed for god knows why. Same with "gridaddr" -> "addr".

**Comment by Pythonix** [comment]
@div72 Well, the string does not appear like that in Bitcoin. Should I move the message to the Bitcoin ones?

**Comment by div72** [comment]
Give me a minute, I'll check any other duplicates. I have a feeling that we do not have anything GRC-specific other than the scraper one.

**Comment by div72** [comment]
```
aries <-> version
griaddr <-> addr
encrypt <-> block
```
Could you also include the original bitcoin ones and add them to the if conditions in ProcessMessage with ||? We can do away with the weird aliases after the mandatory if @jamescowens agrees.

**Comment by jamescowens** [comment]
I agree. I have no idea why we would want to customize these...

**Comment by Pythonix** [comment]
@div72 @jamescowens Done as you suggested =)

**Comment by div72** [comment]
@Pythonix Could you also update the usage in src/net.cpp:495?

**Comment by Pythonix** [comment]
@div72 Good catch, the line break made it escape my grep.

**Review by div72 — APPROVED** [review]
ACK 9b291120493f3a801275aa023131d8828705d817.

**Pull request merged**
