### PR TITLE
Change appcache to use unordered_map

### PR DESCRIPTION
**Pull request by denravonska**
This provides a small performance increase.

### CODE REVIEW

**Review by iFoggz — APPROVED** [review]
Id like to see more use of unordered* where we can

**Comment by tomasbrod** [comment]
RPC output of listdata and similar should be ordered. I can't check right now, but if this adds regression, create a issue for it, please.

**Review by tomasbrod — APPROVED** [review]

**Comment by denravonska** [comment]
You are right, it will. I'll see if there's a clean way to sort them on output.

**Comment by tomasbrod** [comment]
I thought about copy-constructiong a ordered map on demand in the rpc handler.

**Comment by denravonska** [comment]
That was exactly what I was going to do :D

**Comment by denravonska** [comment]
@jamescowens It is double the stack usage for a section when it's been converted.

**Review by iFoggz — APPROVED** [review]
I like this, only sort when its needed for rpc. makes sense even thou a double stack occurs for a short term period during this. So that insignificant imo for clarity.

**Comment by denravonska** [comment]
Replaced by #1317.

**Pull request closed without merging**
