### PR TITLE
D3uxx/docs

### PR DESCRIPTION
**Pull request by D3uxx**
Exelente

### CODE REVIEW

**Comment by jamescowens** [comment]
What is this PR?

**Comment by jamescowens** [comment]
It is done against the wrong branch and is not based properly.

**Comment by RoboticMind** [comment]
@jamescowens this user's GItHub history is really strange. Look at some of the weird PRs and Issues they've opened. I wonder if there's some hacktoberfest type of thing going on again....

**Comment by denravonska** [comment]
Pure nonsense. Just close it.

**Pull request closed without merging**
