### PR TITLE
refactor, misc: remove CBitcoin(Address|Secret)

### PR DESCRIPTION
**Pull request by div72**
<details>
<summary>Testing checklist:</summary>

- [x] Sync from zero.
- [x] Alerting.
- [x] Verifying/Signing messages.
- [x] Sending/Receiving TXs.
- [x] RPC commands.
- - [x] addmultisigaddress
- - [x] beaconreport
- - [x] dumpwallet
- - [x] importprivkey
- - [x] importwallet
- - [x] sendalert/sendalert2
- - [x] signmessage
- - [x] signrawtransaction
- - [x] verifymessage

(Testing checklist copied from the libsecp256k1 port PR.)
</details>

### CODE REVIEW

**Comment by jamescowens** [comment]
Taking the plunge on this one, eh? :)

**Comment by div72** [comment]
Just needs key_io tests and testing now.

**Comment by div72** [comment]
@jamescowens This is ready for a review as well.

**Comment by jamescowens** [comment]
Tested alerting on testnet (sendalert2).
Tested multisig (see attached document)
[multisig testing documentation.txt](https://github.com/user-attachments/files/17270810/multisig.testing.documentation.txt)

**Review by jamescowens — APPROVED** [review]
ACK cff5c14cc3

**Pull request merged**
