### PR TITLE
Update outdated checkpoints

### PR DESCRIPTION
**Pull request by barton2526**
Previous last checkpoint was block 1,050,000, which was nearly 2 years old.

I added checkpoints every 100k blocks (representing a little over 100 days each) following the rules outlined in this file.  Last checkpoint added is block 1.7 million, dated September 2nd 2019 as per @jamescowens advice

### CODE REVIEW

**Comment by barton2526** [comment]
Maintainer: please tag as Fern milestone

**Comment by jamescowens** [comment]
Here is a screenshot of this running on my Windows testnet node...
image
Notice there is an IPv6 address there!

**Review by iFoggz — APPROVED** [review]
tACK; verified blockhashes->block number. good work.

**Comment by barton2526** [comment]
This closes #1441

**Pull request merged**
