### PR TITLE
Revert "Space-saving lossless compression"

### PR DESCRIPTION
**Pull request by denravonska**
Reverts gridcoin/Gridcoin-Research#227

This was supposed to go into development.

### CODE REVIEW

**Comment by tomasbrod** [comment]
I hope you did not revert the merge, becouse there is no way to revert a revertation of marge.

**Comment by denravonska** [comment]
I reverted via the Github which seems to do a standard git revert. It'll be applied to master once development is merged (since it's in there), right?

**Comment by tomasbrod** [comment]
http://stackoverflow.com/a/7101376

**Comment by denravonska** [comment]
Interesting. So I guess there is no proper way of undoing a merge or moving a merge to a different branch? You could delete the offending commits but that opens up another can of worms.

Worst come to worst, in this particular case the commit can be redone if it won't merge from development. I'll try to pay more attention to where pull requests are pointing next time and if we change the default branch to be development this probably won't show up again.

**Pull request merged**
