### PR TITLE
Updated translation files.

### PR DESCRIPTION
**Pull request by Peppernrino**
Fixed and expanded English, Russian, Afrikaans, and Espanol.
Made links SSL. Stayed away from files with characters i couldn't render in .txt. :P

### CODE REVIEW

**Comment by Peppernrino** [comment]
Closing until huppdiwupp's stylesheet fix.

**Comment by philipswift** [comment]
Afrikaans is good to see.

**Comment by denravonska** [comment]
@philipswift Would you be up for translations?

**Comment by philipswift** [comment]
Yes, anything to help. I get my laptop back from Poland today after its repair. As long she fires up I'm there. We should manage expectations at some point but obviously I'll do my best.

**Comment by denravonska** [comment]
@philipswift Awesome, just make sure you translate the one from development since it's been updated recently.

**Comment by philipswift** [comment]
Its back and mining, seems stable so Ill start soon. Please give me some pointers and what expectations are.

**Comment by denravonska** [comment]
@philipswift Either fork the repo or download the .ts file [from here](https://github.com/gridcoin/Gridcoin-Research/tree/development/src/qt/locale). Translate the file using Qt Linguist and either mail it to me or submit a PR.

Qt Linguist is available in the Qt development package but you can try [this alternate installer](https://github.com/lelegard/qtlinguist-installers) which just installs the translation software and skips the rest.

**Comment by philipswift** [comment]
I downloaded it last night. Ill get on with it.

**Pull request closed without merging**
