### PR TITLE
Block Version 9 and Constant interest.

### PR DESCRIPTION
**Pull request by tomasbrod**
* Foundation for block version 9.
  * block trigger height arbitrary
* Constant interest of 12 grc per block.

### CODE REVIEW

**Comment by Quezacoatl1** [comment]
Can we have some other number than 12? We want to reduce the complexity and 12 seems random.

I propose 20 (bigger than 1.5% interest so we keep the promise of 1.5% interest rate if investors stake).

**Comment by ghost** [comment]
I think it works out at 15 if you remove the foundation funds from the total supply.

**Comment by Quezacoatl1** [comment]
15 is much better than 12, but a "round" number would be more appropiate IMO. Sadly 10 (would be best I think) is too low.

**Comment by tomasbrod** [comment]
I am not happy with discussion of the amount here. Go argue in the mega-thread #106. But average interest per last 200 000 blocks was 11.567 GRC per block. That is why I choose 12. It can be literally any number.

**Comment by tomasbrod** [comment]
Candidate for https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/43 ?

**Pull request closed without merging**
