### PR TITLE
build: Patch libzip to fix mingw compile regression for mingw 9.2+

### LINKED ISSUE #1929: Depends build fails using mingw-w64 version 8.0.0-1 (GCC-10)
This is a heads up for future compatibility for if and when mingw-w64 gets updated. Shouldn't currently affect the official builds that are still on Bionic but needs to be kept in mind in case of future updates or for those that build for themselves.

When cross-compiling depends using mingw-w64 version 8.0.0-1 (GCC-10), build fails during the build of libzip with the following error:

`libtool: link: x86_64-w64-mingw32-gcc -pipe -O2 -I/home/g/GRC-Build/Gridcoin-Research/depends/x86_64-w64-mingw32 include -fPIC -I/home/g/GRC-Build/Gridcoin-Research/depends/x86_64-w64-mingw32/include -I/home/g/GRC-Build/Gridcoin-Research/depends/x86_64-w64-mingw32/include -o ziptool.exe source_hole.o ziptool.o  -L/home/g/GRC-Build/Gridcoin-Research/depends/x86_64-w64-mingw32/lib ../lib/.libs/libzip.a -lbz2 -lz`
`/usr/bin/x86_64-w64-mingw32-ld: ziptool.o:ziptool.c:(.text.startup+0x6f1): undefined reference to `__imp__snprintf.constprop.0'`

Downgrading back to mingw-w64 version 6.0.0-3 (GCC-8) from Debian Buster allows a successful build.

I also suspect version 7.0.0 (GCC-9) from Ubuntu Focul and Ubuntu Groovy are ok but have been unable to test them. I wouldn't be suprised to see these be updated at some point though as GCC-10 is already on their package managers and is already the default on Groovy.

Unfortunately both versions of mingw-w64 cant co-exist on the same system like GCC and G++ so the following packages have to be downgraded and held at the earlier versions to work around this issue (in my case to those available on Debain Buster, version numbers will vary on Ubuntu).

`g++-mingw-w64-i686=8.3.0-6+21.3~deb10u1`
`g++-mingw-w64-x86-64=8.3.0-6+21.3~deb10u1`
`g++-mingw-w64=8.3.0-6+21.3~deb10u1`
`gcc-mingw-w64-base=8.3.0-6+21.3~deb10u1`
`gcc-mingw-w64-i686=8.3.0-6+21.3~deb10u1`
`gcc-mingw-w64-x86-64=8.3.0-6+21.3~deb10u1`
`gcc-mingw-w64=8.3.0-6+21.3~deb10u1`
`mingw-w64-common=6.0.0-3`
`mingw-w64-i686-dev=6.0.0-3`
`mingw-w64-x86-64-dev=6.0.0-3`
`mingw-w64=6.0.0-3`

Build System:
WSL Debian Testing

`~$ lsb_release -da`
`Distributor ID: Debian`
`Description: Debian GNU/Linux bullseye/sid`
`Release: testing`
`Codename: bullseye`

Not-working
`~$ x86_64-w64-mingw32-gcc --version`
`x86_64-w64-mingw32-gcc (GCC) 10-posix 20200525`

Working
`~$ x86_64-w64-mingw32-gcc --version`
`x86_64-w64-mingw32-gcc (GCC) 8.3-posix 20190406`

### PR DESCRIPTION
**Pull request by jamescowens**
Closes #1929.

### CODE REVIEW

**Review by cyrossignol — APPROVED** [review]
We will need to remember that this likely breaks compilation with MSVC whenever we get that working.

**Comment by jamescowens** [comment]
Hopefully by that time the regression with GCC will be fixed and we can revert it. Are we ever going to use MSVC? I think not...

**Comment by cyrossignol** [comment]
I spent a _lot_ of time with a would-be contributor who was familiar with MSVC/Visual Studio. The need to understand and install a Linux-like environment to build the software can be a big enough hurdle to discourage folks. I don't think it's a priority to support MSVC at this stage, but it is a desirable goal.

**Comment by jamescowens** [comment]
Is it even possible to compile the core with MSVC?

**Comment by cyrossignol** [comment]
In theory, yes. I'm sure we have some minor compatibility issues to address. Bitcoin has a set of project/solution configuration files for VS that we can adopt eventually.

**Pull request merged**
