### PR TITLE
init: fix daemon forking

### PR DESCRIPTION
**Pull request by div72**
Currently, the parent calls the shutdown routine after forking; removing the child's PID file in the process. This PR fixes that and introduces some refactoring coupled with the addition of the `-daemonwait` functionality.

### CODE REVIEW

**Comment by iFoggz** [comment]
Don't know much about the daemon process from personal experience but Concept ACK

**Review by jamescowens — APPROVED** [review]
Concept ACK. How did you test this?

**Review by jamescowens — CHANGES_REQUESTED** [review]
Did some testing on this. gridcoinresearch GUI executable works fine. gridcoinresearchd daemon also works well in rpc passthrough mode, and also will start up on the command line in both non daemon and -daemon modes. The included systemd service doesn't seem to work and I have not had time to dig in and figure out why, so we need to debug that.

**Comment by jamescowens** [comment]
It was a pathing issue on my testing vm. Using an override file for the service to change the ExecStart path to the correct one for testing did the trick. The service file works correctly.

**Review by jamescowens — APPROVED** [review]
tACK

**Pull request merged**
