### PR TITLE
Attempt to fix ClearCache.

### PR DESCRIPTION
**Pull request by tomasbrod**
#576

### CODE REVIEW

**Comment by tomasbrod** [comment]
Merging this in too fast, can create forks.

**Comment by denravonska** [comment]
Do we hold on to this until a mandatory?

**Comment by denravonska** [comment]
Now I'm confused.

> Merging this in too fast, can create forks.

Hence my question. Do we or don't we schedule this for a mandatory?

**Comment by tomasbrod** [comment]
I don't know. It looks like mandatory change (superblocks being rejected).

**Pull request merged**
