### PR TITLE
qt: Add option to choose not to start the wallet minimized

### LINKED ISSUE #1782: Option to start the wallet unminimised?
Maybe there could be an option to not hide the wallet on system startup.

### PR DESCRIPTION
**Pull request by jamescowens**
This PR implements a conditional "Start minimized" checkbox that appears if the "Start Gridcoin on system login" is checked. The default for this new checkbox is checked (which is the current default behavior), but may be unchecked. This allows the user to specify whether a wallet started automatically on login starts minimized or normally. This is a rebase and addition to #1786.
image
image
image

### CODE REVIEW

**Comment by jamescowens** [comment]
@nathanielcwm I squashed your commits into one and then squashed my two into another one, so you could see the changes easily.

**Comment by jamescowens** [comment]
I haven't decided on the milestone yet for this, but I think we can get it into Fern.

**Comment by div72** [comment]
@jamescowens While not directly related to this PR, the shortcut fails on linux because the datadir parameter is escaped twice.

ex.
```
[Desktop Entry]
Type=Application
Name=Gridcoin-testnet
Exec=<home_directory>/dev/branch/jamescowens/build/src/qt/gridcoinresearch -datadir='"<home_directory>/.GridcoinResearch"' -testnet -min
Terminal=false
Hidden=false
```

**Comment by jamescowens** [comment]
Ok. That should fix it. I will test it on one of my Ubuntu vms and also on Windows.

**Comment by jamescowens** [comment]
The only thing I don't like about this solution, is that if you change the state of both the Gridcoin auto start and minimize on startup flags, it will write the file twice, because the model update (setData) is fired for each change (when the apply button is pressed). It isn't worth fooling with any more to fix that...

**Comment by jamescowens** [comment]
@div72, I should probably escape the exe path, because someone could use a exe filename with spaces in it....

**Comment by jamescowens** [comment]
Ok. That should do it. Testing. Works on Linux Kubuntu...

**Comment by div72** [comment]
ACK 61dd659

**Review by cyrossignol — APPROVED** [review]
Looks good.

**Pull request merged**
