### PR TITLE
Vb fixes

### PR DESCRIPTION
**Pull request by denravonska**
State: Needs testing.

This should fix the concurrent syncs (#717) and at least one of the silent shutdowns shown in #712.

### CODE REVIEW

**Review by iFoggz — APPROVED** [review]
Gonna have to get windows going again and test this out. looks promising. get as many of these problems delt with as possible.

**Comment by denravonska** [comment]
@Foggyx420 Please do if you can. My Windows box is SO slow so testing is a real chore.

**Comment by iFoggz** [comment]
on my agenda today

**Comment by iFoggz** [comment]
confirmed this works. tested on windows.

**Pull request merged**
