### PR TITLE
Optimize getfilecontents() to reduce chance of race for client_state.xml

### PR DESCRIPTION
**Pull request by cyrossignol**
The `getfilecontents()` function loads a file into memory, and the previous implementation read the file line-by-line into a buffer. We use this function to load BOINC's client_state.xml file. A user on Slack reported that the wallet took 7 seconds to read this file, and @jamescowens confirmed that it took 10 seconds with his version. 

As also confirmed on Slack, BOINC aborts on Windows when trying to update client_state.xml if the wallet holds the file open during start-up. This change improves the performance of the function to greatly reduce the chance of a race between Gridcoin and BOINC.

### CODE REVIEW

**Review by jamescowens — APPROVED** [review]
Tested it out. Even more compact than my own solution. Reduced the client_state.xml load time on my windows testnet wallet to < 0.5 seconds from about 10 seconds.

**Comment by jamescowens** [comment]
I can do a special build of 4.0.2.0 release with just this change to give to KarVi71 and see if it fixes his problem. If so, we can hold off on doing more substantial plumbing work, such as implementing RPC communication between the BOINC client and the wallet.

**Review by denravonska — APPROVED** [review]

**Comment by tomasbrod** [comment]
Can the file be opened in such way, that does not block boinc from writing to it?

**Comment by jamescowens** [comment]
The file is already being opened in a non-blocking way. The issue is that BOINC tries to rename the file. Windows does not allow a file to be renamed if another file handle already exists, even if in non-exclusive mode.

**Comment by tomasbrod** [comment]
That is unfortunate and breaks the copy-and-replace pattern.

**Comment by jamescowens** [comment]
It looks like minimizing the amount of time we have the file open has practically solved the issue, but I agree it is an ugly issue underneath....

**Comment by cyrossignol** [comment]
Fortunately, BOINC does retry the write/rename operations on client_state.xml, so as long as we read the file quickly, the wallet probably won't ever kill BOINC anymore.

I studied this issue for a bit because I was completely blown away by the evidence which showed that it took such a huge amount of time to read a file that's only a few MB large. I wanted to understand why this was happening so that I won't make the same mistake later. At first, I thought that the way that the function opened and closed the file twice introduced some delay because of something in the OS, but removing that nonsense didn't change the result.

The culprit appears to be in the way that the old function appended each line to the buffer:

```c++ 
while (getline(myfile, line))
{
    //       vvvvvv--- copy
    buffer = buffer + line + "\n";
    //     ^--- swap
}
```

Namely, the function really didn't append anything to the existing buffer. Instead, it copied the whole buffer and replaced it for _every_ line. For larger client_state.xml files, we were churning through over a GB of data just to read the file.

The issue disappeared when I changed that line of code to:

```c++
buffer += line + "\n";
```

...for which `std::string` overloads `operator+=()` to append the input to the internal buffer. If the function was written like this to begin with, we may never have seen the race condition with BOINC.

**Comment by jamescowens** [comment]
Yep. And the irony is that we didn’t need to do any of that at all!

**Pull request merged**
