### PR TITLE
Upgrader

### PR DESCRIPTION
**Pull request by Lederstrumpf**
Upgrader working both on Linux and Windows - OSX not been tested yet.

Can upgrade qt-client, daemon and bootstrap new users with blockchain download.
Restarts qt/daemon after upgrade.
Creates backups of previous clients/chains in date-specific folders under datadir/backup.
Can restore from backup once function to sort date-specific folders is implemented.

As of yet, upgrading functionality is a stub insofar as that the respective binaries are not available on gridcoin.us yet. 

New dependencies: curl, libzip (both cross-platform)
New Config Flag: programdir (specifies qt-client/daemon directory - if not specified, will search in running directory for said targets)

Current TODO List:
Implement restore functionality
Add RPC command for upgrade (ADDED 11/01/2015)
Add upgrader upgrading command to daemon/qt-client
Work on upgradedialog appearance/layout in qt-client
More extensive commenting on code functionality

### CODE REVIEW

**Comment by theMarix** [comment]
Trying to build this branch I get the following error on openSUSE 12.3:

```
make: *** No rule to make target `build/upgradedialog.moc', needed by `build/upgradedialog.o'.  Stop.
```

Current master builds fine for me, so I assume the file got lost from the list of files to be mocked somewhere during a merge.

**Comment by theMarix** [comment]
Short note from the packaging point of view: It would be great if we could disable (and hide) the binary upgrade functionality for binaries shipped via packages. In our case the binary is usally in a location where the user can/should not modify it and it must be updated via the package manager.

The option to download the blocks should still be available, though. It is a very useful feature that only requires user priviledges.

**Comment by caraka** [comment]
I agree with Marix about hiding the upgrade feature. In a packaging environment it will cause confusion if it does more than a system notification telling the user to use their package manager. This could be an internal flag that we set with a patch at compile time.

**Comment by theMarix** [comment]
I would personally prefer a configuration flag analogous to the USE_PNP flag instead of a patch.

**Comment by caraka** [comment]
successfully compiled gridcoinupgrader when I searched properly for 'upgrader' instead of 'gridcoinupgrader' and found the makefile.   ;-)

Almost a successful download blocks session. The upgrader moved so fast to copy the snapshot and restart the qt that the qt hadn't even fully exited, causing a failure to launch and the usual error that it could not secure the port and is there another instance running, etc. However, the snapshot was properly installed and manually restarting moved to the snapshot block. 

All good with perhaps an added delay or a test to ensure the previous instance is truly dead before restarting gridcoinresearch.

I attempted the actual upgrade function, which crashed. This was the only error apport reported:
gridcoinupgrader crashed with SIGABRT in__gnu_cxx::__verbose_terminate_handler()

However, the upgrade folder had a 404 html document where I presume something else was meant to download for a full upgrade. The upgrade folder had been cleaned up properly after the download blocks session.

**Comment by theMarix** [comment]
Compilation now works fine on openSUSE. I am still somewhat confused by the feature, though. If I run Download Blocks I get an Upgrade Window which downloads blocks. However, in the end it gives me an update button, and that button seems to only shut down the wallet.

**Comment by theMarix** [comment]
The block download in the headless also works well. However, also in the headless the restart only seems to terminate the current wallet, but not restart it.

**Comment by caraka** [comment]
Marix, I got the same results until I set the programdir=/usr/bin in my conf file. No matter what it's looking for the binaries in ~/ unless I manually set the new conf flag. Try setting that to the correct path to your binaries. You are probably not even getting to the gridcoinupdater binary when it's called. 

I agree having the button say 'upgrade' is confusing when downloading blocks. (It's the same gui set up for the actual upgrade feature, which seems intuitively correct to me there, but not here.)

**Comment by theMarix** [comment]
Thanks, with the programdir option I can see the upgrader unpacking the downloaded blocks. I have a feeling it is not moving up to the blocks, though. But this might be because of the mandatories which are not yet in the version.

It would be nice if we explicitly set the default programdir during compile.

Regarding the upgrade button I would suggest to simply rename it to “restart”. This works in either case.

**Comment by caraka** [comment]
I wasn't able to sync either, but we are working 4 versions behind so that's no surprise.

As for the actual upgrade feature, is it looking to download a tar file or what? I remember reading somewhere Lederstrumpf saying that the target doesn't exist yet, so one step at a time.

**Comment by Lederstrumpf** [comment]
Apologies for not having responded to this for some time.
Matthias, thanks for initially pointing out the compile error a few days back  - was a quick fix that allowed testing to resume. Are you on 12.3 for mission critical reliability? Big fan of 13.2/Tumbleweed.

The suggestion to disable the upgrade functionality for package manager installations is very reasonable. Compiler flag a la "USE_UPGRADER" or "PACKAGE_MANAGED" would be the most painless way to go about it. I'll get around to this once I've figured out how to compile libcurl on Windows again, which is currently of greater concern.

**Comment by Lederstrumpf** [comment]
Regarding the upgrader not finding the program:
As of yet, the stand-alone upgrader only searches for the client/daemon in the directory it was called from, which does not necessarily correlate with the directory it is saved in, explaining both of your troubles. Indeed, that is why the programdir flag was added to the conf file. 
I will add some OS-specific default paths to search in to the GetProgramDir() function responsible for this, but I first want to verify that the rudimentary functionality is intact, so simply keeping said flag in your config will be the best way to go about it for now, I believe. This could also be an option at compile time (with the config flag still trumping it in hierarchy), but I'm not yet decided as to whether this will add more complications than benefits.

**Comment by Lederstrumpf** [comment]
Regarding the GUI: The entire layout is a temporary placeholder as of yet - my preference is in fact to have it slide out as an extension to the main window when called, but I haven't figured out how to do this in Qt yet, or if it even would allow this ^^.
Button will be renamed as to avoid confusion when bootstrapping the blockchain.

**Comment by Lederstrumpf** [comment]
@caraka Indeed, as noted in the pull request, the upgrade feature is currently a stub as none of the distro-specific clients are hosted on the website yet. If you want to test it with a client/daemon file hosted on one of your domains, you can change the url in the geturl() function contained in upgrader.cpp. For now, this is not a tarball, but an uncompressed file, but this will eventually depend on what Rob deems to be the most advantageous file hosting layout for the client upgrades.

I'm a bit surprised that the upgrader tried to launch qt before it had exited. 
Before exiting, the client/daemon passes its PID to the upgrader. The upgrader then checks if the process assigned to said PID is still running and only commences once this check is negative.

Would you mind launching the Qt client from a terminal, downloading blocks, clicking 'Upgrade' to restart the client and checking the terminal output for "Waiting for client to exit..." followed by "Client has exited"?

**Comment by caraka** [comment]
Waiting for client to exit...
master@master-1404:~$ Client has exited
~snip~
Full extraction of snapshot here
~snip~
Copied files successfully
Parent: 2141
QObject::connect: Cannot connect (null)::triggered() to QApplication::aboutQt()
QWidget::insertAction: Attempt to insert null action
QGradient::setColorAt: Color position must be specified in the range 0 to 1
(Normal message when starting from terminal)

External dialog box:
Unable to bind to 0.0.0.0:32749 on this computer. GridCoin is probably already running.

(And it is, the appmenu icon with dropdown menu from the last? session is still present and functioning, although when I show the client, It is all zeroed out like a virgin client - like one that just had its download blocks completed.

Not sure exactly what is happening, but I do know that the qt client takes some time to close down. I know in the bitcoin development there was debate because the client specifically hides the appmenu icon at shutdown as it lingers so long and people thought there was a problem. Gridcoin inherited that hiding function, which is ubuntu specific.

All that said, what brought me to my computer was a rash of launchpad compile failures. Rob has been busy. Not only did he push a 3.3.8.8 Leisure upgrade that includes most of your work, he subsequently pushed out to 3.3.8.8-4. I have it building now, which means I'll be testing on my live node in about 30 minutes..

Gridcoin Research 3.3.8.8/21.1 - Exchange Release Candidate
Leisure Upgrade
- Added Green POR mined indicator for POR mined blocks
- Merged in Leders downloadblocks, downloadstate, downloadcancel, and
  upgrade into RPC and the UI changes

**Comment by sEpuLchEr** [comment]
3.3.8.8 compile error on ubuntu. I tried a few hours earlier when Rob push to Git

/usr/bin/ld: cannot find -lzip
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
make: **\* [gridcoinresearchd] Error 1

**Comment by caraka** [comment]
You are right sEp. I was too eager and hit the button, not having pushed the changes to debian/control and rules to incorporate the gridcoinupgrader. it's working on my machine already, why would I need to do anything?  :P

It's compiling now. I hope.

**Comment by sEpuLchEr** [comment]
Problem is, if my headless fail to build, so will the exchanges. They are not going to edit or install any dependencies that they are not already running.

**Comment by caraka** [comment]
Ah, I think I see what you are saying sEp. It failed to build on your system, not just launchpad. Well, launchpad was my fault. 

If you look at the wiki compiling for linux, you will see that I added two more dependencies to the list - curl and libzip2 in particular. Surely the exchanges will follow directions? After all, they install unique programmes for others - such as bash-completion for bitcoin, etc. All because they are listed in the base documentation as dependencies. Both of these packages are ubiquitous across all *nix distributions, that is why Lederstrumpf chose them. There will be no unique or extra compilation steps for the exchanges.

As for you, 
sudo apt-get install libcurl4-openssl-dev libzip-dev
will sort your compilation issues.

**Comment by sEpuLchEr** [comment]
That was what Rob is worried about. Which was why he asked it to be tested. If it can't compile without the exchanges adding anything extra to their system, then there is risk they will not do it.

**Comment by caraka** [comment]
Actually, now the build is blowing up because of something new Rob has or has not completely included, as opposed to my initial packaging error. A brief collection:

/build/buildd/gridcoinresearch-3.3.8.8/src/rpcrawtransaction.cpp:164: undefined reference to `upgrader'
/build/buildd/gridcoinresearch-3.3.8.8/src/rpcrawtransaction.cpp:164: undefined reference to`Upgrader::getFileDone()'
/build/buildd/gridcoinresearch-3.3.8.8/src/rpcrawtransaction.cpp:164: undefined reference to `upgrader'
/build/buildd/gridcoinresearch-3.3.8.8/src/rpcrawtransaction.cpp:164: undefined reference to`Upgrader::getFilePerc(long)'
/build/buildd/gridcoinresearch-3.3.8.8/src/rpcrawtransaction.cpp:165: undefined reference to `upgrader'
/build/buildd/gridcoinresearch-3.3.8.8/src/rpcrawtransaction.cpp:165: undefined reference to`Upgrader::getFileDone()'
/build/buildd/gridcoinresearch-3.3.8.8/src/rpcrawtransaction.cpp:166: undefined reference to `upgrader'
/build/buildd/gridcoinresearch-3.3.8.8/src/rpcrawtransaction.cpp:166: undefined reference to`Upgrader::getFileSize()'

It looks to my untrained eye that Rob has confused Upgrader with gridcoinupgrader as the call to the binary. I could be way off on that though.

**Comment by caraka** [comment]
I doubt that sEp. Almost all the coins have helper scripts that require dependencies that are not part of any base system - like bitcoin's _bash-completion_ - which isn't even available on a number of platforms. Leders stuff is ubiquitous. If they refuse us for something this standard to linux, such as curl and zip, then something is very, very wrong with the exchange. Getting refused for something exotic I would understand. But not this.

**Comment by Lederstrumpf** [comment]
@caraka For those compiling errors, uncomment lines 41 & 42 in rpcrawtransaction. Rob's pulling everything thing in manually, so I believe he initially commented them when he was testing the features and missed them just now.

**Comment by sEpuLchEr** [comment]
Yes, but you want to be on the exchanges, you follow their rules. They won't follow yours.

**Comment by caraka** [comment]
All I'm saying is that I do not believe for a minute that any exchange is going to refuse to install curl or zip. It's fundamentally ridiculous. You've got to show me those ridiculous rules in writing before I'll entertain them. I don't believe they exist. But this should be kept for another thread...

**Comment by caraka** [comment]
Lederstrumpf - see if you can access this build log, just in case there are any other lines that need commenting out:
https://launchpadlibrarian.net/196555892/buildlog_ubuntu-trusty-amd64.gridcoinresearch_3.3.8.8-r9~ubuntu14.04.1_FAILEDTOBUILD.txt.gz

In the meantime, I cannot alter the source code because it is tied to Rob's git directly - part of the trust model.

If it is just one or two lines to comment out, i suppose I could patch.

**Comment by Lederstrumpf** [comment]
@Sepulcher, I see the concern. I presume most exchanges would much prefer to compile new versions themselves; don't know about the blockchain bootstrapping. Perhaps aside from the flag to exclude the upgrader, we could add another to exclude everything dependent on libzip and curl.

**Comment by Lederstrumpf** [comment]
@caraka there may of course be more errors after those I mentioned due to the lines that require uncommenting. There's nothing else preceding them in your log, so it could also be fine otherwise.

**Comment by Lederstrumpf** [comment]
Regarding the dependencies, it may be best to simply approach some of those considering to take us and enquire if it presents any trouble to them. I'd also be surprised if a server does not have curl etc, but they may be running utter barebone setups (although curl is as barebone as it gets, in my view ^^).

**Comment by sEpuLchEr** [comment]
@caraka And all I'm saying is, if I were to run an exchange and your coin requires me to install anything that is not already in my system, then it will not get listed. Simple as that, but I may be wrong. Just need to remember though, we need the exchanges, not the other way round. Whether they are the standard or not, any extra install increases risk, even if minuscule. A risk is a risk. 

@Lederstrumpf My Ubuntu 14.04 LTS doesn't have them. If I don't have them, there may be a chance the exchanges do not have them. But like I said, I may be wrong.

**Comment by caraka** [comment]
Both libcurl4-openssl-dev and libzip-dev are part of the Ubuntu 1404 LTS base system, with the Ubuntu logo next to them in synaptic. They are not installed by default, but they are most certainly there.

@sEp  I totally agree with your statement about risk. I am simply not willing to believe that an exchange would have a rule against typing:
sudo apt-get install ntp git build-essential libssl-dev libdb-dev libdb++-dev libboost-all-dev libqrencode-dev libcurl4-openssl-dev libzip-dev
but not have a rule against typing:
sudo apt-get install ntp git build-essential libssl-dev libdb-dev libdb++-dev libboost-all-dev libqrencode-dev
before typing make.

libboost-all-dev and libqrencode-dev are not already in any system, and are less common than curl or zip.
I totally agree that we need the exchanges, not the other way around. However I think we're over thinking about a rule that almost certainly doesn't exist. I'll believe it when I see it.

**Comment by sEpuLchEr** [comment]
Any dependencies that are not part of the Bitcoin's core have the potential of not being installed by the exchange. Why do you think Rob was concerned and asked it to be tested?

**Comment by caraka** [comment]
I hear you and I'm not disagreeing with your fundamental concern. I'm merely stating my opinion that I think it is a non-starter. The very problems that we are experiencing right now are the most significant reason for ample testing, IMHO.

just try this:
sudo apt-get install libcurl4-openssl-dev libzip-dev

But you'll have to uncomment those lines as Leder pointed out before you compile.  ;-)

**Comment by sEpuLchEr** [comment]
Try seeing from the exchanges view of point. You hold assets belonging to others, are you willing to take any risk? I'm very sure you can come up with the same conclusion. There is no risk that is worth taking. But all these may be moot point if they're already running them... so.. tell Rob and let Rob contact the exchanges.

**Comment by sEpuLchEr** [comment]
I'm not running an exchange but I will not install anything extra if I do not need. See? I'm paranoid. Exchanges will be 1000x more.

**Comment by gustav1976** [comment]
If you aim to alleviate the concerns of exchange adoption, please highlight a compilation flag to not include ease-of-use dependencies and make it as well documented as possible.

**Comment by caraka** [comment]
@Lederstrumpf Ive finally got a local clone, and here are the relevant lines of rpcrawtransaction.cpp

38 #ifdef QT_GUI
39 #include "qt/upgradedialog.h"
40 extern Checker checker;
41 #endif

I'm taking a punt and uncommenting 38, 39 and 41. Do stop me if i'm wrong! I'll probably try a local build so I don't burn my allotment at launchpad. I'm close already.

**Comment by Lederstrumpf** [comment]
@caraka STOP!!

**Comment by Lederstrumpf** [comment]
Those aren't comments, but preprocessing directives.
The relevant lines, if still commented, are:

extern void Imker(void *kippel);
extern Upgrader upgrader;

**Comment by caraka** [comment]
LOL I did do a quilt refresh, but that can be undone!  ;-)

I shall start my patch again, thanks!

**Comment by caraka** [comment]
32 extern void Imker(void *kippel);
33 extern Upgrader upgrader;

Both already uncommented.

**Comment by caraka** [comment]
I need to be up in 6 hours for work, so I'm bailing out for the moment. Happy to continue testing on work time in the morning.  ;-)

Here is a trimmed version of the build log should someone need it while I snooze:
https://gist.github.com/caraka/a1a709523ad34a0abd09

**Comment by Lederstrumpf** [comment]
It seems Rob already did that in the very latest commit. 
He also added this function to upgrader.cpp:

wchar_t _convertCharArrayToLPCWSTR(const char_ charArray)
{
    wchar_t\* wString=new wchar_t[4096];
    MultiByteToWideChar(CP_ACP, 0, charArray, -1, wString, 4096);
    return wString;
}

To build on Unix, add '#ifdef WIN32' above and '#endif' below said function.

**Comment by caraka** [comment]
Just in time Lederstrumpf, because I'm like a dog with a bone...

I'll just knock that patch together...

**Comment by caraka** [comment]
I just saw rpcrawtransaction.o go by without errors. Whoop. Almost home.

**Comment by caraka** [comment]
and I spoke a minute too soon, damnit.
Same errors just on my machine this time, not on launchpad:
Big snip
/home/rick/build/gridcoinresearch-3.3.8.8-4/src/rpcrawtransaction.cpp:165: undefined reference to `Upgrader::getFileDone()'
/home/rick/build/gridcoinresearch-3.3.8.8-4/src/rpcrawtransaction.cpp:166: undefined reference to`upgrader'
/home/rick/build/gridcoinresearch-3.3.8.8-4/src/rpcrawtransaction.cpp:166: undefined reference to `Upgrader::getFileSize()'

Just to note these errors occur before we get to building with upgrader.cpp, according to the build log.
Now I am heading for sleep deprivation. i'll check back in about 6 hours.

**Comment by Lederstrumpf** [comment]
That's very odd; I just did another clean clone from the official repo and only ran into the aforementioned issue with the wchar function. We can explore further once you return from the land of slumber ;)

**Comment by caraka** [comment]
Good morning
I see the source has moved on a bit in the last 6 hours.  ;-)
In trying to compile 3.3.8.8-curl2.1, which is the latest on Rob's git, I am getting the MultiByteToWideChar error again?

src/upgrader.cpp: In member function 'bool Upgrader::unzipper(int)':
src/upgrader.cpp:355:55: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < zip_get_num_entries(archive, 0); i++) 
                                                       ^
src/upgrader.cpp: In function 'wchar_t\* convertCharArrayToLPCWSTR(const char_)':
src/upgrader.cpp:524:23: error: 'CP_ACP' was not declared in this scope
   MultiByteToWideChar(CP_ACP, 0, charArray, -1, wString, 4096);
                       ^
src/upgrader.cpp:524:62: error: 'MultiByteToWideChar' was not declared in this scope
   MultiByteToWideChar(CP_ACP, 0, charArray, -1, wString, 4096);
                                                              ^
src/upgrader.cpp: In member function 'bool Upgrader::verifyPath(boost::filesystem::path, bool)':
src/upgrader.cpp:624:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/upgrader.cpp: At global scope:
src/upgrader.cpp:25:12: warning: 'int cancelDownloader(void_, curl_off_t, curl_off_t, curl_off_t, curl_off_t)' defined but not used [-Wunused-function]
 static int cancelDownloader(void _p,
            ^
make[2]: *_\* [build/upgrader.o] Error 1

I'm compiling locally so I don't burn my Launchpad quota.

**Comment by Lederstrumpf** [comment]
The preprocessor directive I mentioned earlier is missing.
Change line 520 in upgrader.cpp from

#ifdef QT_GUI

to 

#if defined QT_GUI && defined WIN32

**Comment by caraka** [comment]
Thank you, trying a patch now...

**Comment by caraka** [comment]
Successful local build, pushing patch to launchpad and compiling 3.3.8.8-curl2.1

**Comment by caraka** [comment]
Testing 3.3.8.8-curl2.1

gridcoinresearchd - downloads blocks successfully and then appears to hang - hitting enter returns to prompt with gridcoinresearchd still running. It did not restart or even try.

gridcoinresearch-qt - downloads blocks successfully and offers 'upgrade' button. When clicked, qt exits, snapshot is correctly unzipped and installed, but on restart I get External dialog box:
_Unable to bind to 0.0.0.0:32749 on this computer. GridCoin is probably already running._ If I then close the instance, which appears to be a new one, not the old one, and then restart, the client begins it's normal sync from the point of the snapshot.
Are we somehow restarting the client twice? (like double clicking when a single click will do?)

I don't know if this is relevant, but I know there is an issue with the qt closing very slowly on Ubuntu - all the way back into the bitcoin source. See line 330 in qt/bitcoingui.cpp:
if(trayIcon) // Hide tray icon, as deleting will let it linger until quit (on Ubuntu)
It's so slow to close that if you don't hide the icon, people think the program has hung when it hasn't.

Perhaps Marix is having a different experience with his qt version?

**Comment by caraka** [comment]
I see the upgrader.cpp patch is enhanced and pushed in 3.3.8.8-upgrader. I will delete my patch. Rob, is it worth a rebuild for further testing, or do my notes above still stand? Since both the issues above existed in previous tests, I think the notes stand.

let me know, happy to build and test locally.

**Comment by Lederstrumpf** [comment]
@caraka, yes I thought about that again. I'm not currently near my compiling environment, but I should get a chance to look at it in the following two hours. In the meantime, could you perhaps verify that the PID in the log matches the client's before you restart it?

**Comment by caraka** [comment]
@Lederstrumpf I have failed in my mission. First, my investor node (qt) no longer starts properly. It dies at _Opened LevelDB successfully_

So I moved to my researcher node (qt) on another machine. download blocks>upgrade, client exits but does not restart or try to do so. Interestingly, the snapshot wasn't unzipped, etc and i did not even see the gridcoinupgrader flash across the sys monitor, so I don't think it was called. This researcher client starts normally, unlike my investor. Both are same version grc, both Ubuntu 1404 LTS.

Before I cry foul, I am going to recompile locally with the entirety of Rob's upgrader.cpp patch push, which has a couple extra instances of _#if defined QT_GUI && defined WIN32_ added for good measure, beyond the one you had me do. I may still have a bit of WIN stuff clogging up my linux upgrader.

This, however, will be in a couple of hours, because unfortunately I'm at work and the real work is calling... I'll be in various meetings for at least four hours from this post. I'll try and sneak something in between meetings. Maybe even during one of them.  ;-)

**Comment by theMarix** [comment]
I am not on openSUSE 12.3 on any of my systems, @Lederstrumpf. I am currently using 13.1, but mostly because real world stuff keeps me occupied 16+ hours a day currently, which leads to me not having time to update my farm of systems.

Regarding hte upgrader binary, for the packaging case it really makes sense to just let us specify the one true path (tm) via a compile time setting. Everything else opens up Pandoras box of unexpected things happening.

The sliding down can be done in Qt, you can see it in Mendeley I think.

I have not observed any issues regarding closing down of Qt. But I am on openSUSE, in contrast to Ubuntu those guys don't work agains everyone else.

@sEpuLchEr I am pretty sure your system had both curl and libzip. Just not the dev packages containing the headers. But the same is true for openssl, qt, bercleydb, boost and all other libraries required to build the coin. In addition, I would doubt that an exchange actually compiles the code on the machine that it will be run. That would require installing a lot of stuff that is not actually needed to run the application.

**Comment by theMarix** [comment]
Building the RPMs I am getting multiple code quality warnings:

```
[  354s] E: gridcoinresearch no-return-in-nonvoid-function rpcrawtransaction.cpp:146
[  354s] E: gridcoinresearch no-return-in-nonvoid-function src/rpcrawtransaction.cpp:146
[  354s] E: gridcoinresearch no-return-in-nonvoid-function src/upgrader.cpp:623
[  354s] E: gridcoinresearch no-return-in-nonvoid-function upgrader.cpp:623
```

On the newer Distributions this actually prevents generation of the RPM.

**Comment by gridcoin** [comment]
Thanks for all the testing; its good to have the experts out on this on the configuration side to hit it hard.  SeP thanks for supporting the best interests - I was thinking of the dependencies last night and came to the conclusion that if any exchanges squawk about having to install the -dev versions of libzip and curl, we can just add the compiler directives to block off the upgrade feature for headless - so it wont be the end of the world if for example c-cex cant build it and stops.  Although Marix and Caraka are correct that the ubuntu box has the binary libs of these two, the actual problem is only the -dev version has the headers- so it definitely will require an apt-get to install the dev versions - which, as we know is relatively trivial, but does require us to ask for system admin configuration changes to the exchange environment.  I am sure they actually do build the coin from scratch because I sat there for 4 hours while they are asking me questions about deleting .o files, etc etc.  :).  We're good though with our back up plan to block off the feature as a last resort.

Unfortunately being as pessimistic as I am, the reality most likely will be that 2 of the 3 exchanges build it and at least one complains.  So that means another few hours of work - but Im not going there til it happens.

Thanks again everyone.

Rob

**Comment by gridcoin** [comment]
@Marix -
I think I can fix these two return statements; give me 5 mins.

**Comment by gridcoin** [comment]
@Marix -
Ok, those two functions have return statements now (in).

Rob

**Comment by theMarix** [comment]
Thanks, guess I should have waited instead of patching for the RPM. :)

**Comment by theMarix** [comment]
I know we just have to accept reality as it is, but they really shouldn't be building the coin on the system they will run it on. I well understand why they want to build the binary themselves, but if they pull in everything required to be able to build at all, then they really have different issues than needing the libcurl-devel package. The proper way is to build it on some build server or desktop using the same OS, and then copy it to your minimal installation node that provides the service.

**Comment by gridcoin** [comment]
@Marix, 

I see what you are saying; they may be copying the build to the prod environment.  Ill ask c-cex if they copy the compiled binary to the farm once they compile. 

Thanks,
Rob

**Comment by caraka** [comment]
Managed a clean local debuild of 3.3.8.8-upgrader-return using my standard deb packaging during this work meeting, but unfortunately won't have time to actually install and test it until after the next meeting. Clean is good!

**Comment by theMarix** [comment]
The GUI now fails to start up after I updated blocks with the following error message:

```
gridcoinresearch: src/kernel.cpp:769: unsigned int GetStakeModifierChecksum(const CBlockIndex*): Assertion `pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)' failed.
```

**Comment by caraka** [comment]
I can confirm Marix' experience fully this time, including the error message.

**Comment by sEpuLchEr** [comment]
I hope you guys understand, I'm not trying to be a pain in the butt. We have too much at stake here and I just want to make sure that we will go smoothly onto the exchanges.

**Comment by caraka** [comment]
I've been doing a semi-methodical rollback this morning to try and get my local node back into a working state.
What I discovered was that the kernel.cpp error both marix and I have experienced is definitely the result of an _output_ from the upgrade process that renders something in the .GridcoinResearch folder unusable. 
I also discovered that a snapshot of the entire .GridcoinResearch folder was taken as part of what I presume was the upgrade process, not the  download blocks process. Hurray for good programming! Restoring this backup allowed normal progress to resume, using the same client version that failed previously.

All this took place having rolled back to the 3.3.8.8-upgrader version, the one that the gridcoin-daily PPA is currently sitting at.

I then reinstalled my local compilation of 3.3.8.8-upgrader-returns, the current HEAD version, using the restored .GridcoinResearch folder, and it's all working.

I then switched to the headless, also upgraded to 3.3.8.8-upgrader-returns. It starts OK but does not give the _GridCoinResearch starting_ message and does not let go of the terminal. However, querying from another terminal shows normal function. Forcing the original terminal to close did not terminate gridcoinresearchd, so something simple is hanging.

My 3.3.8.8-upgrader-returns build does include Marix' patch (pull request #19 ), but I haven't run the gridcoinupgrader at all because I now have working nodes, so it is not a factor here.

**Comment by gridcoin** [comment]
Due to security concerns from exchanges, we will have to take a new approach for upgrading linux and  automatically downloading blocks on linux.  I think we will need to disable the autoupgrade on linux and take a look at adding in a command in the core that can bootstrap the blocks file before the client starts with a switch.  Later on, we can make the client automatically pull down the blocks by default for a brand new user.  Ill take a look at adding that cross platform compatible feature next (to download the blocks on startup when none exist).

Rob

**Comment by theMarix** [comment]
@gridcoin : We already disable all upgrade functionality in the Ubuntu / Debian and SUSE / Fedora builds. If you want I can create a pull request with the patch for this.

**Comment by gridcoin** [comment]
Yes, please, that would be great.

**Comment by theMarix** [comment]
Looking into it I just realized that you already merged the relevant part. Compiling with `NO_UPGRADE`, analogous to using `USE_UPNP`, disables all upgrade functionality (and removes it from the UI).

**Comment by gridcoin** [comment]
Ok, excellent, thanks.  I just added NO_UPGRADE to the windows default build command in gridcoinresearch.pro.

Looks like it compiles correctly.  Ill test it locally.

I suppose we can close this now.  Ill look at adding a switch to download the blocks file cross platform today also.

**Pull request closed without merging**
