### PR TITLE
Space-saving lossless compression

### PR DESCRIPTION
**Pull request by Peppernrino**
Compressed all image files and .zip folders.

Also, I remastered the Galaza soundtrack!

Current values:
abducted 176 kbps 11025 Hz 16bit
bgm  705 kbps 44100 Hz 16bit
dive  1411 kbps 44100 Hz 16bit
enemyShot 1411 kbps 44100 Hz 16bit
eol  1536 kbps 48000 Hz 16bit
explosion 352 kbps 22050 Hz 16bit
gravity  1411 kbps 44100 Hz 16bit
nextlevel 1411 kbps 44100 Hz 16bit
pickup  1411 kbps 44100 Hz 16bit
shoot  1411 kbps 44100 Hz 16bit
warp  176 kbps 11025 Hz 16bit

Merged stereo into one track, render in 8bit mono with Hz decreased.
Fixed naming scheme a bit. (Uncaps .WAV... appears they have recapped themselves for some reason. haha.)

New values:
abducted 176 kbps 11025 Hz 8bit
bgm  256 kbps 32000 Hz 8bit (also fixed timing for proper looping)
dive  256 kbps 32000 Hz 8bit
enemyShot 256 kbps 32000 Hz 8bit
eol  256 kbps 32000 Hz 8bit
explosion 176 kbps 22050 Hz 8bit
gravity  256 kbps 32000 Hz 8bit
nextlevel 256 kbps 32000 Hz 8bit
pickup  256 kbps 32000 Hz 8bit
shoot  256 kbps 32000 Hz 8bit (also decreased the length for optimal replay)
warp  176 kbps 11025 Hz 8bit

The resulting clips sound better, will play on more device types, and are much smaller. Gameplay may even improve due to the sprites and audio being optimized.

* nextlevel.wav is not present in .cs file
* abducted and warp are the same sound (possibly share in future)
* nextlevel, pickup, and gravity are the same sound (possibly share in future)

### CODE REVIEW

**Review by denravonska — COMMENTED** [review]
I didn't even know this existed :D
Do we use both splash.jpg and splash.png in the installer or can one of them be removed?

**Comment by Peppernrino** [comment]
my guess would be the latter. :P

**Comment by denravonska** [comment]
The png seems to be used in the code while the jpg is only in the project tree. Perhaps we should remove the jpg then. Anyone familiar with the Windows build who can verify this?

**Comment by skcin** [comment]
I think there are several images that are not used anymore. As far as I know only splash3.png is used. But I don't know about the windows build.

**Comment by Peppernrino** [comment]
i am on windows. i'll do some digging. :)

if i had to guess, i'd say we use ~10 of the images in there. there's the BOINC logo, Gridcoin logo, and background image when the wallet is open... the transaction/mined/interest icons... and opening splash, as you said.

**Comment by Peppernrino** [comment]
closing and redoing pull request to make everything a bit easier. :)

**Pull request closed without merging**
