### PR TITLE
Use the simple gridcoin icon as a windows icon instead of the novacoin one

### PR DESCRIPTION
**Pull request by theMarix**
This is only a very simple fix to make the icon at least not appear completely broken. If somebody is willing to create a set of scaled versions, or a vector one, I would happily include those and update the request.

### CODE REVIEW

**Comment by caraka** [comment]
I won't create a pull request of my own, but I will say that in addition to changing the 
"bitcoin" image path, for debian derivatives you need to change the "toolbar" image path as well. 

I use the grcsimple.png for both

Further to this, the "toolbar" path appears twice in bitcoin.qrc, causing a harmless but annoying warning at compilation time.

**Comment by theMarix** [comment]
@caraka, I am not sure when I'll find time to do the changes you suggested. If you want to speed up the process feel free to create a pull request against my branch. Then I can easily update this one.

**Comment by caraka** [comment]
@theMarix Got it. Will do.

**Comment by caraka** [comment]
Kia ora Marix

I munged my fork trying to create a pull request against your branch. Also, when looking at it, it still includes the path the the copied grcsimple.png, not the original in share/pixmaps. Out of ignorance (not being able to do a clean pull request to your branch), I created my own pull request #23 to the main. I've tested it with my builds. If you got a second, have a look and see if it will meet your needs.

**Comment by gridcoin** [comment]
Merged.

**Pull request closed without merging**
