### PR TITLE
Translate '/src/qt/locale/bitcoin_en.ts' in 'pt_PT'

### PR DESCRIPTION
**Pull request by cyrossignol**
Replaces #2075.

### CODE REVIEW

**Comment by cyrossignol** [comment]
@DjMVeiga Here is a development build for 64-bit Windows with these changes:

[gridcoinresearch-5.3.0.1-trans-pt.zip](https://github.com/gridcoin-community/Gridcoin-Research/files/6216210/gridcoinresearch-5.3.0.1-trans-pt.zip)
SHA256: `7f384c590d94b3b9a520d554ebf965d2369e540756a0988bd2ef598dc58be1d0`

**Comment by DjMVeiga** [comment]
> 
> 
> @DjMVeiga Here is a development build for 64-bit Windows with these changes:
> 
> [gridcoinresearch-5.3.0.1-trans-pt.zip](https://github.com/gridcoin-community/Gridcoin-Research/files/6216210/gridcoinresearch-5.3.0.1-trans-pt.zip)
> SHA256: `7f384c590d94b3b9a520d554ebf965d2369e540756a0988bd2ef598dc58be1d0`

Thanks lot, will make the needed changes on the fly. Much easier.
Some translations can only be made when seeing them applied cirectly on the app

**Comment by DjMVeiga** [comment]
> 
> 
> @DjMVeiga Here is a development build for 64-bit Windows with these changes:
> 
> [gridcoinresearch-5.3.0.1-trans-pt.zip](https://github.com/gridcoin-community/Gridcoin-Research/files/6216210/gridcoinresearch-5.3.0.1-trans-pt.zip)
> SHA256: `7f384c590d94b3b9a520d554ebf965d2369e540756a0988bd2ef598dc58be1d0`

Several changes and fixs done to translation. 
Please commit when possivel. Thanks

**Comment by jamescowens** [comment]
Looks like it opened a new PR. I am closing this one.

**Pull request closed without merging**
