### PR TITLE
Split up bitcoinrpc

### PR DESCRIPTION
**Pull request by sedited**
Split bitcoinrpc up into

- rpcserver: bitcoind RPC server
- rpcclient: bitcoin-cli RPC client
- rpcprotocol: shared common HTTP/JSON-RPC protocol code

Original work by [laanwj](https://github.com/bitcoin/bitcoin/commit/fb78cc23784b2fa478324aac35ca76c7cfe683a4#diff-6acaa876c8e0335a97282193c4cc0428). This is some headway into moving from the outdated json_spirit to univalue.

### CODE REVIEW

**Comment by iFoggz** [comment]
Excellent. The univalue is on my list to do as well as separating the gridcoin rpc commands to its own files. Cheers. Also todo will be removing safemode as its not used

**Comment by denravonska** [comment]
Good job. Can we move them into an rpc subfolder?

**Comment by tomasbrod** [comment]
I am just worried that this work may me lost, when, or if, we decide to rebase.

**Comment by sedited** [comment]
This work is just done to make the Rebase easier. The more code we can just copy paste, the easier.

**Comment by denravonska** [comment]
Much of these have already been done in the more modern bases. Yes, the work will be somewhat redundant but it will make the differences smaller.

**Comment by sedited** [comment]
Rebased.

**Comment by denravonska** [comment]
Need another rebase and I'll merge it.

**Comment by sedited** [comment]
Rebased.

**Pull request merged**
