### PR TITLE
gui: Adjust stylesheets and scale icons to improve HiDPI side toolbar display

### PR DESCRIPTION
**Pull request by jamescowens**
This PR makes some stylesheet adjustments to make the menu bar consistent, fix truncation of the side toolbar icon labels, and also scale the side toolbar icons on HiDPI displays. Further work will need to be done on the stylesheets as they still are quite bizarre.

### CODE REVIEW

**Comment by jamescowens** [comment]
Before....
image

After... (this also includes the new fonts and changes in #1908.
image

**Comment by opsinphark** [comment]
Glad you figured out where the stylesheet issues, it was driving me mad.
Looks good!

**Review by cyrossignol — APPROVED** [review]

**Comment by jamescowens** [comment]
Apparently there is a bug of some sort in the border (or border-style): none. When you use that, it truncates the labels, like it is using a ridiculously thick invisible border. Unfortunately getting rid of the none creates a small visible border on the "light" stylesheet, but it is better than truncating the labels.

I also implemented a simple scaling rule for the icons. I did the same thing for the field widths or something similar in the peers tab when I did that a while back. Seems to work pretty well. This will get us by until you do some more thorough house cleaning, if you want, @opsinphark!

**Comment by opsinphark** [comment]
I'm poking around a bit to see what I want to conquer next.

**Pull request merged**
