### PR TITLE
test, ci: xenial support

### PR DESCRIPTION
**Pull request by div72**
Increased the test timeout as our tests usually doesn't take a while to run, 5 minutes should be more than enough.

Added a new job for xenial and fixed tests for it in a weird way. `boost::test_tools::assertion_result` was added Boost 1.59 therefore it isn't present in Xenial's Boost(1.58). I made a workaround which adds a new test case that adds the tests which require client_state.xml based on whether the file is present or not, although I am not sure if this is the best solution. I tried to avoid macros but perhaps a simple boost version check and return early with an additional file check could be better.

Ex.
```cpp
#ifdef BOOST_VERSION > 105800
BOOST_AUTO_TEST_CASE(it_parses_project_xml_from_a_client_state_xml_file,
    *boost::unit_test::precondition(ClientStateStubExists))
{
#else 
BOOST_AUTO_TEST_CASE(it_parses_project_xml_from_a_client_state_xml_file)
{
if (boost::filesystem::exists(ResolveStubDir() / "client_state.xml")) {
    BOOST_CHECK(false);
}
#endif
```

### CODE REVIEW

**Review by jamescowens — COMMENTED** [review]
I am on the fence. This is ok. The macro way may be better. If we decide the macro route, don't make the same mistake I did...

#ifdef VARIABLE > 123 only checks whether VARIABLE is true, not whether it meets the condition...

it is 

#if VARIABLE > 123.

**Comment by jamescowens** [comment]
@cyrossignol what is your opinion on this?

**Comment by jamescowens** [comment]
Looks like this same issue is affecting older Fedora builds on OBS. See https://build.opensuse.org/package/show/home%3AtheMarix/gridcoin

**Comment by caraka** [comment]
Building this PR not only enables the tests, but they pass as well:
PASS: qt/test/test_gridcoin-qt
PASS: test/test_gridcoin
\============================================================================
Testsuite summary for Gridcoin 5.0.0
\============================================================================
\# TOTAL: 2
\# PASS:  2
\# SKIP:  0
\# XFAIL: 0
\# FAIL:  0
\# XPASS: 0
\# ERROR: 0
\============================================================================

**Review by cyrossignol — APPROVED** [review]
Looks good. I'd rather avoid using macros whenever possible.

**Comment by cyrossignol** [comment]
Also, reporting @caraka for being 

# too awesome

**Comment by jamescowens** [comment]
Haha!

**Review by jamescowens — APPROVED** [review]

**Pull request merged**
