### PR TITLE
Split coin stake output if ower 200 coins.

### PR DESCRIPTION
**Pull request by tomasbrod**
Split coin stake output to two if ower 200 coins. This helps to
overcome the time required for coins to mature.

### CODE REVIEW

**Comment by tomasbrod** [comment]
this is a cherry-pick from my other pr

**Comment by Quezacoatl1** [comment]
@tomasbrod can we talk about this here real quick?
We had a similar function in that we did split the stake in any case. Many people thought this would be increasing security and it was even "hyped" by some as _the_ innovation.

The problem I have with such thing is that while the blocks increase linear over time while the necessary blocks to stake all single transactions increases more than linear. That leads to the situation that not every transaction can stake eventually which just does not seem healthy for our project. Additionally newbies and low-stakers will have a decreased probability to stake at all. Yes, on the other hand this is equal to a little more network security but if we wanted to increase that we could also set a minimum threshold of 1mil GRC to be able to stake. What I mean is that we favorize whales that way which also does not seem healthy IMO.
I am definitely no security expert but my gut feeling tells me it is not healthy for scalability.

Kind regards and thanks for your overall activities, Quez :)

**Comment by tomasbrod** [comment]
Ok, we can keep this on hold until enough info is available. And I will add command to split UTXOs manually.
Note that staking 100 and 25+25+25+25 should have the same chance.

**Comment by Quezacoatl1** [comment]
OK,

Well yes it has the same chance but if the 100 stake the network weight will decrease for 16 110 blocks by 100.

If the 25 stake it will only decrease by 25 and remain 75. 

If you are a newbie with 1 GRC you have a higher possibility to stake after the 100 staked for 110 blocks.

Again, security vs. scalability

**Comment by tomasbrod** [comment]
Now I understand the issue.
A boost for new users and boinc miners is on my to-do list.

**Comment by grctest** [comment]
It'd be very cool if this was configurable by the user - for an user with many GRC this could mean thousands of addresses with 200 GRC each, but if it was split on say 2500 then it would save whales from having to split into several hundred addresses manually.

I created a bash script to split 100k GRC on testnet into 1000 addresses on linux w/ bash, but on windows it's a bit more complex.

**Comment by tomasbrod** [comment]
@grctest You mean a config option like `splitminvalue` that when set, will split the output if greater than what was set? That could be easy, but will go against what @Quezacoatl1 said.

I still have that rpc command on todo. Yous script will help me, could you post it @grctest?

**Comment by tomasbrod** [comment]
Rebased on top of development branch. Original at 75c060533cfc7ec2bc4acc3e27dfebe9c7f19b35.

**Comment by denravonska** [comment]
@tomasbrod Is this ready for review?

**Comment by tomasbrod** [comment]
As you see, people don't agree with this. Need to add a command and  to be configurable.

**Pull request closed without merging**
