### PR TITLE
refactor: split clientversion from version

### PR DESCRIPTION
**Pull request by div72**
This PR splits clientversion.cpp/h from version.cpp. The reasoning for this PR is getting closer to upstream.

Needed by #2368.

### CODE REVIEW

**Comment by barton2526** [comment]
I think `#include <boost/algorithm/string/join.hpp>` can be removed from util.cpp after this change

**Review by jamescowens — APPROVED** [review]
utACK

**Comment by jamescowens** [comment]
Hmm... I merged this but should have tested it beforehand.

2021-10-31T14:48:04Z Default data directory /home/jco/.GridcoinResearch

2021-10-31T14:48:04Z Using data directory /home/jco/.GridcoinResearchTest/testnet

2021-10-31T14:48:04Z Gridcoin version v5.3.2-unk (release build)
2021-10-31T14:48:05Z Starting Gridcoin
2021-10-31T14:48:05Z Initializing Core...
2021-10-31T14:48:05Z Boost Version: Using Boost 1.66.0

2021-10-31T14:48:05Z Using specific arg default
2021-10-31T14:48:05Z Using the 'sse4(1way),sse41(4way)' SHA256 implementation

2021-10-31T14:48:05Z Using RdRand as an additional entropy source

2021-10-31T14:48:05Z Block version 11 hard fork configured for block 1301500
2021-10-31T14:48:05Z INFO AppInit2: DataDir = /home/jco/.GridcoinResearchTest/testnet.
2021-10-31T14:48:05Z Using OpenSSL version OpenSSL 1.1.1d  10 Sep 2019

image

**Comment by jamescowens** [comment]
Please debug, do an integration test and submit a PR to fix ASAP. Thanks.

**Comment by jamescowens** [comment]
The above screenshot was with PR2368 included, but if you go to the dev branch, which includes this PR, the error is the same.

**Comment by jamescowens** [comment]
Quickly looking at this, it appears you have removed the fourth version parameter, and now the wallet will fail to load.

new clientversion.h...

static const int CLIENT_VERSION =
                             10000 * CLIENT_VERSION_MAJOR
                         +     100 * CLIENT_VERSION_MINOR
                         +       1 * CLIENT_VERSION_BUILD;

old version.h

static const int CLIENT_VERSION =
                           1000000 * CLIENT_VERSION_MAJOR
                         +   10000 * CLIENT_VERSION_MINOR
                         +     100 * CLIENT_VERSION_REVISION
                         +       1 * CLIENT_VERSION_BUILD;

DBErrors CWalletDB::LoadWallet(CWallet* pwallet)
{
    LOCK(pwallet->cs_wallet);

    pwallet->vchDefaultKey = CPubKey();
    CWalletScanState wss;
    bool fNoncriticalErrors = false;
    DBErrors result = DB_LOAD_OK;

    try {
        int nMinVersion = 0;
        if (Read((string)"minversion", nMinVersion))
        {
            if (nMinVersion > CLIENT_VERSION)
                return DB_TOO_NEW;
            pwallet->LoadMinVersion(nMinVersion);
        }

Please put the client version build parameter back in.

**Comment by jamescowens** [comment]
I think I fixed it. See #2371.

**Comment by jamescowens** [comment]
I am glad you got rid of the old creaky code in this area BTW....

**Pull request merged**
