### PR TITLE
build: vendor bdb 5.3

### PR DESCRIPTION
**Pull request by div72**
Prior to this PR, Gridcoin wallets have been using two different versions of the Berkeley DB. Flavors of Linux where the packages are built on the OBS, which include OpenSUSE, Redhat, and other rpm based distributions have historically used BDB 4.8, which is the same as the Bitcoin standard. The official Windows builds also use BDB 4.8. However the Debian based distributions and similar have used BDB 5.3.

Recently Arch has made available 6.2 and several people have installed it. This has caused the wallet to segfault when running. (It builds but 6.2 is too different to work without changes.)

Having two different database versions for the wallet.dat file causes a number of problems. Any wallet.dat created under BDB 4.8 when run with a wallet compiled against BDB 5.3, will be upgraded to the 5.3 format. The converse cannot happen. A wallet.dat created on a BDB 5.3 platform cannot be downgraded to BDB 4.8. So this causes very hard to understand portability problems for folks wanting to move wallets across platform.

To solve this problem the core devs have decided to include the bdb53 source as part of the Gridcoin build tree, and statically link against bdb 5.3 for the wallet. This will force all wallets to the 5.3 standard. We do not need to maintain lowest common denominator compatibility with Bitcoin.

### CODE REVIEW

**Review by jamescowens — COMMENTED** [review]
This is a really nice job @div72. I wonder if we should implement a backup of the wallet.dat file if the file is being upgraded, along with a log entry and a notification to the user (if running the GUI version) about the upgrade?

**Comment by div72** [comment]
@jamescowens Not a bad idea, but do you know any good way to detect upgrades without hacking something at the BDB source or log file parsing? I could not find any suitable APIs  and the only difference between 4.8 and 5.3 I could find is that `od -An -j16 -N4 -td ~/.GridcoinResearch/testnet/database/log.000*` is returning 16 for 4.8 vs 19 for 5.3 (bytes between 16-20).

Hell, is the file even being upgraded or can 4.8 just not parse logs from 5.3? I remember reading something like that in some upstream discussions.

**Comment by jamescowens** [comment]
I am not sure whether it is both the format of the base dat file or just the log file that is the problem. Let me poke around a little bit.

**Comment by jamescowens** [comment]
Via testing I have confirmed that @div72 is correct. It is only the log file itself that has changed format.
Here is the test (which has to be done on a bdb48 machine to be meaningful):
1. make a safe copy of the bdb 48 wallet.dat and the database subdirectory (containing the log file)
2. run a version of the wallet with this PR included.
3. verify wallet is transparently upgraded (yes)
4. shutdown wallet and try to run without the PR (which uses bdb 48 on my machine)
5. this results in a corrupted wallet error message
6. acknowledge critical error and then remove log.* file(s) from database (log) directory.
7. restart with bdb 48 version and confirm wallet comes up. (It does.)
8. Notice that log numbering has restarted at .0000000001

**Review by jamescowens — APPROVED** [review]
ACK.

**Comment by nethershaw** [comment]
Great. As a package maintainer, this makes my life harder. Thanks.

https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries

**Comment by jamescowens** [comment]
There are valid reasons to bundle dependencies. This is one of them. The precise reason is that we do not need or want to necessarily follow updates on the upstream, or if we do, we want it to be on our terms. This is the same stance as Bitcoin Core. Thanks.

I don't see why it makes your job harder. Your job as a maintainer is NOT to mess around with bundled dependencies. Dependencies are bundled because they have been well-tested in our specific use-cases.

As an example,. go look up the situation with Bitcoin with leveldb early on where they had a consensus issue with leveldb changes introduced upstream. As a result they bundle a specifically tested version of leveldb.

We speciically do NOT want you to mess around or try to update in-source tree dependencies. Thanks.

**Comment by jamescowens** [comment]
One other comment. The new OS_TREE and flatpacks, etc. are essentially a fancy way of dependency bundling... in those cases I side with you and think that is unnecessary bloat.

**Pull request merged**
