### PR TITLE
Change to light_stylesheet.qss for scalablility

### PR DESCRIPTION
**Pull request by RoboticMind**
Changing all absolute px values to relative pt values

### CODE REVIEW

**Comment by denravonska** [comment]
I'm not sure this one works. I just tried it and the tabs toolbar disappeared.
screenshot_2017-08-03_17-11-26

**Comment by RoboticMind** [comment]
Oh i made a mistake here i'll close it

**Comment by denravonska** [comment]
You could also update the current ones with new commits :)

**Comment by skcin** [comment]
hey @RoboticMind, I am not sure the pt values are the way to go. We would like to make the wallet high dpi aware. So I think the px values definitley have to go, but I am not sure if the pt values are the solution. I have no high dpi experience ith Qt, so I am not sure about the best cross platform solution. Do you have any insights on the benefits of using pt values?

**Comment by RoboticMind** [comment]
@skcin I am new to Qt so i was trying to use pt values. I think maybe using percentages would be better because it can scale very. Pt can't scale as well from resizing the windows and things like that so i would agree and say that it isn't the right way to go.

**Pull request closed without merging**
