### PR TITLE
log: grammar correction

### PR DESCRIPTION
**Pull request by nathanielcwm**

### CODE REVIEW

**Review by RoboticMind — APPROVED** [review]
Only thing to mention is to add a category to the pull request title. Probably should be `log: grammar correction` 

See
https://github.com/gridcoin-community/Gridcoin-Research/blob/development/CONTRIBUTING.md#creating-the-pull-request for more details

**Comment by nathanielcwm** [comment]
My bad, was such a minor correction I didn't think about the categories or anything like that.

**Comment by nathanielcwm** [comment]
Actually I might as well just go through and double check for any other issues.

**Comment by RoboticMind** [comment]
> My bad, was such a minor correction I didn't think about the categories or anything like that.

All good. It's easy to miss

> Actually I might as well just go through and double check for any other issues.

It's only a one character change and a title, so I don't think there's anything else that really could have an issue. I think it's good to merge

**Review by jamescowens — APPROVED** [review]

**Pull request merged**
