### PR TITLE
spell-correct threshold

### PR DESCRIPTION
**Pull request by caraka**
insignificant spelling corrections of threshold across comments in 4 files. Cleans up 4 lintian compilation warnings/issues. I don't understand why the main.cpp changes appear so large - I changed/deleted one letter on line 9576.

### CODE REVIEW

**Comment by denravonska** [comment]
Reimplemented in development branch. You got a large commit because your editor couldn't figure out how to deal with the dual line endings in main.cpp.

**Comment by tomasbrod** [comment]
Why can't the line endings be changed once and for all? Or are you so obsessed with smallest-patch-as-possible?

**Comment by caraka** [comment]
@tomasbrod this was an unusual artifact caused by my dev environment, not any real issue at all. And it's sorted, thanks @denravonska

**Comment by denravonska** [comment]
@caraka Actually, it is an issue since it blocks development. @gridcoin Can we please fix this? :D

@tomasbrod I'll always vouch for small diffs since it's easier to see what's going on. I'm all for fixing the line endings but it should be done in a separate commit.

**Comment by caraka** [comment]
Learn something new everyday. I thought I was the problem here.  :D

**Pull request closed without merging**
