### PR TITLE
Remove the Color of (Out of Sync) so it use the Stylesheet

### LINKED ISSUE #1011: Change color of "Out of Sync" transactions in wallet
On MacOS High Sierra (only OS that I've tested on), the "Out of Sync" text for recent transactions is light blue. The contrast of light blue on the current background of the wallet makes it difficult to notice and read the text.

Suggest making that text red, like the text for when the wallet is out of sync. Assuming that the text color might be different from the wallet "out of sync" text currently for a reason, if it needs to be a different color than the text for the wallet being out of sync, I suggest a shade of orange or brown for the transactions "out of sync" text.

gridcoin-mac_1

### PR DESCRIPTION
**Pull request by ghost**
Will Close #1011 
Realy not sure why it was there 
EDIT: But we can think about something like Bitcoin has done https://github.com/bitcoin/bitcoin/commit/7247d103ffc2772b6dd997b7aa4d7147a8044d73
outofsync
only tested on Dev branch

### CODE REVIEW

**Comment by iFoggz** [comment]
good work the difference i saw in dev branch for color label was actually the other out of sync label that was addressed before. I don't know why this one was not addressed at the same time.

**Review by iFoggz — APPROVED** [review]

**Comment by iFoggz** [comment]
ACK `9ab40df`

**Comment by denravonska** [comment]
Red represents something negative, as in an outgoing transaction. Is that what we want here?

**Comment by ghost** [comment]
It's the Warning that the Wallet is (Out of sync).
So i think Red is good for that.

**Comment by tomasbrod** [comment]
What about yellow?

**Comment by denravonska** [comment]
Did the wallet addresses also used to be red?

**Comment by ghost** [comment]
I dont think that Yellow will work, cause it has the same Problem as #1011 , that you cant read it with the light theme.EDIT: It can be changed in the Stylesheets #labelWalletStatus & #labelTransactionsStatus{
With my PR it uses now the Line 454-460 of https://github.com/gridcoin/Gridcoin-Research/blob/development/src/qt/res/stylesheets/dark_stylesheet.qss 

The Addresses with a Label are shown with red text in Master and Dev Branch, so its not Related with the PR.

But i think the Transactions Widget needs a deeper look. It looks like the Widget has its own Colors(grey and red) on both themes. 
It will look better(and is better to read) when it is the same as the rest of the Wallet: 
White on Dark 
Black on Light  
The Amount of the Transaction looks right -> Red when Out, Black/white when In
2018-03-10-161319_swaygrab
This looks not so easy to me, maybe add the TransactionWidget part to #1021 or make a new Issue for that

**Comment by ghost** [comment]
Have add a small Fix for the Dark Theme so you see if the Checkbox is clicked or not.
Not sure if i need to add it to the light Stylesheet too?!
Edit: Working on cleaning up the Stylesheet, will do the same with the light and add the Checkbox stuff too(that will be a extra PR i think)

**Comment by ghost** [comment]
I think i found the Source of the Color in the Transactions Widget 
overviewpage.cpp:60  makes the Red of the Address with Label
It would be nice if we can Change the Color in the Stylesheet, but thats over my knowledge...
The Color of the Address without Label is not yet found 
EDIT: Found it: qt/guiconstants.h:21:#define COLOR_BAREADDRESS QColor(140, 140, 140)

**Comment by tomasbrod** [comment]
I do not know how much CSS Qt supports, if it does, I suggest to use css class for this. In stylesheet define that class x should have colour y, then in code, instead of raw colour value, set the class.

**Comment by ghost** [comment]
Would it not make more sense to make a own Issue for the Transactions Widget(and Network Widget) to add them to the Stylesheet? So this PR with the small fixes can be Reviewed.
My experience is enough for "low hanging Fruit" work, but not yet for "real" Code changes.

**Pull request merged**
