### PR TITLE
Add message support to sendtoaddress and sendfrom

### LINKED ISSUE #1346: Sendtoaddress does not set the transaction message

### PR DESCRIPTION
**Pull request by denravonska**
This closes #1346.

### CODE REVIEW

**Review by jamescowens — COMMENTED** [review]
Should you add the message parameter to the help section?

**Comment by denravonska** [comment]
@jamescowens You want it removed from the help?

**Comment by jamescowens** [comment]
Nope. Two of your commits were on the same thing. Good to go.

**Review by jamescowens — APPROVED** [review]

**Comment by denravonska** [comment]
Aha, they were for two different commands :)

**Comment by satonakamo** [comment]
could it be possible to move this update to the upcoming Camilla release?

**Comment by jamescowens** [comment]
I don't see why not. @denravonska ?

**Comment by denravonska** [comment]
I am fine with that. Let me see if I can rebase.

**Comment by satonakamo** [comment]
does the addition of this feature allow for the same functionality (adding message) using the createrawtransaction method?

**Pull request merged**
