### PR TITLE
The static build was not showing svg's icons on runtime. The static b…

### PR DESCRIPTION
**Pull request by sedited**
…uild did not include the reqcuired .svg plugins.

This fixes it by adding the QtSVG package to depends and linking the svg and svgicon plugin to static executables.

It does not cross compile to darwin. I already spent a full day finding out why, but could not discover the culprit. Some help here would be greatly appreciated.

### CODE REVIEW

**Comment by ghost** [comment]
QTSVG documentation says this about SVG, have you tried this?

Rendering SVG Files

Qt SVG provides classes for rendering SVG files. To include the definitions of the module's classes, use the following directive:

#include  QtSvg

To link against the module, add this line to your qmake .pro file:

QT += svg

-------
It is interesting to note that (without auto tools) the ruby Jiro patch builds the App with all icons intact, by using only Qt as the dependency. Using only "qmake" followed by "make".

**Comment by sedited** [comment]
The PR contains exactly what you just proposed - it includes the qsvg plugins when compiling statically, and does so successfully for linux, windows and arm. The problem is that the static darwin build does not pick up the apple SDK.

**Comment by ghost** [comment]
So the Apple SDK again eh. I'll forward this to Jiro for his comment...

**Comment by Git-Jiro** [comment]
Hi @TheCharlatan,
Here are my 2 Cents about this issue:

I did the following: I compared the output of Travis-Jobs 722.6 and 731.6.
Job 731.6 is from your PR #828, which worked just fine.
This PR #849 got Job 722.6 and has issues with the Apple SDK, as you guys said.
I have seen some differences in the behaviour of the Jobs when they setup the build.

I have the following hunch about this issue:
For your PR #828 the MacOS cross compilation seems to work fine.
For this PR it doesn't.
This PR is based on an older commit compared to PR #828.
So maybe this PR is just based on a bad state of the build environment and therefore it is failing.

Try to rebase this PR to the same commit you based PR #828 on and check if this will improve things.

**Comment by sedited** [comment]
The static darwin build does run fine for previous builds. It is only the QtSvg module, that fails to compile - no change made in other branches may improve this situation. QtBase, QtTools and QtTranslations all compile with the SDK.

**Comment by Git-Jiro** [comment]
I had another look at the Travis 722.6:
Yes, my mistake was I interpreted build errors in the configure part of the build as "real build errors".

For me it looks like compiling QtSVG works. What fails is the final step of creating the library using "ar". For me, the final build errors seems to be "make[2]: x86_64-apple-darwin11-ar: Command not found". This is crazy, because creating libraries with x86_64-apple-darwin11-ar was working perfectly fine several times before ...

**Comment by ghost** [comment]
Does this "-ar cq" Qmake configuration help by any chance? https://dexp.in/download/qmake-macosx.conf

Reference: "x86_64-apple-darwin11-ar cq"  referring to Qmake configuration.

**Comment by ghost** [comment]
Just for info, the "make deploy" command produces a functional app complete with all icons.

**Comment by sedited** [comment]
Good to hear, that it runs with native builds. I will disable cross compilation on Travis for now, so we can move on with this. Will continue my research on why this happens though.

**Pull request merged**
