### PR TITLE
Update Copyright Years

### PR DESCRIPTION
**Pull request by barton2526**
It's 2018!

### CODE REVIEW

**Review by tomasbrod — COMMENTED** [review]
Is this legal?

**Comment by barton2526** [comment]
@tomasbrod This PR merely updates the MIT licensing on the Gridcoin copyright notes to include the new year of 2018.  Nothing actually changes from a licensing perspective except for the note that it is still being developed under MIT.

**Comment by denravonska** [comment]
I'm not so sure we should use copyright ranges at all, but just the initial copyright year: https://stackoverflow.com/a/2391555

> The date on the notice establishes how far back the claim is made. This means if you update the date, you are no longer claiming the copyright for the original date and that means if somebody has copied the work in the meantime and they claim its theirs on the ground that their publishing the copy was before your claim, then it will be difficult to establish who is the originator of the work.

Edit: On the other hand: http://epiphany.law/articles/copyright/copyright-dates-single-year-or-range

> This is appropriate for ‘documents’ such as web pages or software programs which are constantly being revised and updated incrementally. The ‘start’ year should be the date of the oldest content still contained in the work, with the ‘end’ year being the last year that the work was revised.

**Comment by barton2526** [comment]
@denravonska I was merely updating the copyright for existing ranges.  If we want to remove ranges altogether, I can do that as well, but note that this will affect copyrights we don't technically own (Bitcoin, Peercoin, Blackcoin, etc).

Regarding the usefulness of copyright ranges, I would tend to believe a legal resource over some folks on StackOverflow ;)

**Review by tomasbrod — APPROVED** [review]

**Comment by denravonska** [comment]
Ranges seem the way to go with software.

**Pull request merged**
