### PR TITLE
test: Add dead code detection

### PR DESCRIPTION
**Pull request by barton2526**
This adds unreachable code detection for Python based on `vulture`.

Ref: https://github.com/bitcoin/bitcoin/pull/21096

### CODE REVIEW

**Comment by barton2526** [comment]
From the CI, this error prints from the linter:
``` 
test/lint/lint-all.sh: line 23: test/lint/lint-python-dead-code.sh: Permission denied
^---- failure generated from test/lint/lint-python-dead-code.sh

**Comment by div72** [comment]
@barton2526 `chmod +x test/lint/lint-python-dead-code.sh`.

**Comment by barton2526** [comment]
> @barton2526 `chmod +x test/lint/lint-python-dead-code.sh`.

This is in the Github Actions runner

https://github.com/gridcoin-community/Gridcoin-Research/runs/5382624866?check_suite_focus=true#step:4:435

**Comment by div72** [comment]
@barton2526 Yes, it's complaining about the execute bit not being set. You need to mark the file as executable.

**Comment by barton2526** [comment]
Moved to https://github.com/gridcoin-community/Gridcoin-Research/pull/2449

**Pull request closed without merging**
