### PR TITLE
Remove deprecated RSA weight and legacy kernel

### PR DESCRIPTION
**Pull request by cyrossignol**
This cleans up the staking kernel by removing the old algorithms for version 7 blocks and earlier. It removes the deprecated RSA weight parameter and provides a mechanism to carry proof hashes of version 7 blocks into version 8 to facilitate the calculation of the stake modifier for the current staking kernel routine.

### CODE REVIEW

**Comment by jamescowens** [comment]
This seems to pair with #1497 as clean up for the mandatory.

**Comment by cyrossignol** [comment]
Sync has been tested on testnet and on mainnet by @denravonska.

**Review by jamescowens — APPROVED** [review]
This looks really good to me.

**Comment by jamescowens** [comment]
Give the importance of these changes. I have assigned @denravonska to second review. My guess is that it is a formality, given that @denravonska has synced from zero as a test already (implies he is happy with it).

**Comment by jamescowens** [comment]
Once this is merged, development will branch away from staging... This is post-Elizabeth stuff...

**Comment by jamescowens** [comment]
@denravonska will you sign off on this and then we can merge into development.

**Review by denravonska — APPROVED** [review]

**Pull request merged**
