### PR TITLE
Revert "Merge pull request #1060 from tomasbrod/supercfwd"

### PR DESCRIPTION
**Pull request by denravonska**
This removes superblock forwarding in preparation for the new scraper.

### CODE REVIEW

**Review by tomasbrod — CHANGES_REQUESTED** [review]
Reverting merge commits is bad. I will try to reformat the patch.

**Comment by denravonska** [comment]
Why is reverting merge commits bad? I can't find any info about it.

**Comment by tomasbrod** [comment]
Sorry. I can't do it. This pr appears to work and therefore is good enough.

**Comment by denravonska** [comment]
Replaced by #1430.

**Pull request closed without merging**
