### PR TITLE
voting, gui: Fix formatting and alignment of vote shares and percent

### LINKED ISSUE #1848: Fern RC5 - Poll display should not use exponential notation
image (1)

### PR DESCRIPTION
**Pull request by jamescowens**
This closes #1848.

### CODE REVIEW

**Comment by jamescowens** [comment]
image

**Comment by a123b** [comment]
How about also adding a size policy for the columns? Right now, the available space is allocated equally among the three colums, causing long answer texts to get clipped:

image

The shares and espacially the percentage column won't ever need this much space, so I would suggest defining a preferred width for them and allowing the text column to expand.

**Comment by jamescowens** [comment]
Ok. I changed the Shares and Percentage columns to ResizeToContents. That ought to do it.
image

**Comment by a123b** [comment]
That's much better! IMHO it would look even better with the percentage header changed to just "%".
I also found another small bug, sorting by shares doesn't work / is alphabetical:

image

**Comment by jamescowens** [comment]
Ok. That was a bit annoying. I padded the strings rather than blowing this out into a full blown TableView and having to define a model just for this....

Looks like the sorting works correctly now.

**Comment by jamescowens** [comment]
image

**Comment by a123b** [comment]
I was playing around with this and found the TableView approach not that much of a hassle actually. The StandardItemModel is good enough for it, didn't have to make a custom model. Here's the commit if you're curious: https://github.com/a123b/Gridcoin-Research/commit/78bd47190ce7a306ac25c93c6f83948e6788c1ba

**Comment by jamescowens** [comment]
I prefer yours to mine.

**Comment by jamescowens** [comment]
Personally I think going to the "%" for the column name makes the column too narrow, but I am ok with it.

**Comment by jamescowens** [comment]
It is weird that the sort by the percentage column worked even when they were changed into strings without any further changes, and it doesn't have anything to do with the decimal point being in the string. I added a decimal place to the shares just to see. Anyway, this is good enough.

**Comment by a123b** [comment]
It _is_ pretty small, but it didn't bother me as much as the column being way larger than the shares one. I think padding the "%" with 3 spaces on both sides might be a good compromise:
image

**Comment by jamescowens** [comment]
I am actually ok with it as is...

**Review by cyrossignol — APPROVED** [review]
Looks much better.

**Pull request merged**
