### PR TITLE
Re-activate Windows Installer

### PR DESCRIPTION
**Pull request by sedited**
The windows installer is automatically created by running `make deploy` , similarly to how the .dmg is created on macOS. The installer first uninstalls everything, then re-installs cleanly again. 
Currently all the docs from `doc/` are just bindly copied.

### CODE REVIEW

**Review by jamescowens — APPROVED** [review]
utACK

**Comment by denravonska** [comment]
utACK.

**Comment by jamescowens** [comment]
/bin/mkdir -p ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /home/jco/builds/Gridcoin-Research/build-aux/install-sh -c -s ./src/gridcoinresearchd.exe ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /home/jco/builds/Gridcoin-Research/build-aux/install-sh -c -s ./src/qt/gridcoinresearch.exe ./release
error: could not build gridcoin-4.0.1-win64-setup.exe
built gridcoin-4.0.1-win64-setup.exe

**Comment by jamescowens** [comment]
@TheCharlatan pointed out I was probably missing nsis. That was it. Just tested the win64 version. Works great. I will test win32 later on today and if successful, I will merge.

**Comment by jamescowens** [comment]
It worked for win32 too. Merging.

**Pull request merged**
