### PR TITLE
gui: Install bold variant of Inter font

### PR DESCRIPTION
**Pull request by cyrossignol**
This is a small follow-up for #1908. 

I added the bold variant for the "Inter" font. This improves rendering accuracy and style faithfulness of bold-style text because the rendering engine can use the font data directly instead of extrapolating boldness from the regular variant. I also replaced the regular variant with a desktop font. The original appears to be a web font that doesn't include additional hinting data that may improve legibility in environments that support advanced font shaping (ClearType).

I did not include the italic variants because we don't use this style anywhere that I can see.

Before | After:

image

The screenshot isn't a great example because it's running from a remote Linux session, but it does illustrate the differences between the shapes of the glyphs.

### CODE REVIEW

**Review by jamescowens — APPROVED** [review]
Good.

**Comment by jamescowens** [comment]
Maybe, but that is bigger right? And a related question since cycy brought it up, does the variable font include all the sub-pixel hinting for cleartype/etc?

**Comment by jamescowens** [comment]
We could play around with that in another PR...

**Comment by cyrossignol** [comment]
Inter's variable fonts do not have the hints. 

But honestly, after staring at the hinted text for a day, something subtle about the way they're rasterized makes me **_really_** hate them. Can't put my finger on it. Might have something to do with the forced `10pt` size across the board. 

So I'm all for swapping out the constant font files for the variable font. @opsinphark You want to do that? Should cut down the size of the final binary.

**Comment by opsinphark** [comment]
I can start a new PR for moving to the the variable font.  Might take some playing around with to find the font right size that displays well in both normal and scaled aspects.

**Comment by opsinphark** [comment]
I've created a new PR for this, please checkout https://github.com/gridcoin-community/Gridcoin-Research/pull/1926

**Pull request merged**
