### PR TITLE
script: Setup Improvements

### LINKED ISSUE #1893: [Windows] Automatically set the install path in setup to where the wallet is currently installed.
Currently the setup always uses the default C:\Program Files... folder when you run it regardless of whether you've already installed it to another location. 

This contrasts with other programs where when you already have it installed and run the setup it would automatically change the install path to the current location of the program.

### PR DESCRIPTION
**Pull request by nathanielcwm**
Main purpose of this was to make the setup read the existing install location from the registry.

I also resized some of the bitmaps which makes them look better for example:
5.0.1|This PR
-|-
image|image1

### CODE REVIEW

**Comment by nathanielcwm** [comment]
Not entirely sure how to make the installer. With makensis it doesn't seem to create it properly.

**Comment by jamescowens** [comment]
make deploy

**Comment by nathanielcwm** [comment]
I believe it doesn't work for the 32 bit setup.

**Comment by jamescowens** [comment]
I will check today.

**Comment by nathanielcwm** [comment]
Also we should probably have an image for the welcome page right?

The generic nsis one doesn't look very nice but i can't find anything in gridcoin-marketing that seems to be in the right style.

Here's some examples:
image
image
image

**Comment by nathanielcwm** [comment]
5.0.1:
image
This Branch:
image

I feel like having some more space beneath the logo would make it look nicer though.

**Comment by nathanielcwm** [comment]
Looks like b852566 broke some stuff that didn't break on my machine lol

**Comment by jamescowens** [comment]
I am testing this now.

**Review by jamescowens — APPROVED** [review]
Tested on both 64-bit and 32-bit Windows and works well.

**Pull request merged**
