### PR TITLE
GUI: Fix Column Widths in RPC Console.  Elide long strings in their center.  Indent user agent.

### LINKED ISSUE #2222: GUI: Columns in Peers tab not wide enough
# Bug Report

**Current behavior**
Columns in Peers tab not wide enough to display the information they contain.

**Expected behavior**

All information visible.

**Steps to reproduce:**

Install wallet on MacOS. Columns to narrow both on Mainnet and Testnet versions.

**Screenshots**

 
Screenshot 2021-07-12 at 18 36 24

**Gridcoin version**

**Machine specs**
- OS: MacOS
- CPU: M1 arm
- RAM: 16GB
- Disk size: 512 GB
- Disk Type (HD/SDD): SSD

**Extra information**

### PR DESCRIPTION
**Pull request by barton2526**
Closes #2222 

This reverts some of the changes introduced in #1566 to make the columns wide enough for their data.  This should be tested on displays of various resolutions.

Implements https://github.com/bitcoin-core/gui/pull/276 to put an ellipsis in the middle of long peer addresses.

Before:
before

After:
image

I am aware the spacing at the start of the User Agent is not ideal.  The solution is unfortunately very complex.  I posted a snippet on Slack of how upstream handles it, but it's overly complicated for what it does IMO.

### CODE REVIEW

**Comment by barton2526** [comment]
Another option: left align the sent and received columns

**Comment by jamescowens** [comment]
This is the current Bitcoin Core client... (with the address column scrunched to show ellipses...)
image

**Comment by jamescowens** [comment]
I am perfectly fine with the PR as it is. Undoing my scaling work in #1566 is goog, since that should have been undone when @cyrossignol implemented the application-wide scaling work a while back.

**Review by jamescowens — APPROVED** [review]
ACK

**Pull request merged**
