### PR TITLE
build, crypto, script: remove most of OpenSSL usage

### LINKED ISSUE #2702: OpenSSL 1.1.1 has reached EOL
[OpenSSL 1.1.1 has reached EOL](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/) and last time I've looked, we had a lot of warnings when compiling with OpenSSL 3.x. We should look into that and update the version in depends.

IIRC we only use MD5 functionality of OpenSSL directly. It might make sense to just drop it for outside of curl on depends.

### PR DESCRIPTION
**Pull request by div72**
Removes all non-trivial usages of OpenSSL except in `src/crypter.*`.

### CODE REVIEW

**Comment by jamescowens** [comment]
I like where this is going. On the disallowed ops, is this technically a mandatory to deprecate script code? How do we know those op codes are not in use?

**Comment by div72** [comment]
The disallowed ops are unconditionally rejected here, so all nodes already reject scripts with any of them present at any block height already:

https://github.com/gridcoin-community/Gridcoin-Research/blob/7548e6cfda604264e412de55a6a24c20bd0e075b/src/script.cpp#L364-L379

The main issue with this PR currently is that the CBigNum -> arith_uint256 changes to staking calculations break sync for PoS blocks at some point. I thought everything was limited to 2^256 but I'll re-check to see what broke.

**Review by jamescowens — COMMENTED** [review]
Hmm... how did this work before? I don't think we used 300+ bit integers in the original implementation...

**Comment by div72** [comment]
> Hmm... how did this work before? I don't think we used 300+ bit integers in the original implementation...

@jamescowens Pre f7c13bed581200d3908615fa0b5cbb7a4da526fd, CBigNum which used OpenSSL's unbounded BIGNUM was used.

**Comment by jamescowens** [comment]
Ah yes...

**Comment by jamescowens** [comment]
Hmm...

`
Build Options:
  with external callbacks = no
  with benchmarks         = yes
  with tests              = yes
  with ctime tests        = yes
  with coverage           = no
  with examples           = no
  module ecdh             = no
  module recovery         = yes
  module extrakeys        = yes
  module schnorrsig       = yes

  asm                     = x86_64
  ecmult window size      = 15
  ecmult gen prec. bits   = 4

  valgrind                = yes
  CC                      = gcc-12
  CPPFLAGS                =  
  SECP_CFLAGS             = -O2  -std=c89 -pedantic -Wno-long-long -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-overlength-strings -Wall -Wno-unused-function -Wextra -Wcast-align -Wcast-align=strict -fvisibility=hidden 
  CFLAGS                  = -g -O2
  LDFLAGS                 = 
Fixing libtool for -rpath problems.

Options used to compile and link:
  with wallet   = yes
  with gui / qt = yes
    with qr     = yes
  with zmq      = 
  with test     = yes
  with bench    = yes
  with upnp     = yes
  debug enabled = no
  werror        = no

  target os     = linux
  build os      = 

  CC            = /usr/bin/ccache gcc-12
  CFLAGS        = -g -O2
  CPPFLAGS      =  -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -DQT_GUI -DUSE_QRCODE
  CXX           = /usr/bin/ccache g++-12 -std=c++17
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wformat-security -Wvla -Wdate-time -Wduplicated-branches -Wduplicated-cond -Wlogical-op -Woverloaded-virtual -Wimplicit-fallthrough -Wno-unused-parameter -Wno-implicit-fallthrough -Wno-deprecated-copy
  LDFLAGS       = 
  AS            = gcc-12
  ASFLAGS       = -g -O2
`

  CXX      test/test_test_gridcoin-serialize_tests.o
  CXX      test/test_test_gridcoin-sigopcount_tests.o
  CXX      test/test_test_gridcoin-sync_tests.o
  CXX      test/test_test_gridcoin-test_gridcoin.o
  CXX      test/test_test_gridcoin-transaction_tests.o
  CXX      test/test_test_gridcoin-uint256_tests.o
  CXX      test/test_test_gridcoin-wallet_tests.o
  CXX      test/test_test_gridcoin-util_tests.o
test/gridcoin/project_tests.cpp:20:15: warning: ‘GRC::Contract {anonymous}::contract(std::string, std::string)’ defined but not used [-Wunused-function]
   20 | GRC::Contract contract(std::string key, std::string value)
      |               ^~~~~~~~
  CCLD     libsecp256k1_precomputed.la
  CCLD     libsecp256k1.la
make[3]: Leaving directory '/home/jco/builds/Gridcoin-Research/src/secp256k1'
  CXXLD    gridcoinresearchd
  CXXLD    test/test_gridcoin
  AR       qt/libgridcoinqt.a
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: crypto/libgridcoin_crypto_base.a(crypto_libgridcoin_crypto_base_a-md5.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:4435: gridcoinresearchd] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/jco/builds/Gridcoin-Research/src'
make[1]: *** [Makefile:12371: all-recursive] Error 1
make[1]: Leaving directory '/home/jco/builds/Gridcoin-Research/src'
make: *** [Makefile:785: all-recursive] Error 1
jco@jco-monster-ng:~/builds/Gridcoin-Research>

**Comment by jamescowens** [comment]
Looks like the c source file for md5 is not being compiled with PIE flag.

**Comment by jamescowens** [comment]
I have successfully synced from zero on testnet. The CPID detection is broken with a researcher node. With this PR coming up as investor. This probably has something to do with the MD5. Need to track that down.

**Comment by jamescowens** [comment]
Also successfully synced from zero on mainnet.

**Comment by jamescowens** [comment]
Confirmed the Cpid::Hash is not working correctly.

Current testnet branch...
2023-10-23T19:58:10Z Loading BOINC CPIDs...
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23
2023-10-23T19:58:10Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = bc0621a4ac4610ffa400a0d298c02e23


This PR:
2023-10-23T20:02:21Z Loading BOINC CPIDs...
2023-10-23T20:02:21Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = b00000002a000000ec000000e8000000
2023-10-23T20:02:21Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = b00000002a000000ec000000e8000000
2023-10-23T20:02:21Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = b00000002a000000ec000000e8000000
2023-10-23T20:02:21Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = b00000002a000000ec000000e8000000
2023-10-23T20:02:21Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = b00000002a000000ec000000e8000000
2023-10-23T20:02:21Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = b00000002a000000ec000000e8000000
2023-10-23T20:02:21Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = b00000002a000000ec000000e8000000
2023-10-23T20:02:21Z INFO: Hash: internal = fa89b5db83c284b90f57a1fb65a137b5, email = ***, cpid = b00000002a000000ec000000e8000000

**Review by jamescowens — APPROVED** [review]
tACK

**Pull request merged**
