### PR TITLE
update dev version to 3.7.11.2

### PR DESCRIPTION
**Pull request by caraka**
For fresh testnet builds with rpc changes

### CODE REVIEW

**Review by tomasbrod — APPROVED** [review]

**Comment by denravonska** [comment]
We need to figure out a better way to manage the versions in the development branch. If we build a staging build we have to update the version number in both branches. Maybe the dev branch should only be a commit hash as its series is not determined yet.

**Comment by tomasbrod** [comment]
Agreed. While using versionnumbers in master and staging branches is ok, this is difficult. Version should update on each merge to staging, with automatic script perhaps, but the development should not need to. Ideal would be to get the version from git.

**Comment by jamescowens** [comment]
Does the last number have to be a number? Why don't we use x.y.z.<last commit> where x.y.z comes from configure.ac and can be set to the desired series, but the last digit is the first seven digits of the last branch commit number...

git log -1 --pretty=format:"%H"

So at the time of this message, development would be 3.7.11.3cc7ae3

**Comment by tomasbrod** [comment]
@jamescowens Build environment that is used to build deb packages can not use git. Either it takes tarball of the repo (without `.git`), so the hash is not available, or it reluctantly takes the git repo, but does a local commit on it, so the hash is completely unrelated.

**Comment by caraka** [comment]
@tomasbrod has stated the challenge as succinctly as I have ever heard it. Debian's anal way of doing things is one of the ways they build trust between devs > maintainers > users. Every alteration is transparent, which breaks our lovely appended hash.

**Review by tomasbrod — CHANGES_REQUESTED** [review]
the version was changed

**Review by tomasbrod — CHANGES_REQUESTED** [review]
is at 3.7.11.3 already

**Pull request closed without merging**
