### PR TITLE
build: CMake: Initial Windows support (MSYS2)

### PR DESCRIPTION
**Pull request by CyberTailor**
This PR is a follow-up to #2676. The following changes make it possible to build Gridcoin with CMake in Windows.

It also adds the [Hunter](https://hunter.readthedocs.io/en/latest/) dependency manager for systems without package management abilities.

TODO for next pull requests:
- [ ] Add NSIS integration to CMake
- [ ] Make the code compile with MSVC

### CODE REVIEW

**Comment by jamescowens** [comment]
I just merged https://github.com/gridcoin-community/Gridcoin-Research/pull/2734. You probably need to rebase this on the development branch again.

**Comment by div72** [comment]
@CyberTailor Why hunter, instead of (for example) conan?

P.S. MacOS CI failure is unrelated, seems like a GH issue.

**Comment by CyberTailor** [comment]
> Why hunter, instead of (for example) conan?

I'm not familiar with Conan and don't know any projects that use it with CMake.

**Comment by CyberTailor** [comment]
This software is abandoned, use ttyd instead

**Comment by CyberTailor** [comment]
(sorry for confusion, i've mistook browser tabs)

**Comment by jamescowens** [comment]
@CyberTailor can we get this into Miss Piggy or should I push to Natasha?

**Comment by CyberTailor** [comment]
I think yes. It'd be hard to continue without feedback

**Comment by jamescowens** [comment]
@div72?

**Comment by div72** [comment]
I did take a peek at this PR, nothing popped out to me but I haven't used CMake before and I'm not a Windows user so I don't really think I'm qualified to give a proper review. There does seem to be something weird on how defines are processed (also on MacOS) but it seems to compile and run ok.

---

Since automake is currently our sanctioned build system, it shouldn't matter if this lands in Miss Piggy or Natasha imo as long as there are no code changes.

**Comment by jamescowens** [comment]
I am not qualified to review it either. If it seems to compile and run ok, lets go ahead and merge it.

**Pull request merged**
