### PR TITLE
trivial: Unbreak build with Boost 1.72.0

### PR DESCRIPTION
**Pull request by barton2526**
Ref: https://github.com/bitcoin/bitcoin/pull/17654

### CODE REVIEW

**Comment by jamescowens** [comment]
@div72 we should check to see if we are using any deprecated features. Do we really care about 1.72 anyway?

**Comment by barton2526** [comment]
#2231 removes (hopefully all) deprecated features below 1.58

**Comment by denravonska** [comment]
If there are no build requirements for <1.58 (@caraka ?) I'm utACK:ing this.

**Comment by div72** [comment]
@denravonska Minimum required boost was bumped to 1.58 in #2194.

**Comment by div72** [comment]
@barton2526 I don't think referencing a PR in a commit is a good idea, that might cause everyone who forks after this to cause a notification in the bitcoin PR.

**Comment by caraka** [comment]
> If there are no build requirements for <1.58 (@caraka ?) I'm utACK:ing this.

All my debian derivative build deps have been => boost 1.58 since trusty went EOL, so I am more than happy with this - it's already my default.

**Review by jamescowens — APPROVED** [review]
utACK

**Pull request merged**
