### PR TITLE
rpc: Remove deprecated RPC commands

### PR DESCRIPTION
**Pull request by jamescowens**

### CODE REVIEW

**Comment by RoboticMind** [comment]
I still see users occasionally ask about the `list` and `execute` commands (usually looking at really old guides), so I don't know if we want to remove the warnings for them

**Comment by jamescowens** [comment]
I do. They can get the command not found error and they will figure it out. These have been deprecated for more than two years. Time to move on.

**Comment by Pythonix** [comment]
@jamescowens You might want to update the list of deprecated rpcs for the autocomplete function as well (https://github.com/gridcoin-community/Gridcoin-Research/blob/development/src/rpc/server.cpp#L447-L460)

**Comment by jamescowens** [comment]
Ah yes. Thanks for the reminder on that...

**Review by cyrossignol — APPROVED** [review]
Heh, I removed the `execute` and `list` RPCs in the past too, but I noticed that there is a lot of old documentation that still refers to them, so I didn't see any harm leaving those in. Might as well clean them up at this point.

**Pull request merged**
