### PR TITLE
gui: Update Qt Linguist localization files

### LINKED ISSUE #2062: Typo - console [archivelog]. Change 'valus' to 'values'
Typo - the word value

### PR DESCRIPTION
**Pull request by cyrossignol**
Been a while since we did this housekeeping. This fixes a few wording/formatting issues with display strings and regenerates the Qt Linguist translation units to prepare for Transifex integration.

Closes #2062.

### CODE REVIEW

**Comment by cyrossignol** [comment]
Putting into draft mode. A contributor worked on a particular language that we may want to merge before blasting the repo with conflicts.

**Comment by DjMVeiga** [comment]
Hello cyrossignol.
2 years passed since my last translation on Gridcoin and ive tried to commit a change today but im a noob on Github.
Im a BOINC translator for more than 7 years and im used to transifex. Will need to explore github system.
Ive not finished the translation since you've said youre going to do some changes to the files. Can you warn about when that is done so i can finish my translation correctly and 100% well done.

Thanks
Miguel

**Comment by jamescowens** [comment]
@DjMVeiga Hey. @cyrossignol hooked up the Transifex integration to the repo today...
https://github.com/gridcoin-community/Gridcoin-Research/settings/installations

**Comment by DjMVeiga** [comment]
> 
> 
> @DjMVeiga Hey. @cyrossignol hooked up the Transifex integration to the repo today...
> https://github.com/gridcoin-community/Gridcoin-Research/settings/installations

Amazing. Im more an app translator than a developer. Would be amazing if the changes ive did today  can be already commited so i dont need to done it again. Thanks

**Comment by DjMVeiga** [comment]
Will wait that i can do it directly on transifex or will study more the github system

**Comment by cyrossignol** [comment]
@DjMVeiga This looks like excellent work. I'm impressed by your commitment to update the XML files directly! Of course, I don't speak Portuguese, so I cannot review your changes, but I pulled your commit into my branch, and I made some small tweaks to fix some XML syntax issues. It will merge with this pull request. 

When this finishes, translators can begin to contribute to the [Gridcoin project on Transifex](https://www.transifex.com/gridcoin/gridcoin/).

**Comment by DjMVeiga** [comment]
Thanks cyrossignol. I'm used to do apps translations, so i love to do that.
However ,theres been 2 years since the initial translations when Gridcoin was still a child and many changes happened so far.
I understand the xml code, so thats not a problem at all. My problem was with the github system. In the beggining in my first translations, Gridcoin was not even on Github i think. All i did was directly in contact with IRC users.
Anway , if you're going to start using Transifex, that will be amazing as Transifex is a specialized system for that and more user friendly for translators. Githuh is more for developers and as i told before, i do translations as an hobbie and not a developer. I work as a Systems Administrator but i really like to do App translations.

Best regards and whatever i can do to help Gridcoin grow, you can alway count on me

**Comment by cyrossignol** [comment]
@DjMVeiga I agree&mdash;GitHub is not a very good tool to manage translations with. Transifex looks much better, and I've been meaning to set it up for a while. Your message in IRC reminded me to look at it again. I'm new to this platform, though, so I hope you can offer advice as we set up the project.

I accepted your request to join as a translator. Please wait for this pull request to merge before submitting changes. Thanks for the contributions!

**Review by jamescowens — APPROVED** [review]
Wow!

**Comment by DjMVeiga** [comment]
> 
> 
> @DjMVeiga I agree—GitHub is not a very good tool to manage translations with. Transifex looks much better, and I've been meaning to set it up for a while. Your message in IRC reminded me to look at it again. I'm new to this platform, though, so I hope you can offer advice as we set up the project.
> 
> I accepted your request to join as a translator. Please wait for this pull request to merge before submitting changes. Thanks for the contributions!

Thanks, will do the translation as soon as the files are ready.
Other thing, dont add me as Brasilian Translator. Portuguese from Portuguese and Brasil are tottaly different in the way certain words and sentences are written. Both are Portuguese but still very different. We both understand from each other but i cannot translate into Portuguese from Portugal as im Native from Portugal.

Best regards

**Comment by DjMVeiga** [comment]
> 
> 
> @DjMVeiga I agree—GitHub is not a very good tool to manage translations with. Transifex looks much better, and I've been meaning to set it up for a while. Your message in IRC reminded me to look at it again. I'm new to this platform, though, so I hope you can offer advice as we set up the project.
> 
> I accepted your request to join as a translator. Please wait for this pull request to merge before submitting changes. Thanks for the contributions!

Also, you can add give me permissions also to review, as in transifex you can have the privileges to translate but also to review.
So after someone translate, theres should be someone to review  the file. Otherwise the file is not considered as complete. If you agree as for now theres not anyone else to translate Portuguese (Portugal), ill translate and review all the content. I'm also a translator and reviewer in BOINC, so im used to that.
Also theres a good way to check what i've reviewed, as the project is new so its 100% not reviewed. That way i will recheck everything and not only what is not translated.

So when you can please do that changes: remove me as Portuguese (Brasil) translator and give me the translator and reviewer permissions to Portuguese (Portugal)

**Comment by cyrossignol** [comment]
@DjMVeiga Thanks for the tips. I made the changes that you suggested.

**Comment by DjMVeiga** [comment]
> 
> 
> @DjMVeiga Thanks for the tips. I made the changes that you suggested.


Hi again. 
You add me as a reviewer but removed me as translator. I have to have both permissions.
Can you fix it please? Thanks

**Comment by cyrossignol** [comment]
@DjMVeiga Sorry about that. When I assigned the "reviewer" role to you, Transifex automatically removed your "translator" role. According to the Transifex documentation, though, a reviewer can work on translations as well. Is that not true?

I invited you you to the translator role again. Please let me know if that fixes the issue.

**Comment by DjMVeiga** [comment]
> 
> 
> @DjMVeiga Sorry about that. When I assigned the "reviewer" role to you, Transifex automatically removed your "translator" role. According to the Transifex documentation, though, a reviewer can work on translations as well. Is that not true?
> 
> I invited you you to the translator role again. Please let me know if that fixes the issue.


All working now.
Thanks a lot

Will finish it this weekend

**Comment by DjMVeiga** [comment]
Translation done. 
Well 95% but it can be considered 100%
Is there a way to appl the locale file on installed gridcoin on my machine so i can test several phrases to check if theyre ok considering the context. Can't file where the local files are installed on local disk

**Comment by iFoggz** [comment]
Everything is compiled into the application at compile time.

**Comment by DjMVeiga** [comment]
> 
> 
> Everything is compiled into the application at compile time.

is there a way to get a compiled version with language PT_pt already applied with the changes done on transifex?

**Comment by iFoggz** [comment]
I personally know nothing about transifex so cy would have to comment on that

**Comment by DjMVeiga** [comment]
> 
> 
> @DjMVeiga Sorry about that. When I assigned the "reviewer" role to you, Transifex automatically removed your "translator" role. According to the Transifex documentation, though, a reviewer can work on translations as well. Is that not true?
> 
> I invited you you to the translator role again. Please let me know if that fixes the issue.

Know that ive done 95% of my translation, is there a way to have a compiled version of Gridcoin with the tanslation already there, so i can fix eventual words or phrases out of context. Some work has to be done directly on the app, checking the tranlsation applied

**Comment by jamescowens** [comment]
Yes. I can give you a build based on the PR. What platform do you use?

**Comment by DjMVeiga** [comment]
> 
> 
> Yes. I can give you a build based on the PR. What platform do you use?

Windows 10  - 64bits

**Pull request merged**
