### PR TITLE
Fix invalid example Gridcoin address

### PR DESCRIPTION
**Pull request by jamescowens**
Address issue #1238.

### CODE REVIEW

**Comment by barton2526** [comment]
Suggestion: Can the example address be one that exists on an explorer already?  Perhaps the Foundation wallet?

**Comment by barton2526** [comment]
In that case why supply an example at all?

**Comment by jamescowens** [comment]
I don’t want to turn what should be a minor change into a long discussion Barton. The new address example is a valid address as opposed to the original which was not.

We have too much to do to waste time on minor things like this.

**Comment by barton2526** [comment]
My concern is that users could take issue with the "default address" being
one under dev control.  I understand that you destroyed the key, but given
there is no way to prove that I don't think it's a good idea to allow
conspiracy theories to get started.

We should just set the default to the foundation address and be done with
it.  I'd also be interested to here over dev opinions on this issue.
@ravonn?

**Comment by tomasbrod** [comment]
What about OP_RETURN burn address?
Personally, I am for transparency. Foundation address will mean the least amount of speculation.

**Comment by jamescowens** [comment]
Paste the address you want and I will make the change.

**Comment by denravonska** [comment]
This one? https://gridcoinstats.eu/address/S67nL4vELWwdDVzjgtEP4MxryarTZ9a8GB

**Comment by jamescowens** [comment]
Ok. Changed it to S67nL4vELWwdDVzjgtEP4MxryarTZ9a8GB, which is the default burn address.

**Review by denravonska — APPROVED** [review]
I could have sworn I approved it already.

**Comment by jamescowens** [comment]
We need two approvals right?

**Comment by denravonska** [comment]
Correct. It's not set in stone but we're striving for it.

**Comment by jamescowens** [comment]
Tomas please take a quick look at this and approve if you are ok. We want to get this merged for Camilla.

**Comment by jamescowens** [comment]
This is trivial. I am not waiting any longer...

**Pull request merged**
