### PR TITLE
refactor: use include guards instead of #pragma once

### PR DESCRIPTION
**Pull request by div72**
Also modifies the linter to allow `GRIDCOIN_` prefix for include guards to ease detection of gridcoin specific files by machinery.

Also modifies the linter to allow just `GRIDCOIN_` prefix for src/gridcoin, so that we don't need include guards like `GRIDCOIN_GRIDCOIN_SCRAPER_SCRAPER_H`.

### CODE REVIEW

**Comment by jamescowens** [comment]
Alright. We will merge this one first, and then I want to merge #2315 after rebasing ont he development branch post merge of this.

**Review by jamescowens — APPROVED** [review]
ACK, CI testing sufficient for this. No errors in the include guard section of the Linter.

**Comment by denravonska** [comment]
I prefer `#pragma once` over include guards:( Did the linter complain?

**Comment by div72** [comment]
@denravonska Please see the discussion after https://github.com/gridcoin-community/Gridcoin-Research/pull/2315#issuecomment-918180953.

**Pull request merged**
