### PR TITLE
Removed FAQ from Wallet

### LINKED ISSUE #1022: Update/Remove The FAQ In the Wallet
Under the advanced tab, there is a section labeled FAQ. The FAQ section's UI is unintuitive, and it makes it hard to tell what you are supposed to use it for. If we keep this system the user interface needs an overhaul.

### PR DESCRIPTION
**Pull request by Lenni**
Fixes #1022

### CODE REVIEW

**Comment by RoboticMind** [comment]
This should also fix https://github.com/gridcoin/Gridcoin-Research/issues/453, correct?

**Review by sedited — COMMENTED** [review]
Please rebase the commit unto the dev branch and open the pr to the development branch.
The action should not just be commented out, but removed entirely, or replaced by a simple link to an explanatory website. The code leading up to it should be removed as well, including the connect call, QAction object, and icon and settings passing.

**Comment by Lenni** [comment]
I currently have the Problem, that i cant compile the Gridcoin Wallet on the dev branch, because QT Maker says the clientversion.h is missing. So I cant test my Patch :/

**Comment by sedited** [comment]
The project moved to autotools as a build system, you need to configure it in Qt Creator as such. Follow the instructions here: http://doc.qt.io/qtcreator/creator-projects-autotools.html

**Comment by Lenni** [comment]
@TheCharlatan I configured it, but now it can't find the QT Headers, when I try to compile the Wallet. The gridcoinresearchd can be compiled though...

**Comment by denravonska** [comment]
You can remove the action and the `faqClicked` method.

**Comment by Lenni** [comment]
Sorry, my local branch was a mess. I sorted it out now, ans will create a new pull request as soon as the Travis CI Build passed :D

**Pull request closed without merging**
