### PR TITLE
Qt: Don't allow to open the debug window during splashscreen & verification state

### PR DESCRIPTION
**Pull request by barton2526**
Ref: https://github.com/bitcoin/bitcoin/pull/8042

This fixes a bug on MacOS reported in Discord.

Note this needs to be tested on MacOS.

### CODE REVIEW

**Comment by jamescowens** [comment]
Given that I was already mucking around with similar stuff for the snapshot download, this doesn't give any more regression risk than that and is easy to test. Changing milestone to Ingrid.

**Comment by jamescowens** [comment]
@sweede-se Can you test this one too?

**Review by jamescowens — APPROVED** [review]
utACK. Asking @sweede-se to test.

**Comment by ghost** [comment]
Works for the Debug window. Maybe also implement for the Diagnostics? Made it crash by opening that but having trouble  replicate it.

(What do utACK stand for? Have seen it here before but do not understand what it means.)

**Comment by jamescowens** [comment]
Untested acknowledged.

**Comment by jamescowens** [comment]
@barton2526 per our discussion on Slack, I think we should extend this to include all of the actions starting at 856 and going through 870 in bitcoingui.cpp, except toggleHideAction and quitAction.

**Comment by ghost** [comment]
Works as intended on MacOS.

**Review by jamescowens — APPROVED** [review]
ACK

**Pull request merged**
