### PR TITLE
Switch to Tinyformat

### LINKED ISSUE #440: Switch to tinyformat
Use bitcoin's tinyformat commit to remove a lot of warnings and workarounds: https://github.com/bitcoin/bitcoin/pull/3549

### PR DESCRIPTION
**Pull request by sedited**
This pr was inspired by laanwj's bitcoin/bitcoin#3549 and should close #440 . The initial commit from printf -> LogPrintf can be found [here](https://github.com/laanwj/bitcoin/commit/881a85a22d76c875f519cd54388a419ec6f70857#diff-b7702a084eb00fb47f9800fd68271951L1003).

In it's current state (especially regarding commit order) it is a mess. Should I squash it into a single commit, or keep multiple commits that attempt to show the order of changes done?

The most important changes happen in util.cpp / util.h .

### CODE REVIEW

**Comment by tomasbrod** [comment]
* squashing is not necessary, I prefer separate commits
* the commits should have proper authorship attached,
   - wasn't it possible to do interactive rebase?

**Comment by sedited** [comment]
Could have applied singular patches from bitcoin's git, but that would have been a large amount of work, since line numbers are completely different and we have a lot of new stuff that is being logged. I'll try to figure out how to attach the authorship properly. It's a bit hard, since multiple commits do different things, e.g. LogPrintf -> LogPrint("class",...) -> allow std::string to be logged, on the same line. Obviously I do not want to do the same work 3 times over.

**Comment by sedited** [comment]
Ok, much nicer now. I included the original commit message for each and then added the fixes I had to apply as a single last commit.

**Comment by denravonska** [comment]
I think we can remove the `\r\n` from all the calls now.

**Comment by sedited** [comment]
Just the carriage return, or also the newline?

**Pull request merged**
