### PR TITLE
gui, researcher: Add GDPR protection display

### LINKED ISSUE #2437: Wallet should warn users when crunching on GDPR-protected project
# Feature Request

**Describe the Feature Request**
Wallet should warn solo crunchers if they are attached to a project which requires GDPR export and direct them to a page with information on how to do so, as many users do not seem to know they need to do this.

### PR DESCRIPTION
**Pull request by jamescowens**
This PR adds the status of GDPR protection to the projects table in the GUI. It requires a mandatory because it changes the version of the Project contract to accommodate the m_gdpr_controls boolean. On testnet this will be a separate mandatory from the MRC mandatory that already happened that will coincide with the Poll v3 mandatory coming up. This will be coordinated (at the same height) with the MRC mandatory for Kermit's Mom on the production release. Closes #2437.

### CODE REVIEW

**Comment by jamescowens** [comment]
I am currently testing this on the four node fork I am running to test poll v3 stuff.

**Comment by jamescowens** [comment]
Here is a screenshot of the projects table. Note that I currently have not included the logic for the project to be attached to trigger the warning triangle to show, because I only have one project attached on my four node fork, and it is not a gdpr enabled project.
image

**Comment by RoboticMind** [comment]
Will the warning triangle only show if you have not enabled stats exports? If it always shows, I would recommend making them orange or yellow instead of red since red usually indicates problems rather than potential problems

**Comment by jamescowens** [comment]
The scrapers can’t tell whether you have enabled it directly, but if your RAC is zero, then this would show. In general if your stats exports are inhibited then you will not have an entry in the user stats export and your RAC will total to zero, so it is a good proxy. I have to add the logic to suppress the triangle if the boinc on the wallet instance is not attached.

**Comment by jamescowens** [comment]
With that logic added, there would be "trues", but none of the above would show triangles, because the boinc instance on the wallet machine is not attached to any of the GDPR protected projects.

**Comment by jamescowens** [comment]
Ok here is a screenshot with the above logic added.
image

**Comment by jamescowens** [comment]
Notice it only shows the triangle if the project is "eligible" and has gdpr controls, and also has zero magnitude, which is the highest probability situation for the gdpr export not enabled on that project. This is good enough for now. Later I will decide on flowing this through to the summary screen and main screen as a possible action needed state.

**Comment by jamescowens** [comment]
@div72 and I agreed in the interest of time I would be merging this PR without review as well. It has been tested in my four node testnet fork.

**Comment by iFoggz** [comment]
I agree this is the way to go for this since there is no direct connection to determine if the project has GDPR enabled.

Don't mind the migraine question (difficult reading code with it) but:

We pull the RAC from the superblock or scrapers correct? or that from boinc?

Was wondering if it would be a good idea for the warning like a tool tip or something that stats once they have resolved the GDPR issue it could take some time until that condition is corrected?

probably not thinking right but was my only question

**Comment by jamescowens** [comment]
IF the project is whitelisted, we pull the RAC from the scraper convergence map, which is essentially a superset of the superblock data. I think we should decide what we want to do in the bubbled up message to the project summary screen and the main screen. We don't have to wait on this for right now though. This part we need to merge now because it is a mandatory change that I want to coordinate with the poll v3.

**Comment by iFoggz** [comment]
absolutely. thank you for the comment

**Pull request merged**
