### PR TITLE
refactor: Rename "neural network" project-wide

### LINKED ISSUE #1732: Change the Name of the Neuralnetwork
The name neuralnetwork is very confusing since it sounds like it is using artificial intelligence. The name should be changed to something that explains what it actually does. 
Proposed alternatives:
* Stats Database
* Credit Checker 
* Stats Maintainer
* Research Verifier
* Scraper Stats
* Scraper/Stats Auditor 

Open to other suggestions

### PR DESCRIPTION
**Pull request by cyrossignol**
This renames the `neuralnet` directory to `gridcoin`, the `NN` namespace to `GRC`, and any references to a neural network with a suitable alternative. I left some items with historical significance alone (mostly comments and to-be-removed code). 

I chose `gridcoin` and `GRC` instead of more specific names because we will reorganize some code to prepare for Bitcoin upgrades soon. This structure seems to be working well.

### CODE REVIEW

**Comment by div72** [comment]
Could the scraper also be moved to `src/gridcoin`?

**Comment by jamescowens** [comment]
Lets move the scraper to gridcoin/scraper/ *. We should also move scraper_net. * into the gridcoin/scraper/ subdirectory.

**Review by jamescowens — COMMENTED** [review]
Looks good. See my comment about moving the scraper and scraper_net files...

**Comment by cyrossignol** [comment]
I have a broader set of changes queued that include moving the scraper files. This PR just focuses on the "neural network" term.

**Comment by jamescowens** [comment]
Lets rebase to clear the conflicts. I would like to get this merged while PR's at an ebb given how many files this touches.

**Pull request merged**
