### PR TITLE
[DEPENDS] VERSION UPDATES+ARMV7I SUPPORT+REMOVE CCACHE

### PR DESCRIPTION
**Pull request by ghost**
### This updates the DEPENDS folder with a port from Bitcoin that includes:

1. Version updates.

2. Support of armv7l builds from [/depends].
 ref: https://github.com/bitcoin/bitcoin/commit/ac91ea64c2b1daec8fee0bfde443c18cf87595ae

3. Update to remove ccache.
Allows removal of ccache altogether from depends. Which cross-compiling for windows on linux was giving a problem with Travis.
ref: bitcoin/bitcoin@29fad97

Note: This replaces pull requests #970, #971, and #1013.

### CODE REVIEW

**Comment by tomasbrod** [comment]
git commit has an author option, i am sory for nitpicking. Author option only supports one. PR comments do not make it into the repo. If intention is to give credit, use the author option or alternatively, the commit message (3rd+ line, 2nd should be empty).

**Comment by ghost** [comment]
Thank you for your suggestion tomasbrod. I have amended my last commit to include Co-authors as you have suggested.

**Comment by denravonska** [comment]
What is the issue with ccache? If we could fix the problem it would be neat as it substantially speeds up compilations.

**Comment by ghost** [comment]
Bitcoin chose to delete ccache instead of fixing it. Because cross-compiling for windows on linux was giving a problem with Travis. I believe this was an issue for us a while back yes?

**Comment by sedited** [comment]
The commit message still reads the same content. Split up the changes into the separate commits you are pulling from bitcoin, then amend the appropriate author to each commit. 
@denravonska ccache now just uses whatever is natively available on the system. 

Edit: Your commit also contains some changes to the translation. I don't think that is intended.

**Comment by ghost** [comment]
I'll submit these as separate commits then.

**Pull request closed without merging**
