### PR TITLE
given netsoft link results in: forbidden + http 404

### PR DESCRIPTION
**Pull request by Erkan-Yilmaz**
The command "list cpids" gives this url (1) for the value "CPID Link", but that link gives me: forbidden + 404, see (2).

The current, working link in my browser is: (3).

Thus: replaced the link at 2 places in the code.

(1) 
http://boinc.netsoft-online.com/get_user.php?cpid=myCPIDvalue

(2) 
Forbidden
You don't have permission to access /get_user.php on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

(3) http://boinc.netsoft-online.com/e107_plugins/boinc/get_user.php?cpid=myCPIDvalue

### CODE REVIEW

**Comment by Erkan-Yilmaz** [comment]
what a strange behaviour of git: 

I just changed 2 LOC, but it thinks: 
"466 additions, 407 deletions not shown because the diff is too large."

**Comment by gridcoin** [comment]
Hi Erkan,

That is a nice idea.  Netsoft banned the public use of reading the XML rac a while back, due to massive abuse.  So in all of the code that gathers credits we now use the Neural Network.
However, the list cpids command still has the old value in for convenience (which as you point out does not work).

Since I run a project (which I have moved to the cloud) my house IP is still un-banned by netsoft (just as a courtesy to help me look at credits).

When I test this URL it works:
http://boinc.netsoft-online.com/e107_plugins/boinc/get_user.php?cpid=784afb35d92503160125feb183157378

Could you please tell me if you can view the results from your IP?

If so, then I will just manually merge your change in since github somehow is pulling too many changes.

Thanks!
Rob

**Comment by Erkan-Yilmaz** [comment]
yes, that works for me also

> When I test this URL it works:
> http://boinc.netsoft-online.com/e107_plugins/boinc/get_user.php?cpid=784afb35d92503160125feb183157378
> 
> Could you please tell me if you can view the results from your IP?

**Comment by gridcoin** [comment]
Got the change in the code, thanks a lot.

**Pull request closed without merging**
