### PR TITLE
Image Compression Roundup

### PR DESCRIPTION
**Pull request by Peppernrino**
Ran all the images and the images inside BOINC.zip through several lossless compression algorithms.

### CODE REVIEW

**Comment by barton2526** [comment]
@denravonska thoughts on removing [/contrib/Installer/boinc/boinc/Resources/splash.png](https://github.com/Peppernrino/Gridcoin-Research/blob/173e7e561bfa67423eeb770e8efc2b6eca749153/contrib/Installer/boinc/boinc/Resources/splash.png) while we're at it?  This image is very old and seems to be completely unused.

Edit: I think we can remove [this jpg version](https://github.com/Peppernrino/Gridcoin-Research/blob/173e7e561bfa67423eeb770e8efc2b6eca749153/contrib/Installer/boinc/boinc/Resources/splash.jpg) and [this image of an open pit mine](https://github.com/Peppernrino/Gridcoin-Research/blob/173e7e561bfa67423eeb770e8efc2b6eca749153/contrib/Installer/boinc/boinc/Resources/mining.jpg) too lol

**Comment by Peppernrino** [comment]
always wondered why tx_minedoie_WOEI3ooIzGHI.png had such a whacky name. could we just change it to tx_mined? or is it also ununsed?

**Comment by denravonska** [comment]
Nuke them all if they're unused.

**Comment by tomasbrod** [comment]
Please KISS. remove images in separate pr.

**Comment by barton2526** [comment]
Will create a new PR @tomasbrod 

See PR #1053

**Pull request merged**
