### PR TITLE
Change team whitelist separator to <> to accomodate more team names.

### PR DESCRIPTION
**Pull request by jamescowens**

### CODE REVIEW

**Comment by jamescowens** [comment]
That should do it. Testing with my Linux explorer testnet node (using the current team whitelist string), all works as expected, and the team file is now with the <> delimiter.

The only part that is not tested is actually changing the delimiter in the protocol TEAM_WHITELIST variable to use '<>', but I can't really do that. The new GetTeamWhitelist() function detects whether '<>' is present in the string, and if so uses that delimiter, otherwise the pipe delimiter. That should work. When we activate [H]ard|OCP I will update the string to use the new delimiter.

Any scraper node can update with this change and remain compatible, but I cannot update the protocol string to use the new delimiter until all scraper nodes on that network are updated.

**Comment by cyrossignol** [comment]
Looks good, I think. Testing this now.

**Comment by jamescowens** [comment]
@cyrossignol bump...

**Review by cyrossignol — APPROVED** [review]
Looks good to me. The scraper replaced the delimiters in the team ID as expected, and I think this will work for the new contracts.

**Comment by jamescowens** [comment]
Awesome. Merging.

**Pull request merged**
