### PR TITLE
build: Qt 5.15.2

### PR DESCRIPTION
**Pull request by barton2526**
> Opening this for visibility. Apart from it probably being time to use a newer version of Qt for releases, an update is required so that we are using a version which has a C++17 mode.
> 
> The biggest change here is that [Qt no longer has internal xcb libs](https://codereview.qt.nokia.com/c/qt/qtbase/+/253905), so we need to build the requirements ourselves.

Ref: https://github.com/bitcoin/bitcoin/pull/19716
Ref: https://github.com/bitcoin/bitcoin/pull/23489

- build, qt: Ditch no_sdk_version_check.patch
Ref: https://github.com/bitcoin/bitcoin/pull/23618

- build: Post-pr23489 small cleanups
Ref: https://github.com/bitcoin/bitcoin/pull/23675

- build, qt, macOS: Don't hard-code x86_64 as the arch when using qmake 
Ref: https://github.com/bitcoin/bitcoin/pull/23583

### CODE REVIEW

**Comment by barton2526** [comment]
CI is failing on Windows. Any assistance in debugging would be appreciated.

Here is the error I see locally:
```compiling rhi/qrhi.cpp
In file included from rhi/qrhi.cpp:49:0:
rhi/qrhid3d11_p_p.h:57:10: fatal error: dxgi1_3.h: No such file or directory
 #include <dxgi1_3.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile.Release:71665: recipe for target '.obj/release/qrhi.o' failed```

**Comment by barton2526** [comment]
Here is a patch we could use
https://github.com/bitcoin/bitcoin/pull/19716#issuecomment-682155809

**Comment by barton2526** [comment]
This currently compiles for me on Windows 10 WSL cross-compile (Ubuntu Bionic)

image

**Comment by jamescowens** [comment]
@barton2526 please rebase this to development now that I merged #2484.

**Comment by barton2526** [comment]
Moved to #2486

**Pull request closed without merging**
