### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Peppernrino**
Added link to BOINC site.
SSL'd main site.
Updated Tags URL.
Removed duplicate paragraph.
Grammar.
Capitalized Freenode and IRC.
Updated IRC channel to #gridcoin-help, as it is the help channel and you have to be a registered user to use #gridcoin.
Made Slack link clickable with invite link behind it.
Fixed header line markdown.
Removed unnecessary spaces.

### CODE REVIEW

**Review by tomasbrod — APPROVED** [review]

**Comment by sedited** [comment]
I'd prefer this directly into master. I don't see any conflicts with existing pr's and we can ask people in the future to submit seperate pr's , if they want to edit the README as part of their larger pull request.

**Comment by Peppernrino** [comment]
so... i'll redo this in master branch, then? :)

**Comment by tomasbrod** [comment]
no, let it be. Ravon can cherrypick

**Comment by Peppernrino** [comment]
as per @TheCharlatan 's advice, i made a larger pull request, and included the readme update with it. :+1: see #1342

**Pull request merged**
