### PR TITLE
Gridcoin-themed BOINC Skin

### PR DESCRIPTION
**Pull request by Peppernrino**
Swapped out default BOINC skin for our Gridcoin-themed BOINC skin from https://github.com/gridcoin-community/BOINC_Skin

It is much smaller in size, and produces way less errors in the stderrgui.txt file. Also, branding! :D

### CODE REVIEW

**Comment by barton2526** [comment]
I don't think these files are used anymore.  @Foggyx420 @denravonska ?

**Comment by denravonska** [comment]
Seeing as they are in the scraper bin folder I highly doubt they are needed. It's better to axe them and put the skin in a separate repo.

**Comment by denravonska** [comment]
@Peppernrino Can move these to a separate repo. We can set it up in Gridcoin-Community.

**Comment by Peppernrino** [comment]
It's already in the Gridcoin Community repo as an option! :P 

https://github.com/gridcoin-community/BOINC_Skin

And as always, I'd rather see images removed altogether than replace them with arbitrary changes. No problems here. <3

**Pull request closed without merging**
