### PR TITLE
ci: Port lint scripts from bitcoin

### PR DESCRIPTION
**Pull request by div72**
Adds lint scripts and a Travis job for them, also includes some typo fixes.

### CODE REVIEW

**Comment by cyrossignol** [comment]
Oof...

**Comment by cyrossignol** [comment]
Nice start. Some good stuff in there. A lot of noise, though. Will take some time to knock out the whole rule set. We may plug this in with `allow_failures` to begin with.

**Comment by barton2526** [comment]
This is really useful and pretty much exactly what I was trying to get working, just in a different way.  Thanks @div72 !

**Comment by jamescowens** [comment]
A bug with lint. It is treating an escaped % in a LogPrint argument as an argument format specifier.

**Comment by jamescowens** [comment]
Our position on boost is different than Bitcoin, so we need to adjust those rules.

**Comment by jamescowens** [comment]
All calls to LogPrintf() and LogPrint() should be terminated with \n. This is not true with us, and we should change the rule. This is a stupid rule and when I ported the logging system I changed the underlying functions to put the \n terminator in there underneath so I did not literally have to go through every single LogPrint statement and change each one. Give me an example (realistically) of where you want to do a logging statement and it shouldn't have a \n termination. Exactly. There isn't a realistic one.

**Comment by jamescowens** [comment]
A general comment about Bitcoin... those people are not God, and just because they do stuff doesn't mean we will automatically follow. We have to keep in mind the rebase, but we will NOT be slaves to them.

**Comment by div72** [comment]
> A general comment about Bitcoin... those people are not God, and just because they do stuff doesn't mean we will automatically follow. We have to keep in mind the rebase, but we will NOT be slaves to them.

Agreed, although I won't complain if we decide to follow their decision about boost.

**Comment by div72** [comment]
Also doesn't `#pragma once` do the same thing as include guards? Perhaps we can change the existing include guards with it?

**Comment by jamescowens** [comment]
On Boost... I have mixed opinions. Many things that have ended up in the std libraries originated in Boost (with slight changes of course). Be that as it may, if standard library implementations suffice, we should use those. One of the biggest gaps is the boost filesystem classes, which are really elegant. IIRC those are being put in std (with some tweaks as usual). We are also using some of the boost extended stream implementations, including filters, and some of the calendaring classes which are also very useful.

My view on this is that we should minimize the use of boost to only those areas where there is not an acceptable std library implementation... for example, we ought to be able to rip out all of the boost thread handling and replace with std implementations.

**Comment by cyrossignol** [comment]
Bitcoin uses Boost (and other third-party libraries like OpenSSL) conservatively not as a form of elitism. The project suffered several consensus failures in the past because of subtle behavior variations between library versions and their implementations for different platforms. For this reason, the maintainers review the use of third-party libraries very closely. Gridcoin experienced forking issues caused by Boost in the past as well. 

As we know, lints are a sanity check tool, not an injunction. They draw human attention to code that may need closer inspection. The Boost rules do not ban the use of the library&mdash;these ensure that no one overlooks the use of those libraries in consensus-critical code. I continue to support the application of Boost where it makes sense. We should minimize its presence where we have better tools.

**Comment by jamescowens** [comment]
I agree, and I am not arguing that the Bitcoin dev's attitude towards third party libraries is based on elitism... The snottiness there extends across the board I think... but they do have some talented folks working on Core, and they are justified in their attitude given the status of Bitcoin Core in the world of cryptocurrency.

We are in agreement. In fact I would argue we should minimize its presence if we have adequate tools in the standard libraries, and should only use Boost or other third party libraries if their use prevents onerous work, or the risk would actually INCREASE if we did NOT use them. That could be true for specialty libraries where a custom coded replacement could actually have more problems than the library you are trying to replace!

On the use of other third party libraries, I agree we need to control the dependencies, especially in consensus-critical code. For example we should finish the port of Bitcoin's replacement of OpenSSL for the purposes of signatures, etc, although we will have to maintain the OpenSSL dependency for the sole purpose of CURL. (I for one do NOT want to try and custom code a replacement for CURL. It is very capable and we are not likely to do better...)

**Comment by cyrossignol** [comment]
> Also doesn't #pragma once do the same thing as include guards? Perhaps we can change the existing include guards with it?

@div72 Yes, it effectively does the same thing. Let's leave Bitcoin's include guards alone for now. We can update the linter to allow our use of `#pragma once`.

**Comment by cyrossignol** [comment]
@div72 Before you get too far down the rabbit hole, let's freeze the de-linting and review this PR as-is. We can add the lint stage to CI without blocking other PRs until we address the remaining violations (and some of these will go away as we port Bitcoin's newer code). Since many of these changes will touch a lot of files, merging a huge PR may create a lot of conflicts for other people's branches. On the flip side, continuously rebasing this branch on top of other incoming PRs will make it very hard to review. I look over non-trivial PRs commit-by-commit, and I have to start over for a rebase, so it will save me a lot of work 🙂

**Comment by div72** [comment]
@cyrossignol Mind if I pull c2ed11e back?

**Comment by cyrossignol** [comment]
@div72 No, please do. We can reapply when the commit is ready.

**Comment by div72** [comment]
No idea why fast_finish doesn't work, but since the lint stage takes like a minute I don't think it's much of an issue.

**Comment by jamescowens** [comment]
I really like this PR, but I want to discuss merge strategy a little more. @cyrossignol is right, this could cause a lot of rebase work for branches that people may have in progress, although we are at a real low point on PR's, which is a good thing in respect to this one.

Also, the development branch is temporarily in a frozen state except for fixes that I deem worthy for admission into Fern, but any fixes for Fern are pointwise, and can start on a commit base post this PR merge, so I don't see it as a problem.

@cyrossignol what is your opinion on this? Wait until after Fern release when the development branch is unfrozen?

**Comment by div72** [comment]
I mean I can pull a6f5e60 and 3292f8c since the lint job failing doesn't effect the build status which should pretty much eliminate the need to rebase for most, then again this PR is not really an urgent one.

**Comment by jamescowens** [comment]
Yeah, but I don't want you to have to continually rebase, either. It would seem to me that the right time to do this is right after the release as the first post release merged PR...

**Review by cyrossignol — APPROVED** [review]
I see no reason not to merge this to development. The application-specific changes are all cosmetic. This is a great tool to have, and we can finish the remaining items incrementally for more manageable conflicts.

**Comment by jamescowens** [comment]
Merging.

**Pull request merged**
