### PR TITLE
Removed all instances of the volatile keyword

### LINKED ISSUE #187: Remove volatile declarations
There are a number of variables declared volatile, which I assume is with the intention of using them in a multithreaded environment. However, the keyword is not intended to to guard the software against other threads, only to notify the compiler that the data might be changed outside of the application scope. For example, through an interrupt in a microcontroller.

Using volatile for variables like this should do more harm than good since it prevents the compiler from applying some optimizations when reading those variables. I have seen some rumours that the Microsoft compiler does provide scope guards for volatile but I'm not sure if it's more than rumours and it's very platform dependent.

I'll do some testing for this on Linux.

### PR DESCRIPTION
**Pull request by pwnorbitals**
Fixes #187 
Also fixes an unsigned vs signed comparison warning

### CODE REVIEW

**Comment by iFoggz** [comment]
try to keep certain things separate in different commits. like unsigned vs signed stuff separate from volatile. :)

**Comment by pwnorbitals** [comment]
It was [on-the-go refactoring](https://github.com/gridcoin/Gridcoin-Research/wiki/On-the-go-refactoring)

**Review by tomasbrod — COMMENTED** [review]
Plz no. That volatile modifier is actually needed for inter-thread communication.

**Comment by pwnorbitals** [comment]
You should have said it when https://github.com/gridcoin/Gridcoin-Research/issues/187 was brought up... It dates back from january !
Do you know exactly which variables should be kept volatile ?

**Comment by tomasbrod** [comment]
I thought I said that, but apparently no comment exists 🤔

**Comment by denravonska** [comment]
@brod No, volatile is needed when the linker cannot see any references to the variables.It is not a locking mechanism.

**Comment by denravonska** [comment]
Hmmmmm, need to double check. http://www.drdobbs.com/cpp/volatile-the-multithreaded-programmers-b/184403766

**Comment by denravonska** [comment]
Yeah:

> Bjarne Stroustrup says as much in TCPPPL4E:
>
> Do not use volatile except in low-level code that deals directly with hardware.
>
> Do not assume volatile has special meaning in the memory model. It does not. It is not -- as in some later languages -- a synchronization mechanism. To get synchronization, use atomic, a mutex, or a condition_variable.

Since the variables ARE shared between threads it does make sense to replace the volatility with atomic to get proper protection.

**Comment by tomasbrod** [comment]
Yes that will properly solve the issue. But now, as the volatile is removed, we can have problems.

**Pull request merged**
