### PR TITLE
gui: Updated Russian localization

### PR DESCRIPTION
**Pull request by 3man001**

### CODE REVIEW

**Comment by jamescowens** [comment]
We are doing all translations through https://www.transifex.com/gridcoin/gridcoin/.

**Comment by jamescowens** [comment]
Thanks for your efforts on this! :)

**Comment by 3man001** [comment]
It's clear. I sent a request to join the team.
P.S. It would be nice to have the translation information posted in a prominent place.

**Comment by jamescowens** [comment]
Looks like you put this up on Transifex as a bulk upload. We will close this PR as part of the Janice release process. We are updating the translation process in the docs. Thanks!

**Comment by jamescowens** [comment]
Closing this PR. The equivalent was processed through Transifex.

**Pull request closed without merging**
