### PR TITLE
Add freedesktop.org desktop file and icon set

### LINKED ISSUE #280: Desktop file is missing
A [XDG desktop file](https://standards.freedesktop.org/desktop-entry-spec/latest/) is missing.
It should be installed by `make install` on the Linux platform.

The only thing I could find is
https://github.com/gridcoin/Gridcoin-Research/blob/4efc4a1abe85f69dcca4e6b95154226ba9f9ff64/src/qt/guiutil.cpp#L401-L406

### PR DESCRIPTION
**Pull request by a123b**
I wrote a desktop file for Gridcoin.

If you want to add a translation or have any suggestions for improvements, leave a comment and I'll try to add it. 

I'm also not very familiar with automake, not sure if this is the correct way to do this...

Fixes #280.

### CODE REVIEW

**Comment by denravonska** [comment]
Neat :)

`GenericName[sv]=Kryptovaluta som belönar beräkningar genom BOINC`

**Comment by jamescowens** [comment]
This can go in Denise too. Looks ok to me. @TheCharlatan should take a quick look at it.

**Comment by jamescowens** [comment]
This appears to mostly work. If I do a compile on my Odroid running Mate, and the do ./configure --with-incompatible-bdb --prefix=/usr and do the full build and then sudo make install, it installs a menu item, but the icon is not shown in the item.

Doing sudo update-icon-caches /usr/share/icons/* updates the icon cache and then the menu item/desktop item is displayed properly.

I am not sure whether it is appropriate for the make install to execute that command. Comments?

**Comment by a123b** [comment]
Added Swedish translation. Also dropped the `-qt` from the .desktop filename to be consistent with the executable and icon name.

As for the icon cache issue, this is only an issue if you do a local `make install`. Don't know how common that still is nowadays. If you install it as a package, it's up to the package manager to call these commands anyway (I think `update-desktop-database` and `update-mime-database` should also be called). I even think this is somewhat distro-specific, for example on openSUSE and Arch I don't have `update-icon-caches`, but `gtk-update-icon-cache`...

**Comment by jamescowens** [comment]
Only devs :). Based on that I think good to go.

**Review by jamescowens — APPROVED** [review]

**Comment by jamescowens** [comment]
Merging to dev for testing. @denravonska do we want to put this in Denise (staging) too?

**Pull request merged**
