### PR TITLE
build: Implement Github Workflow Testing

### PR DESCRIPTION
**Pull request by nathanielcwm**
Attempting to implement Github Actions as a second opinion for testing.

It's my first time using Github Workflows so it might be a little shoddy.

Current Status:
Mac Build
Mac Build (Cross Compile)/badge.svg?branch=workflow)
Windows (64 Bit)/badge.svg?branch=workflow)
Ubuntu Build (Bionic, x86_64)/badge.svg?branch=workflow)
ARM Build

### CODE REVIEW

**Comment by denravonska** [comment]
I'm not well versed in the Github CI, but other systems have templates or custom tasks. You should be able to share most of the code between the workflows and only (?) invoke the build part differently. Azure DevOps calls this "templates".

**Comment by nathanielcwm** [comment]
I'll look into it

**Comment by nathanielcwm** [comment]
@denravonska https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
this seems like it.

**Comment by nathanielcwm** [comment]
doesn't seem very useful for our purposes except for storing the build / configure flags + dependencies

**Comment by denravonska** [comment]
This replaces Travis, no?

**Comment by nathanielcwm** [comment]
It's supposed to be more of an alternative honestly.

**Comment by jamescowens** [comment]
Are all the builds passing yet?

**Comment by nathanielcwm** [comment]
The mac builds aren't working but the others seem to work.

**Comment by jamescowens** [comment]
How are you doing on this?

**Comment by nathanielcwm** [comment]
Sorry I haven't had a lot of time to work on this.

**Comment by jamescowens** [comment]
No problem. We still have Travis for the time being... :). Maybe we can pick this back up later...

**Pull request closed without merging**
