### PR TITLE
random: port upstream random changes

### PR DESCRIPTION
**Pull request by div72**
This PR ports random(env).(cpp|h) from upstream. The reasoning for this PR being that FastRandomContext could be used in tests to increase determinism and porting these changes gets us closer to upstream, easing further ports. (Like cuckoocache, which does use functions from the new random.h, that is required for my work on main.(cpp|h).)

Needs #2367. The first two commits will disappear after the merge of that PR.

### CODE REVIEW

**Comment by barton2526** [comment]
Thank you for undertaking this.  We can port so much other stuff once this is in.

**Comment by barton2526** [comment]
https://github.com/gridcoin-community/Gridcoin-Research/pull/2365 interacts with https://github.com/gridcoin-community/Gridcoin-Research/pull/2368/commits/c341b45bdbd6d8d2f2c5f6f285486186a7c80a0d.  @jamescowens should I close my PR in favor of this?

**Comment by div72** [comment]
@barton2526 I disagree, your PR is much more related to crypto than mine. It might even make sense to move c77e39d and c341b45 to your PR in my opinion.

**Comment by barton2526** [comment]
> 
> 
> It might even make sense to move [c77e39d](https://github.com/gridcoin-community/Gridcoin-Research/commit/c77e39d4c3e14011e8933faec181e7a56d1892d1) and [c341b45](https://github.com/gridcoin-community/Gridcoin-Research/commit/c341b45bdbd6d8d2f2c5f6f285486186a7c80a0d) to your PR in my opinion.

Do either of those commits depend on the existence of random.h?  If not we can add them to my PR.

**Comment by jamescowens** [comment]
I think we should move them to @barton2526's PR.

**Comment by barton2526** [comment]
> 
> 
> @barton2526 I disagree, your PR is much more related to crypto than mine. It might even make sense to move [c77e39d](https://github.com/gridcoin-community/Gridcoin-Research/commit/c77e39d4c3e14011e8933faec181e7a56d1892d1) and [c341b45](https://github.com/gridcoin-community/Gridcoin-Research/commit/c341b45bdbd6d8d2f2c5f6f285486186a7c80a0d) to your PR in my opinion.

These commits are now in #2365

**Comment by jamescowens** [comment]
Once 2367 is corrected with a revision PR and that is merged, please rebase this on that merged PR, as this has the same problem baked in.

**Review by jamescowens — CHANGES_REQUESTED** [review]
Looks good except the issues tied to #2367.

**Review by jamescowens — APPROVED** [review]
ACK. Good job on this. I ran tests on a testnet node.

**Comment by jamescowens** [comment]
Sanity testing checks out.

**Pull request merged**
