### PR TITLE
build: Fix depends cross-compilation for macOS

### PR DESCRIPTION
**Pull request by cyrossignol**
This is a series of fixes and updates that clean up a huge mess in the depends system to allow for static cross-compilation and packaging of macOS artifacts with the project's built-in tools.

I updated several of the depends configurations from Bitcoin to help fix some of the underlying issues. This bumps the Qt version slightly from 5.9.6 to 5.9.8. Please expand the commit descriptions for details.

### CODE REVIEW

**Comment by jamescowens** [comment]
This looks ready. Remove from draft?

**Comment by cyrossignol** [comment]
Have a couple things left to clean up.

**Comment by div72** [comment]
Could you remove `doc/README_osx.MD`?

**Comment by cyrossignol** [comment]
@div72 Good call. I merged some useful bits into contrib/macdeploy/README.md and squashed.

**Review by jamescowens — APPROVED** [review]
Headache generating. Looks good to me.

**Review by div72 — APPROVED** [review]
utACK

**Comment by Git-Jiro** [comment]
Hi @cyrossignol
can you share the commands (autogen, configure and make flags) you used to build the static DMG?
A lot of users are craving for binaries that support older macOS versions.
I would like to include a DMG with the statically linked binary at https://github.com/Git-Jiro/homebrew-jiro build

**Comment by cyrossignol** [comment]
@Git-Jiro The commands are in [this doc](https://github.com/gridcoin-community/Gridcoin-Research/tree/development/contrib/macdeploy). The trickiest bit is getting a specific Xcode SDK version to build against. Due to licensing, we cannot endorse a distribution of the SDKs. You can look at [the CI scripts](https://github.com/gridcoin-community/Gridcoin-Research/blob/20ed7d6378bd906a641c60677737dc7a9adbf924/ci/test/05_before_script.sh#L16) for hints if you're creating your own pipeline. 

Note that static build support for macOS is only complete on the development branch right now. You can merge this PR into master if you want to work on the build before the next release. Some of the improvements here also apply to dynamic builds, so you may be able to adapt your formula to use `make deploy` to create the DMG.

**Pull request merged**
