### PR TITLE
Correct tally on init

### PR DESCRIPTION
**Pull request by denravonska**
Add support for tallying from a certain block and to find the closest tally block given a certain starting point.

This fixes the issue where we risk tallying from the wrong block on init.

### CODE REVIEW

**Review by iFoggz — COMMENTED** [review]
this will be interesting to test. how were you results?

**Comment by denravonska** [comment]
I have not seen this be an issue yet but it looks like there's a 50% risk we use the incorrect tally window on init.

screenshot_2018-02-04_08-33-21

**Review by tomasbrod — COMMENTED** [review]
If tally_v9 uses some global structures as source, then supplying a block to go from will produce inconsistent results.

**Comment by denravonska** [comment]
@tomasbrod I will double check the execution paths just to be sure.

**Comment by tomasbrod** [comment]
I could have done that for tally instead of connecting back and forth in reorgnew.

**Comment by denravonska** [comment]
I could not find anything which uses pindexBest directly.

**Pull request merged**
