### PR TITLE
Move shutdown poll block to end of AppInit2.

### PR DESCRIPTION
**Pull request by denravonska**
This fixes the issue where daemonizing cause the fork to exit.

Not too pleased with the solution so if anyone ha a better way I'm all ears.

### CODE REVIEW

**Comment by nicola-d** [comment]
Still having issues with daemonizing:

1/13/18 12:29:33 ***************************************** GRIDCOIN RESEARCH ****************
***********************************^M
01/13/18 12:29:33 Gridcoin version v3.7.3.0-gbca68109d-dirty (2018-01-09 00:40:35 +0200)
01/13/18 12:29:33 Using OpenSSL version OpenSSL 1.1.0g  2 Nov 2017
01/13/18 12:29:33 Default data directory /home/nicola/.GridcoinResearch
01/13/18 12:29:33 Used data directory /home/nicola/.GridcoinResearch
01/13/18 12:29:33 dbenv.open LogDir=/home/nicola/.GridcoinResearch/database ErrorFile=/home/ni
cola/.GridcoinResearch/db.log
01/13/18 12:29:33 Loading block index...
01/13/18 12:29:33 Mode=Prod^M
01/13/18 12:29:33 Opening LevelDB in /home/nicola/.GridcoinResearch/txleveldb
01/13/18 12:29:33 Transaction index version is 180015
01/13/18 12:29:33 Opened LevelDB successfully
01/13/18 12:29:33 Loading DiskIndex 0
01/13/18 12:29:33 Flush(true) db not started
01/13/18 12:29:33 Stop RPC IO service
01/13/18 12:29:33 RPC IO server not started
01/13/18 12:29:33 Gridcoin exited

01/13/18 12:29:33 Wait for 0 threads to join.
01/13/18 12:29:33 Time to memorize diskindex containing 1694 blocks :              70ms^M
01/13/18 12:29:33 Shutdown requested. Exiting.
01/13/18 12:29:33 gridcoinresearch exiting...^M
01/13/18 12:29:33 Flush(false)
01/13/18 12:29:33 DBFlush(false) ended               0ms
01/13/18 12:29:33 StopNode()
01/13/18 12:29:33 Wait for 0 threads to join.
01/13/18 12:29:33 Flush(true)
01/13/18 12:29:33 DBFlush(true) ended               0ms
01/13/18 12:29:33 Stop RPC IO service
01/13/18 12:29:33 RPC IO server not started
01/13/18 12:29:33 Gridcoin exited

01/13/18 12:29:33 Wait for 0 threads to join.

**Comment by denravonska** [comment]
Weird, it seems to be working for me :(

> 17030 ?        Ssl    0:55 ./gridcoinresearchd -testnet -daemon

**Comment by nicola-d** [comment]
Started with ./gridcoinresearchd &, it works for a while and then wallet stops staking. This is the last part of the debug.log:

*Reorganize**Postponing 80 reconnects
01/13/18 14:44:35 REORGANIZE
01/13/18 14:44:35 REORGANIZE: Disconnect 0 blocks; 33aeb728bf2015b92d58..33aeb728bf2015b92d58
01/13/18 14:44:35 REORGANIZE: Connect 1 blocks; 33aeb728bf2015b92d58..9f29572e4977b8938d3e
01/13/18 14:44:35 REORGANIZE Disc Size 0ERROR: FetchInputs() : 9d25522316 prev tx d4ac532c7a i
ndex entry not found
01/13/18 14:44:35 ERROR: Reorganize() : ConnectBlock 9f29572e4977b8938d3e failed
01/13/18 14:44:35 Reorganize failedInvalidChainFound: invalid block=ad020c21be5680075d3c  heig
ht=1134932  trust=3275838333972824660711873320762369734724920483558585417587759928124440585947
  blocktrust=2697360632  date=01/13/18 14:44:32
01/13/18 14:44:35 InvalidChainFound:  current best=33aeb728bf2015b92d58  height=1134851  trust
=3275838333972824660711873320762369734724920483558585417587759927779510058335  blocktrust=3861
693488  date=01/13/18 12:34:08
01/13/18 14:44:35 ERROR: SetBestChain() : Reorganize failed
01/13/18 14:44:35 ERROR: AcceptBlock() : AddToBlockIndex failed
01/13/18 14:44:35 ERROR: ProcessBlock() : AcceptBlock FAILED
01/13/18 14:46:25  Received block b99f8de508da392b96ca541d84e89f77159899c97d468b8a14ef53025d99
e8d9; AcceptBlock: Proof Of Stake V8 8
01/13/18 14:46:25 ^M
**Reorganize**Postponing 81 reconnects
01/13/18 14:46:25 REORGANIZE
01/13/18 14:46:25 REORGANIZE: Disconnect 0 blocks; 33aeb728bf2015b92d58..33aeb728bf2015b92d58
01/13/18 14:46:25 REORGANIZE: Connect 1 blocks; 33aeb728bf2015b92d58..9f29572e4977b8938d3e
01/13/18 14:46:25 REORGANIZE Disc Size 0ERROR: FetchInputs() : 9d25522316 prev tx d4ac532c7a i
ndex entry not found
01/13/18 14:46:25 ERROR: Reorganize() : ConnectBlock 9f29572e4977b8938d3e failed
01/13/18 14:46:25 Reorganize failedInvalidChainFound: invalid block=b99f8de508da392b96ca  heig
ht=1134933  trust=3275838333972824660711873320762369734724920483558585417587759928127612099244
  blocktrust=3171513297  date=01/13/18 14:45:52
01/13/18 14:46:25 InvalidChainFound:  current best=33aeb728bf2015b92d58  height=1134851  trust
=3275838333972824660711873320762369734724920483558585417587759927779510058335  blocktrust=3861
693488  date=01/13/18 12:34:08
01/13/18 14:46:25 ERROR: SetBestChain() : Reorganize failed
01/13/18 14:46:25 ERROR: AcceptBlock() : AddToBlockIndex failed
01/13/18 14:46:25 ERROR: ProcessBlock() : AcceptBlock FAILED
AppInit

**Comment by nicola-d** [comment]
Updated to  "version" : "v3.7.4.0-g33affac8b".

Problem seems disappeared :)

**Pull request merged**
