### PR TITLE
Hard Coded Seed Node Cleanup

### PR DESCRIPTION
**Pull request by barton2526**
Reference Issue #764 

Removed dead node (gridcoin.asia)
Removed duplicates (frankfurt, amsterdam)
Added two new seed nodes (nuad.de and www.grcpool.com)

I am open to other node suggestions if these are insufficient.

### CODE REVIEW

**Comment by grctest** [comment]
Would we be able to add some of gridcoinstats.eu nodes? 👍

**Comment by tomasbrod** [comment]
And ifoggz nodes?

But this dns seed list should not contain references to hostnames. Instead a record that resolves to multiple A/AAA records should be given. If needed, I can maintain one.

**Comment by barton2526** [comment]
@grctest This is a good idea, I will add gridcoinstats after checking with startail.

@tomasbrod I specifically did not add @Foggyx420 's node(s) because they contain his username in the URL and did not want it to look like node favoritism.  If people think it's okay, I can add ifoggz's node(s).

Regarding the hostnames: I merely edited the already existing format of the seed list.  If it needs to be modified that is outside the scope of my capabilities.

**Comment by iFoggz** [comment]
yea my nodes have A and AAAA ips for each host. sorry for my name. :package: i originally had my domain to have local network connections with dns. but never thought id run nodes till after the fact. nodes should start supporting ipv6 since most data centers are well beyond ipv6 ready

**Comment by tomasbrod** [comment]
I not clear myself.
The list of domain names in `strDNSSeed` is for DNS seeding, which works different than directly specifying hosts by name.The DNS seed name should resolve to multiple, not just one, node address. Correctly SRV records should be used for this, but SRV is not impl and this should work good too. So the dns query does not return ip address for one node, but for multiple independent nodes. Wallet then picks and tries them in arbitrary order. This allows for change in the full node list without having to change config file or release.
See: https://bitcoin.org/en/developer-guide#peer-discovery

So I think, we should have two such DNS names set up, like `seed.gridcoin.co` which would A-resolve to all (max 10) IP addresses of our full nodes. But it only supports IP addresses, not hostnames, so static IPs would be required, or rewrite it to use SRV record. So that is a little inconvenience.

**Comment by iFoggz** [comment]
i cud setup a seeds.* with two hostnames in it or more

**Comment by barton2526** [comment]
Added gridcoinstats nodes (cryptofans) and ifoggz seed address (http://seeds.gridcoin.ifoggz-network.xyz/).  Note that the address from @Foggyx420 points to 2 A records and 2 AAAA records.

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
why not actually use a small base list like the current small list barton26 originally used ( that i did months ago but was ignored and rejected )  , and when nodes that get added to the wiki have been around and stable etc after ## number of days or # months gets an A and AAAA record under node.gridcoin.us . 
That seems more logical than fighting over , who do we trust or who is my favorite person that hosts nodes or who do I not like and don't want on the list like high school kids?  
People whom have seen node DNS enties can do like customminer and his gridcoin.co.uk entries and  round robin behind that so they can add 2000 nodes and ip addresses and since they are seen nodes again can  do a bunch of stuff...  Allegedly , ask NeuralMiner round robin DNS entries are a security issue and risk to Gridcoin and the Gridcoin network.  I can see some logic after he removed it , but only when it comes to the hard coded seed nodes.
So adding your buddy or your lackey or beasties nodes to the source code is not a good idea. 

That or another idea is the seed nodes should have rules of ethics such as only a single ipv4 address and really , if smart an ipv6 address pointing to the same host and ONLY 1.

**Comment by barton2526** [comment]
These seeds were specifically selected to prevent perceived favoritism among developer or admin nodes.  

See this comment above: 
>@tomasbrod I specifically did not add @Foggyx420 's node(s) because they contain his username in the URL and did not want it to look like node favoritism. If people think it's okay, I can add ifoggz's node(s).

The addition of @Foggyx420 's node was only done after careful consideration and polling of the developer team.

**Pull request merged**
