### PR TITLE
Rewritten Build Instructions

### PR DESCRIPTION
**Pull request by G-UK**
Instructions have now been completely rewritten to match the latest updates on the Gridcoin wiki.
File does not exist on the development branch.

### CODE REVIEW

**Comment by iFoggz** [comment]
You should correct this. this is kind of a mess.  XD. Would of better if you just copied the contents of your changes then updated a branch to current commit (master branch top commit since its just a document) then placed your changes to eliminate this spaghetti. good work on the document.

**Comment by sedited** [comment]
As soon as the current development branch is the new release candidate, the documentation structure will change. Everything will be moved to doc/ . The .txt for Linux build instructions will be removed. If you want to make the change, then base your pull request onto hotfix.

**Comment by G-UK** [comment]
Sorry, screwed up my fork and had to reset everything. (Still learning Git)

I'll hold off any doc changes for now as this is already on the wiki.

**Comment by iFoggz** [comment]
its fine if u need help let me know

**Pull request closed without merging**
