### PR TITLE
ci: Add GitHub workflows

### PR DESCRIPTION
**Pull request by div72**
Credits to the contributors who wrote `.travis.yml` and @nathanielcwm

### CODE REVIEW

**Comment by jamescowens** [comment]
@div72 As you may have noticed, we do not do full graphical builds of all of the architectures in Travis. There are two reasons: 1. Travis has a timeout limitation that abends the full builds for the architectures where depends is used, so we can only really do the full graphical build on the dynlink version. This is a testing hole for sure. 2. The MacOS kit won't compile the GUI part in its current form. Would be nice to solve both of those problems. I would prefer to do a comprehensive build for each platform.

**Comment by RoboticMind** [comment]
What happened to the commit messages? Most of them only show up with `.` and `..` ? Did something go wrong with git?

**Comment by div72** [comment]
@RoboticMind No, I need to trigger CI a lot and since I'll squash all the commits into one I didn't feel the need to use proper commit messages, so I use only those two different messages so I can distinguish between them.

**Comment by div72** [comment]
You don't really need to pay attention to this PR before I mark it ready for review.

**Comment by jamescowens** [comment]
Maybe we don't need to pursue this since we have adopted successfully the modern Bitcoin Travis CI?

**Comment by div72** [comment]
I agree, there's not much of a need now.

**Pull request closed without merging**
