### PR TITLE
Interim new logo and splash screen

### PR DESCRIPTION
**Pull request by ghost**
This is not to undermine @skcin's great work on pull #517 High dpi improvements. I have replaced the icon, icons, and splash3 png files in order to get our new branding out to the public while using the wallet. The app logo and startup splash screen is the only thing changed. So use if desired.

### CODE REVIEW

**Comment by iFoggz** [comment]
is there anything more that can be done for the splash screen there is a lot of bare space around that logo. think the splash screen could either use a more fitting image or some use of the bare space

**Comment by ghost** [comment]
When you mean bare space, do you want lager size?  It looks fine on MacOS. I picked this logo so one could see the blocks loading. Other images this was not possible. The file image that you see is actually larger than the old splash, and is misleading to look at directly from here. 
screen shot 2017-10-09 at 6 00 10 am
screen shot 2017-10-09 at 6 01 18 am
screen shot 2017-10-09 at 6 01 45 am

**Comment by iFoggz** [comment]
ah so splash screen does resize smaller when there is a smaller splash image?

**Comment by ghost** [comment]
So you want it larger then?

**Comment by iFoggz** [comment]
no. lol if the splash screen resizes to the size of the image then its fine. I just thought we were going to have blank space above and below the logo in excess.

**Pull request merged**
