### PR TITLE
High dpi improvements

### PR DESCRIPTION
**Pull request by skcin**
So far the BOINC logo is replaced by its vector graphics version and the unit of measurement in the stylesheets is switched to svg. The intention is to make the Qt wallet scale on different systems with different DPI values. 
@denravonska  please don't merge this right away, there is more to come. (besides the merge conflicts)
I plan on putting the new icons/logo in as svg files too. I think the gui should then be tested on different platforms. (and on high dpi displays if anyone got one)

### CODE REVIEW

**Comment by grctest** [comment]
How's this coming along? Since several services began using the new logo, we went live with the new branding/logo on the gridcoin.us website. Don't forget the little grc logo within the msi installer 👍

**Comment by grctest** [comment]
Branding change applied to slack/telegram/twitter/website/reddit etc. Only the client to go now.

**Comment by skcin** [comment]
I am currently in the process of refining the color schemes. I will commit once it is done.

**Comment by skcin** [comment]
screenshot
screenshot2

**Comment by skcin** [comment]
@grctest do you know where the logo in the msi installer is located in the code?
@ravon We need to test this on as many platforms as possible. Not sure if svg images behave well.
Would be nice to test this on windows and mac too. There are some people offering testing on high DPI displays but they need binaries. (Mac and Windows)

**Comment by tomasbrod** [comment]
That first screen, there contract is too high imo.

**Comment by skcin** [comment]
We should also include @Peppernrino's #628 after this PR to get the icon changes in that I missed. All the .ico and .icns files and everything in share/pixmaps/.

**Comment by tomasbrod** [comment]
* [ ] Unlock button does not fit screen (it shows after 5px resize)
* [ ] Scroll-bar appears on bottom of the "Tabs toolbar"
snimka obrazovky_2017-09-21_20-09-45

**Comment by skcin** [comment]
@tomasbrod do you have a screen shot?

**Comment by denravonska** [comment]
@skcin Maybe you should merge @Peppernrino's branch into this one?

**Comment by tomasbrod** [comment]
Yup, I just attached it @skcin .

**Comment by iFoggz** [comment]
itd be nice if someone could modify something so if a message is in the boinchash that it shows something that indicates the tx comes with a message?

**Comment by ghost** [comment]
HI, this looks real good.  I am happy to help test this on mac book pro high resolution. I have been experimenting with the new logo on my forked repo and have the new purple hex logo running in my dock now. I can submit a pull request for the classic png files until you get the svg issue settled if you wish.

**Pull request merged**
