### PR TITLE
Move checks for cpidsignature, reward and magnitude

### PR DESCRIPTION
**Pull request by tomasbrod**
This moves the context sensitive checks to ConnectBlock, where context is.

cpidsignature: Context-free checks left in CheckBlock. Added a "fast" check to catch most obvious signature errors. Check the CPID validity (signature) in ConnectBlock.

reward: Removed CheckProofOfResearch call. Reward check was already in ConnectBlock /**please review an verify this**/. Magnitude check, that was done there too, was moved.

magnitude: Moved to ConnectBlock.

This needs some dark-clouded sky testing. (opposite to blue sky)

### CODE REVIEW

**Comment by tomasbrod** [comment]
Quick trying show me that dpor blocks staked on the other fork are accepted to index. They have less trust than my chain so no reorg happens.

Also changed over the beacon dump, it was bugging me.

**Comment by tomasbrod** [comment]
Todo:
```
Stake Reward of 2,638330 B 0,000000 I 2,638330 F 0 ea0727f14d27e24812b5fd5344a4419d   
Operation connectblock_researcher, ComputedAccrual 0,000000, StakeHeight 1155321,000000, RABlockSpan 6,000000, HistoryHeight1155315,000000, AccrualAge 0,008519, AvgMag 40,000000, MagUnit 0,250000, PPD 5,501060, Reference PPD 6,898038
```
Computed Accrual was 0, yet a block with 2.64 GRC reward was accepted.

I think it is one of the BlockNeedsChecked things.

It seems like that the Drift is calculated from the Claimed, not calculated, reward [here](https://github.com/tomasbrod/Gridcoin-Research/blob/73b392fce48d6c0f2da3ef4ce2d36ee7bca0548f/src/main.cpp#L3106). 15% from infinite is still a lot.

Edit: Newer-mind. It was a interest block, no research and I was doing another experiment.

**Comment by tomasbrod** [comment]
It stops on [this block 1144550](https://gridcoinstats.eu/block/58b2d6d0ff7e3ebcaca1058be7574a87efadd4b7f5c661f9e14255f851a6185e). It has a invalid signature, yet it is accepted in the main chain.

**Comment by tomasbrod** [comment]
The following block hashes fail the check on connecting:
```
58b2d6d0ff7e3ebcaca1058be7574a87efadd4b7f5c661f9e14255f851a6185e [E]
471292b59e5f3ad94c39b3784a9a3f7a8324b9b56ff0ad00bd48c31658537c30 [E]
5b63d4edbdec06ddc2182703ce45a3ced70db0d813e329070e83bf37347a6c2c [S]
13e8dee125c5d40d49df77428ad255deee69c44f96bae68b971ab20b0791db95 [S]
e9035d821668a0563b632e9c84bc5af73f53eafcca1e053ac6da53907c7f6940 [S]
9387774230f23a898b11c016533f7c5da6d095edec0e9347a147be8c3cada3ac [S]
```

[E]: has error string instead of signature
[S]: bad signature for some reason, but the key matches
[K]: key in block does not match loaded beacon key

**Comment by tomasbrod** [comment]
Todo: add DoS calls.

**Comment by tomasbrod** [comment]
I tried reorg from 1144210 to present with 3e2a0c7 and it passed. Indicating that the workaround works.
Still the txPrev error can cause stuck on a fork, but it outside the scope of #922 .
I declare this PR good for testing and reviews.

**Comment by tomasbrod** [comment]
When reviewing, please verify that conditions [L3135](https://github.com/gridcoin/Gridcoin-Research/pull/922/files#diff-7ec3c68a81efff79b6ca22ac1f1eabbaL3135) .. [L3145](https://github.com/gridcoin/Gridcoin-Research/pull/922/files#diff-7ec3c68a81efff79b6ca22ac1f1eabbaL3146) correctly catch blocks with DPoR reward higher than fair, calculated on [L3100](https://github.com/gridcoin/Gridcoin-Research/pull/922/files#diff-7ec3c68a81efff79b6ca22ac1f1eabbaL3100).

**Comment by tomasbrod** [comment]
I think that reward calc at [this line](https://github.com/tomasbrod/Gridcoin-Research/blob/staging/src/main.cpp#L3174) needs to be made same as on [this previous place](https://github.com/tomasbrod/Gridcoin-Research/blob/staging/src/main.cpp#L2173). In connectblock it is computed on pindex, but otherwise on pindexPrev.

**Comment by denravonska** [comment]
@tomasbrod Merging this now so we can continue testing. Will do additional review later. Should we fix the pindex/pindexPrev before release?

**Pull request merged**
