### PR TITLE
Add new checkpoint

### PR DESCRIPTION
**Pull request by barton2526**
Added block 1050000

### CODE REVIEW

**Review by tomasbrod — CHANGES_REQUESTED** [review]
Need signed commit.

**Comment by barton2526** [comment]
@tomasbrod Can this be done on Windows?

**Comment by barton2526** [comment]
@tomasbrod I have attached my gpg key to GitHub but am unsure of how to retroactively sign this commit.  Do I need to remove the commit and do it over again with the key?

**Comment by barton2526** [comment]
Signed Commit.  Please ensure I did this correctly.

**Review by tomasbrod — APPROVED** [review]
Correct signature. I also cross checked that the hash matches explorer.

**Comment by barton2526** [comment]
Why was this not pushed to master for the 3.7.7.0 release?  @denravonska

**Pull request merged**
